### ISSUE TITLE
Gemfile specifying ruby "2.0.0" cannot contain Ruby 2.0 syntax.

### ISSUE THREAD

**Issue by pda** [heroku/heroku-buildpack-ruby#100]
Ruby 2.0 syntax e.g. `%i{list of symbols}` is not supported in Gemfiles, even if they specify `ruby "2.0.0"`.

The resulting error `Invalid RUBY_VERSION specified` is misleading.

If the Gemfile can be detected and parsed as Ruby 2.0, that'd be great.
Short of that, a more correct error message would help.

Example Gemfile:

```ruby
source "https://rubygems.org"
ruby "2.0.0"
gem "dotenv-rails", groups: %i{development test}
```

Buildpack output:

```
-----> Ruby/Rails app detected
 !
 !     Invalid RUBY_VERSION specified: Gemfile-syntax-error:-groups:-%i{development-test}-^-/tmp/build_redacted/Gemfile:20:-syntax-error,-unexpected-$end-groups:-%i{development-test}-^
 !     Valid versions: ruby-2.0.0, ruby-1.9.3, ruby-1.9.2, ruby-1.8.7, ruby-1.9.3-jruby-1.7.0, ruby-1.8.7-jruby-1.7.0, ruby-1.9.3-jruby-1.7.1, ruby-1.8.7-jruby-1.7.1, ruby-1.9.3-rbx-2.0.0dev, ruby-1.8.7-rbx-2.0.0dev
 !
 !     Heroku push rejected, failed to compile Ruby/Rails app
```

**Comment by schneems** [comment]
Going to put this in the "won't fix" category. It won't change easily or any time soon.
