### ISSUE TITLE
Regression on master for deploying ember-cli-rails app

### ISSUE THREAD

**Issue by halfbyte** [heroku/heroku-buildpack-ruby#1001]
Hi @schneems I pinged you on twitter because of this. I think I have identified the offending commit and unfortunately it is 8413eec. I have yet to fully understand the issue but I am willing to help with debugging if possible. I guess a useful thing would be to have a minimal repro app that shows the same behaviour?

Here are some data points:

- Deploying using the currently released version of the buildpack (by just specifying `heroku/ruby`) works
- Deploying using master (using `https://github.com/heroku/heroku-buildpack-ruby`) fails (more on the failure later)
- Deploying using `https://github.com/heroku/heroku-buildpack-ruby#65c39f7e0d41bb9a44a9b74c0aafffc66250e487`works
- Deploying using `https://github.com/heroku/heroku-buildpack-ruby#8413eecb42ce8a99b47194ab9d237093175b915f` fails

The failure happens when ember-cli-rails tries to compile the ember app. It runs yarn install in the folder where the ember app is stored (`frontend` by default) where a package.json and a yarn.lock should be present. When a "broken" buildpack is at work, it looks as if yarn is instead either run in the root folder, where (historically) an empty package.json and yarn.lock is present.

I don't have enough inside knowledge about how this buildpack works to figure out why the corresponding commit would break that behaviour. The code in ember-cli-rails that installs the dependencies is [here](https://github.com/thoughtbot/ember-cli-rails/blob/master/lib/ember_cli/shell.rb#L35).

If it helps, I'll try to set up a minimal testing app. Unfortunately the app that breaks is closed source.

**Comment by schneems** [comment]
Thanks a ton. I'm asking for a Heroku support ticket at https://twitter.com/schneems/status/1262795473099751426 to link all of our communication together.

**Comment by 2468ben** [comment]
Same situation here, except that even with "heroku/ruby" specified as the buildpack, new review apps are hitting that error.

**Comment by schneems** [comment]
Linking internal support ticket https://heroku.support/876664

We tracked this failure mode to being a problem with the `bin/yarn` binstub that Rails generates:

```ruby
#!/usr/bin/env ruby
APP_ROOT = File.expand_path('..', __dir__)
Dir.chdir(APP_ROOT) do
  begin
    exec "yarnpkg", *ARGV
  rescue Errno::ENOENT
    $stderr.puts "Yarn executable was not detected in the system."
    $stderr.puts "Download Yarn at https://yarnpkg.com/en/docs/install"
    exit 1
  end
end
```

The ember-cli-rails gem runs the `yarn` command in different directories but this binstub forces the directory back to the root dir with `Dir.chdir(APP_ROOT)`. You can delete this file or remove those lines to un-break the app. I'm working on a remediation but it's difficult because either way we've got to break behavior. I just have to try to figure out if there's a way forward with minimial pain.

**Comment by halfbyte** [comment]
@schneems Sorry for not getting back to you earlier, I was just now able to test this properly, but our deploy is working with the buildpack pointing to master, so all good. Thanks for that quick fix!
