### ISSUE TITLE
Why does node lag so far behind releases?

### ISSUE THREAD

**Issue by ro-savage** [heroku/heroku-buildpack-ruby#1009]
Is there a reason the version of node in the ruby build pack lags so far behind releases?

Note v14 has been out for months and ruby buildpack is still on Node v10 which has been in maintenance for months.

I realise we can use the the node build pack to specify the version and I wouldn't expect this buildpack to be update with node within 24hrs like the node build pack. But why keep it so out of date? Surely it makes sense to keep it up to date with the latest LTS release?

**Comment by schneems** [comment]
We're using node 12 on master, it's just not been deployed yet as there are several known bugs that need to be worked out before deploying. 

If you ever see we're on an older non-LTS version of node you can let me know. We provide node in the Ruby buildpack as a convenience and for stability, I'm not super aggressive about rev-ing it.
