### ISSUE TITLE
Invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by conradchu** [heroku/heroku-buildpack-ruby#1019]
@schneems I think your latest PR merge https://github.com/heroku/heroku-buildpack-ruby/pull/1014 broke Heroku's compile of Rails.  

https://github.com/heroku/heroku-buildpack-ruby/blob/6499ce8b7e8c4e2df90332cc59746217fa620b09/lib/language_pack/helpers/binstub_check.rb#L27

Can't deploy anymore.

Here's the error:

-----> Ruby app detected
-----> Installing bundler 2.0.2
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
 !
 !     invalid byte sequence in UTF-8
 !
/app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/helpers/binstub_check.rb:27:in `match?': invalid byte sequence in UTF-8 (ArgumentError)
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/helpers/binstub_check.rb:27:in `block in call'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/helpers/binstub_check.rb:21:in `each'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/helpers/binstub_check.rb:21:in `call'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/ruby.rb:190:in `warn_bad_binstubs'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/ruby.rb:100:in `block in compile'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /tmp/tmp.M1UCauTKB3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/base.rb:50:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/base.rb:46:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/ruby.rb:94:in `compile'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/rails2.rb:62:in `block in compile'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /tmp/tmp.M1UCauTKB3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/base.rb:50:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/base.rb:46:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/rails2.rb:60:in `compile'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/rails3.rb:42:in `block in compile'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /tmp/tmp.M1UCauTKB3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/base.rb:50:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/base.rb:46:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/rails3.rb:41:in `compile'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/rails4.rb:41:in `block in compile'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /tmp/tmp.M1UCauTKB3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/base.rb:50:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/base.rb:46:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/rails4.rb:40:in `compile'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/bin/support/ruby_compile:20:in `block (2 levels) in <main>'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/base.rb:190:in `log'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/bin/support/ruby_compile:19:in `block in <main>'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:35:in `block in trace'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /tmp/tmp.M1UCauTKB3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/lib/language_pack/instrument.rb:35:in `trace'
	from /app/tmp/buildpacks/fde76f91bdbdb8c009b5556572b14f3142b1a896e60309cd28cbac478b708a2888980a1af963b94004133656ac4b16abec60e027dd6780105c4b047c55cbcf8a/bin/support/ruby_compile:15:in `<main>'
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by schneems** [comment]
This bug is coming from having a binary file in the `bin/` directory. For example if you had the ruby buildpack set on your app twice then the first run will put a binary in that location, and the second run will try to read it.

We can reproduce the bug locally like this::

```
irb(main):010:0> /foo/.match? Pathname.new(`which ruby`.chomp).open(&:readline)
Traceback (most recent call last):
        6: from /Users/rschneeman/.rubies/ruby-2.6.6/bin/irb:23:in `<main>'
        5: from /Users/rschneeman/.rubies/ruby-2.6.6/bin/irb:23:in `load'
        4: from /Users/rschneeman/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        3: from (irb):10
        2: from (irb):10:in `rescue in irb_binding'
        1: from (irb):10:in `match?'
ArgumentError (invalid byte sequence in UTF-8)
```

**Comment by conradchu** [comment]
Got it, thanks.  Yeah, we had it in there twice.  We removed it.  Closing the issue.

**Comment by schneems** [comment]
Great, glad you got it working. I'm going to re-introduce the binstub check again. I'm going to add a binary binstub check explicitly in it this time. Thanks for letting me know about the problem, sorry you hit this issue.
