### ISSUE TITLE
Frozen string error in latest commit (125191f)

### ISSUE THREAD

**Issue by aaronwieberg** [heroku/heroku-buildpack-ruby#1027]
Error:

`/lib/language_pack/helpers/binstub_wrapper.rb:59:in 'force_encoding': can't modify frozen String (FrozenError)`
  `from /lib/language_pack/helpers/binstub_wrapper.rb:59:in 'valid_utf8?'`
  `from /lib/language_pack/helpers/binstub_wrapper.rb:55:in 'binary?'`
  `from /lib/language_pack/helpers/binstub_wrapper.rb:31:in 'bad_shebang?'`

https://github.com/heroku/heroku-buildpack-ruby/blob/125191fdf57bf80f0cebf1f2d6009f77be6ae99a/lib/language_pack/helpers/binstub_wrapper.rb#L59

When `shebang` returns `""`, that is a frozen string literal. Changing that line to `shebang.dup.force_encoding("UTF-8").valid_encoding?` may work, not sure if that is the best solution. Thanks!

**Comment by schneems** [comment]
Thanks for the issue. I'll update it.

**Comment by schneems** [comment]
I've got a fix here https://github.com/heroku/heroku-buildpack-ruby/pull/1028

It looks like you've got an empty file in your `bin/` folder. Do you know what file it is or where it's coming from?

**Comment by aaronwieberg** [comment]
Ah yes, in my `bin` there's a .keep file that is empty `File.new('/app/bin/.keep').readline => EOFError`.
