### ISSUE TITLE
Ruby 2.3 Buildpack Failure

### ISSUE THREAD

**Issue by jcbantuelle** [heroku/heroku-buildpack-ruby#1043]
I have some apps running on Ruby 2.3.4 that suddenly stopped being able to be deployed. Based on the failure, it appears that the Heroku S3 bucket containing the various Ruby versions used by the buildpack has had all versions of 2.3 removed.

I completely understand why this decision was made and that it's no longer supported, but I'm in a somewhat difficult situation now since upgrading isn't going to be a viable quick option. I see that it's possible to change the location that it attempts to source this file from at https://github.com/heroku/heroku-buildpack-ruby/blob/main/lib/language_pack/base.rb#L21, and am happy to do so, but when I attempted to change this and point it to my own S3 bucket with a copy of Ruby 2.3.4 I got the following error:

`remote: /tmp/buildpackpBI9P/bin/compile: line 11: /tmp/tmp.dtj5ESzKD7/bin/ruby: No such file or directory`

Looking at the ruby versions still available on the S3 bucket, it appears that they have some specific expectations of what files will be in the archive, including an already compiled version of Ruby.

As a stopgap solution, do you have any advice for how to reconstruct a Ruby archive matching what the buildpack expects or is there some other way to get access to the Ruby archives that were removed?

**Comment by jcbantuelle** [comment]
I'm still unclear on what caused this issue to occur when no external changes were made, but after investigating further it appears that the problem is the deployments started using the wrong stack. Setting the ENV variable for `STACK` to `heroku-16` resolved the issue.

**Comment by schneems** [comment]
Please unset the variable, we manage it for you:


    $ heroku config:unset STACK


-- 
Richard Schneeman
https://www.schneems.com
he/him
