### ISSUE TITLE
Allow vendoring of .bundler/config

### ISSUE THREAD

**Issue by gregburek** [heroku/heroku-buildpack-ruby#106]
Currently, it is very difficult to get bundler to be aware of vendored binaries or of previous buildpacks that have altered the env vars to inject new paths into PATH, LDFLAGS, CFLAGS and LD_LIBRARY_PATH. Would it be possible to combine a vendored config file that would point bundler to non standard binary and source locations?

**Comment by schneems** [comment]
is this still an issue?

**Comment by tmgardner** [comment]
Here's a workaround buildpack that works around this: https://github.com/dwnld/heroku-buildpack-bundle-template

You create a bundle_template/.config and you can set any options you want in it, or access env vars.
