### ISSUE TITLE
Provide a way to specify a gem cache on first app build

### ISSUE THREAD

**Issue by scottjacobsen** [heroku/heroku-buildpack-ruby#1064]
Our `bundle install` from scratch take 10 minutes, and our asset compile takes several minutes, and seeding our database takes several minutes. When it is all said and done each initial review app build takes 30 minutes.

Our automated testing environment can re-use caches from other builds to avoid paying that cost on each new branch.

Provide a way to specify a command to download a tar.gz file containing a recent cache. This could just be a config var with a path to a script that is run before the assets are build/gems are installed. The dev would write the script to use `curl` or something else to download the .tar.gz file.

The cache would be extracted from the root app directory - this way the archive can contain a cache of gems, or assets, or node_modules, or all of the above.

It isn't the responsibility of this buildpack to maintain or keep the gem cache up to date, just to provide a simple way for developers to grab a tar.gz early in the process, and the buildpack would untar it before moving on.

**Comment by geoffharcourt** [comment]
This would be a pretty huge benefit for groups that work in small changes (which is also I think the ideal case for review applications vs. dedicated staging environments). Our `bundle install` from scratch takes exactly four minutes, and shaving that down would be pretty powerful.

One possible idea here that would not be specific to the buildpack but a more generalized pipelines capability (so it would also help with JS assets) would be to allow the buildpack to choose an initial slug to pull from if the application doesn't yet exist. For most applications this would be the primary staging environment. If we had that as our initial source of build cache stuff it would take care of both gems and NPM packages.

**Comment by schneems** [comment]
The generalized path forward would be to support native gem compilation and platform support like `nokogiri` introduced.

**Comment by geoffharcourt** [comment]
The carwow build cache buildpack is pretty useful for this case. We used it for about two years with success.
