### ISSUE TITLE
Bundle install gives `Errno::EROFS: Read-only file system @ dir_s_mkdir`

### ISSUE THREAD

**Issue by nertzy** [heroku/heroku-buildpack-ruby#1079]
Now that we are using the new Bundler 2.1.4 support released today, we are seeing the following issue:

```
-----> Installing dependencies using bundler 2.1.4
Running: BUNDLE_WITHOUT=development:test BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
There was an error accessing `/home/rof/cache/bundler/ruby/2.7.0`.
The underlying system error is Errno::EROFS: Read-only file system @ dir_s_mkdir
- /home
Bundler Output: There was an error accessing `/home/rof/cache/bundler/ruby/2.7.0`.
The underlying system error is Errno::EROFS: Read-only file system @ dir_s_mkdir
- /home

!
!     Failed to install gems via Bundler.
!
!     Push rejected, failed to compile Ruby app.

!     Push failed
    Build failed
```

**Comment by nertzy** [comment]
We tried clearing our cache but the problem still occurs.

**Comment by nertzy** [comment]
Our Gemfile.lock ends with:
```
RUBY VERSION
   ruby 2.7.2p137

BUNDLED WITH
   2.1.4
```

**Comment by nertzy** [comment]
This is happening for two of our Rails applications. They both pull from multiple gem servers and have a few gems from both public and private Git repos.

**Comment by nertzy** [comment]
Reverting to `https://github.com/heroku/heroku-buildpack-ruby.git#v218` is our workaround for now.

**Comment by schneems** [comment]
Sorry for this. I would love to investigate. Can you open a support ticket so I can take a look at your app? https://help.heroku.com search for "ruby buildpack" and link back to this thread. I'll need your app name and access as well (given in the support interface) please.

**Comment by nertzy** [comment]
Opened https://help.heroku.com/tickets/924657

Thanks!

**Comment by drewnichols** [comment]
I'm having the same issue with ruby 2.6.3 and bundler 2.1.4

**Comment by qortex** [comment]
Same issue. Not using Rails but custom Ruby (and roda). See https://github.com/rubygems/rubygems/issues/3284#issuecomment-704975760

**Comment by schneems** [comment]
This issue is coming from CodeShip. They're sending over a `.bundle/config` with some values in it that appear to take precedence over the env vars that we're now using see https://devcenter.heroku.com/changelog-items/1930.

1) The short term workaround is to change your CodeShip config to delete the `.bundle/config` file before deploy
2) If you have a copy of the config, can you provide it to me? I would like to see what's in there. 
3) Please contact CodeShip's support and ask them to remove the `.bundle/config` file before attempting to deploy to Heroku.

**Comment by joesiewert** [comment]
`.bundle/config` contains:

```
---
BUNDLE_PATH: "/home/rof/cache/bundler"
```

**Comment by yogodoshi** [comment]
Same here. I can push fine to Heroku but when Codeship deploys I receive the same error (pasting it here with a bit more info than OP's):

```
-----> Ruby app detected
-----> Installing bundler 1.17.3
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.6.6

###### WARNING:

You have the `.bundle/config` file checked into your repository
It contains local state like the location of the installed bundle
as well as configured git local gems, and other settings that should
not be shared between multiple checkouts of a single repo. Please
remove the `.bundle/` folder from your repo and add it to your `.gitignore` file.

https://devcenter.heroku.com/articles/bundler-configuration

-----> Installing dependencies using bundler 1.17.3
Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 BUNDLE_GLOBAL_PATH_APPENDS_RUBY_SCOPE=1 bundle install -j4
There was an error accessing `/home/rof/cache/bundler/ruby/2.6.0`.
The underlying system error is Errno::EROFS: Read-only file system @ dir_s_mkdir
- /home
Bundler Output: There was an error accessing `/home/rof/cache/bundler/ruby/2.6.0`.
The underlying system error is Errno::EROFS: Read-only file system @ dir_s_mkdir
- /home

!
!     Failed to install gems via Bundler.
!
!     Push rejected, failed to compile Ruby app.

!     Push failed
    Build failed
```

**Comment by schneems** [comment]
It looks like bundler considers the local `.bundle/config` file to take precedence over the env vars:

```
$ BUNDLE_PATH=/foo bundle config | grep path -a3

path
Set via BUNDLE_PATH: "/foo"
```

Versus when both the env var and the file are there:


```
$ mkdir .bundle
$ BUNDLE_PATH=/foo bundle config | grep path -a3
$ cat <<EOF > .bundle/config
> ---
> BUNDLE_PATH: "/home/rof/cache/bundler"
> EOF
$ BUNDLE_PATH=/foo bundle config | grep path -a3
path
Set for your local app (/private/tmp/3b304e6fe18bd8e74210f64bd1cfc488/.bundle/config): "/home/rof/cache/bundler"
Set via BUNDLE_PATH: "/foo"
```

Notice that the "set for your local app" takes precedence.  Has anyone managed to get in contact with CodeShip's support?

**Comment by yogodoshi** [comment]
@schneems I did, I'm waiting on their answer about telling me about a way to remove that `.bundle` folder before the deploy (cause I couldn't find how to do it on their UI) or them fixing this issue on their side.

**Comment by schneems** [comment]
> I'm waiting on their answer about telling me about a way to remove that .bundle folder 

Some others have mentioned to me they were able to do this via config with CodeShip. If you've managed to work around this issue, could you share how that was accomplished?

**Comment by joesiewert** [comment]
Try running your deploys again now. A fix was deployed to address this.

**Comment by yogodoshi** [comment]
It is working again for me. Thanks for the quick fix @joesiewert 🏅

**Comment by drewnichols** [comment]
My Codeship deploys are also working again.  Thank you!!

**Comment by schneems** [comment]
Awesome. Thanks!

**Comment by thorsummoner** [comment]
i found this thread while researching this issue: https://github.com/tootsuite/mastodon/issues/3676#issuecomment-873766178
