### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by qortex** [heroku/heroku-buildpack-ruby#1082]
https://github.com/heroku/heroku-buildpack-ruby/blob/master/CHANGELOG.md is not updated, which made understanding why #1080 happened just today difficult (release yesterday).

**Comment by schneems** [comment]
We've switched to using the `main` branch. The default view on GitHub is up-to-date https://github.com/heroku/heroku-buildpack-ruby/blob/main/CHANGELOG.md. I don't want to delete/remove the master branch for stability

**Comment by schneems** [comment]
I updated the changelog to link to the right place
