### ISSUE TITLE
Potentially misleading warning when asset pipline is disabled

### ISSUE THREAD

**Issue by jaredbeck** [heroku/heroku-buildpack-ruby#1097]
It's my understanding that `config.assets.enabled = false` completely disables the asset pipeline. So, in an app that is so configured, I think the following warning is misleading.

```plain
remote: -----> Detecting rails configuration
remote: 
remote: ###### WARNING:
remote: 
remote:        You set your `config.assets.compile = true` in production.
remote:        This can negatively impact the performance of your application.
remote:        
remote:        For more information can be found in this article:
remote:          https://devcenter.heroku.com/articles/rails-asset-pipeline#compile-set-to-true-in-production
```

**Comment by schneems** [comment]
If you set `config.assets.enabled=true` what you're telling Rails/Sprockets to do is compile your assets on the fly. It's incredibly expensive. From the link

> When you have compile on, this is what happens: Every request for a file in /assets is passed to Sprockets. On the first request for each and every asset it is compiled and cached in whatever Rails is using for cache (usually the filesystem). On subsequent requests Sprockets receives the request and has to look up the fingerprinted filename, check that the file (image) or files(css and js) that make up the asset were not modified, and then if there is a cached version serve that

Setting `config.assets.enabled=false` means that compilation is disabled, but you should still be serving assets that were precompiled at deploy time from your `public/assets` directory. It's a confusingly named config. The "correct" value of this setting in production is `false`.

**Comment by jaredbeck** [comment]
Thanks for the explanation. Let me see if I understand correctly.

Perhaps the warning should also say

> When `assets.enabled=false` (for example, when using only webpacker), please also set `assets.compile = false`. Even if `app/assets` is empty (again, e.g. when using only webpacker), `assets.compile` should still be set to `false` in production.

Would such an addition to the warning be correct? and helpful?

**Comment by schneems** [comment]
Sorry. I realized I got mixed up. I meant `config.assets.compile` in my reply for clarity.

**Comment by schneems** [comment]
To clarify what actually happens when you set `config.assets.compile=true` it adds this middleware into your app: https://github.com/rails/sprockets/blob/dba2802f8d6b9f54e3a057350cadd149316d0da5/lib/sprockets/server.rb

Then for every request, this method gets called https://github.com/rails/sprockets/blob/dba2802f8d6b9f54e3a057350cadd149316d0da5/lib/sprockets/server.rb#L65.

**Comment by jaredbeck** [comment]
Neat, I didn't know about the middleware. 

What do you think about my suggested addition to the warning message?
