### ISSUE TITLE
Allow `prepared_statements: false` in database.yml

### ISSUE THREAD

**Issue by gregburek** [heroku/heroku-buildpack-ruby#110]
Starting with AR 3.1, prepared_statements are default on when interacting with the db. Named prepared statements disallow transaction pooling with tools such as pgbouncer. Additionally, Postgres before 9.2 may experience a performance regression with certain prepared statement parameters as only the initial query plan is used for the lifetime of a prepared statement. Some paramaters would be better served by different query plans and will suffer when run. 

Rails documentation change: https://github.com/rails/rails/commit/c6663235f6ac2c9e09187c8413903211ddeb76d2

Rails open issue re pgbouncer: https://github.com/rails/rails/issues/1627

I'm a bit at a loss on how to trigger the inclusion of `prepared_statements: false` during the database.yml injection, otherwise a PR would be attached. Do you guys have a better idea about this?

**Comment by schneems** [comment]
we now no longer over-write database.yml in Rails 4.1+ so, done!
