### ISSUE TITLE
On stack upgrade, customers close to a working version need a better warning

### ISSUE THREAD

**Issue by schneems** [heroku/heroku-buildpack-ruby#1100]
```
-----> Ruby app detected
-----> Installing bundler 2.1.4
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.7.0.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.
       Command: 'set-o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-extrnal-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.7.0.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3.
 !
 !     The Ruby version you are trying to install does not exist on this stack.
 !     
 !     You are trying to install ruby-2.7.0 on heroku-20.
 !     
 !     Ruby ruby-2.7.0 is present on the following stacks:
 !     
 !     - cedar-14
 !     - heroku-16
 !     - heroku-18
```

This error tells them that 2.7.0 is not on their stack, but it does not tell them that 2.7.2 (which is really close) is present and they should us it.

**Comment by schneems** [comment]
Another thought discussed with support is to list available versions as a matrix on the devcenter article.


Something like 


|       | Heroku-16 | Heroku-18 | Heroku-20 |
|-------|-----------|-----------|-----------|
| 2.6.6 | ✅         | ✅         | ✅         |
| 2.6.5 | ✅         | ✅         |           |
| 2.6.4 | ✅         | ✅         |           |

**Comment by johlym** [comment]
One incantation of this I had in my head, which is less visually appealing (lacks emoji checkmarks) is something along the lines of:

|     | Heroku-16 | Heroku-18 | Heroku-20 |
|-----|-----------|-----------|-----------|
| 3.0 | 3.0.0     | 3.0.0     | 3.0.0     |
| 2.7 | 2.7.0     | 2.7.0     | 2.7.0     |
| 2.6 | 2.6.4     | 2.6.4     | 2.6.6     |
| 2.5 | 2.5.8     | 2.5.8     | 2.5.8     |

It's denser, but my thinking was being able to explain that if one wants to run X stack and Y `major.minor` version of Ruby, this is the minimum version they'll have to use to make it so. Admittedly it confused me at first that `2.6.5` is older than `2.5.8`, which is a whole thing in and of itself.

Along those same lines, it could be a good entry point to having a second table that shows the current _supported_ version in the same format.
