### ISSUE TITLE
Feature request: Allow `--local` to be specified when running `bundle install`

### ISSUE THREAD

**Issue by f1sherman** [heroku/heroku-buildpack-ruby#1107]
Recently there was some downtime on rubygems.org that disrupted some of our deploys. This was a surprise to me since we check our gems into source control. Reading through [the bundler documentation](https://bundler.io/man/bundle-cache.1.html#REMOTE-FETCHING) it appears that bundler depends on rubygems.org even when all gems are available locally:

> By default, if you run bundle install(1)](bundle-install.1.html) after running bundle cache(1), bundler will still connect to rubygems.org to check whether a platform-specific gem exists for any of the gems in vendor/cache.

...

> If you know for sure that the gems packaged in vendor/cache are appropriate for the platform you are on, you can run bundle install --local to skip checking for more appropriate gems, and use the ones in vendor/cache.

It would be great if we could have a way to specify that we want our gems to be installed with `--local` to avoid this unnecessary dependency. I'd be happy to contribute this change. Looking at the source, it wasn't clear to me how this should be configured, so I'd love some guidance on that. Should it be a new ENV var, a file checked in to the repository, etc.?

Alternatively we could have the buildpack always specify `--local` when the gems exist locally, but that would technically be a breaking change.

**Comment by schneems** [comment]
This is interesting. I've actually thought of caching contents of the Gemfile, Gemfile.lock, and any `BUNDLE_` config vars and then using this to conditionally skipping the `bundle install` altogether. Alternatively maybe using `bundle check` 

```
~ $ time bundle check
The Gemfile's dependencies are satisfied
real	0m1.771s
```

But that would be an extra second of overhead if things did change. It's a bit of a micro optimization though.

I would say that if the behavior you're describing existed in bundler, something like "--allow-local-fallback` then we would probably enable it. 

Regarding the specific request

> Allow `--local` to be specified when running `bundle install`

You can do this today by running:

```
$ heroku config:set BUNDLE_LOCAL=1
```

All bundler config flags can also be set by environment variables https://devcenter.heroku.com/articles/bundler-configuration

**Comment by f1sherman** [comment]
@schneems thank you for the detailed and timely response! I will give the `BUNDLE_LOCAL` env var a try. I knew that many bundler config options could be set by environment variables, but couldn't find anything indicating specifically that there was one for `--local`. Thanks again!

**Comment by dentarg** [comment]
> You can do this today by running:
> 
> ```
> $ heroku config:set BUNDLE_LOCAL=1
> ```

I'm not seeing `BUNDLE_LOCAL` working (using latest Bundler, 2.2.15), [see this CI build using `BUNDLE_LOCAL=1`](https://github.com/Starkast/wikimum/runs/2159428735?check_suite_focus=true):

```
Run bundle install --jobs 4
  bundle install --jobs 4
  shell: /bin/bash -e {0}
  env:
    BUNDLE_LOCAL: 1
    POSTGRES_URL: postgres://localhost/runner
Fetching gem metadata from https://rubygems.org/.........
Installing rake 13.0.3
...
```

vs [this CI build instead using `--local`](https://github.com/Starkast/wikimum/runs/2159414490?check_suite_focus=true)

```
Run bundle install --local --jobs 4
  bundle install --local --jobs 4
  shell: /bin/bash -e {0}
  env:
    POSTGRES_URL: postgres://localhost/runner
Installing rake 13.0.3
...
```

Only no "Fetching gem metadata from https://rubygems.org/" in the build using `--local`.

(I haven't dug in to check whether this is a bug in Bundler or they never had this feature.)
