### ISSUE TITLE
How to change the number of jobs bundler runs

### ISSUE THREAD

**Issue by johncadengo** [heroku/heroku-buildpack-ruby#1113]
Hi, I'm deploying with this build pack and I'm wondering if I can change the number of jobs. By default is shows 4, is there a way to change it?

```
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby.git
=====> Detected Framework: Ruby
-----> Installing bundler 2.1.4
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.7.2
-----> Installing dependencies using bundler 2.1.4
       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
```

The specific argument that I would like to change is `-j4`.

**Comment by schneems** [comment]
It's hardcoded in https://github.com/heroku/heroku-buildpack-ruby/blob/main/lib/language_pack/ruby.rb#L913

All builds happen on perf-m dynos which have 1 physical core and 1 hyperthread (so an nproc of 2). Setting to four is double that value already.

Did you have a specific use case?

**Comment by johncadengo** [comment]
@schneems It's a stretch to write "all builds happen" in one way or another. Would you be open to a PR to allow an ENV variable to override this hardcoded value?

**Comment by AndrewKvalheim** [comment]
I’m early in troubleshooting what I expect is a case of resource exhaustion and lowering this is one of the first things I wanted to try.
