### ISSUE TITLE
detect_needs_java Gemfile.lock errors if not exists

### ISSUE THREAD

**Issue by dzuelke** [heroku/heroku-buildpack-ruby#1125]
This line:

https://github.com/heroku/heroku-buildpack-ruby/blob/648a14986020ae6c681dbbba0895fe6bb542d5fd/bin/support/bash_functions.sh#L77

will print a `grep` error message if `Gemfile.lock` doesn't exist:

```
remote: grep: /tmp/build_91bd8e7c/Gemfile.lock: No such file or directory
```

**Comment by schneems** [comment]
It's a bug if the Gemfile.lock doesn't exist. It would be cleaner if it didn't do this, but it's not an active bug.
