### ISSUE TITLE
heroku run rails not working

### ISSUE THREAD

**Issue by conradwt** [heroku/heroku-buildpack-ruby#1130]
Given the command

```
heroku run rails db:migrate
```

I'm getting the Rails standard help documentation:

```
Running rails db:migrate on ⬢ flix-cwt... up, run.7603 (Free)
Usage:
  rails new APP_PATH [options]

Options:
      [--skip-namespace], [--no-skip-namespace]              # Skip namespace (affects only isolated engines)
      [--skip-collision-check], [--no-skip-collision-check]  # Skip collision check
  -r, [--ruby=PATH]                                          # Path to the Ruby binary of your choice
                                                             # Default: /app/vendor/ruby-3.0.0/bin/ruby
...
```

Next, I have the following buildpacks installed:

```
➜ heroku buildpacks          
=== flix-cwt Buildpack URLs
1. heroku/nodejs
2. heroku/ruby
```

Finally, I'm using Rails 6.1.3 and Ruby 3.0.0p0.

**Comment by schneems** [comment]
Please open a Heroku support ticket for this case. The buildpack issues are for development issues with the buildpack itself.

I also recommend using `heroku run bash` along with some linux commands such as `which rails` and `cat` to determine what is executing.

My best guess is that your `bin/rails` is not quite correct and might need to be regenerated, but I wouldn't know for sure.

**Comment by conradwt** [comment]
Hi, I had a .gitignore_global file that was ignoring the top level `bin` directory within my Rails project.  Thus, I was able to resolve this issue by performing a `git add bin -f`.
