### ISSUE TITLE
Review apps unable to use cached bundles

### ISSUE THREAD

**Issue by zeptonaut** [heroku/heroku-buildpack-ruby#1160]
There seems to be some problem where review apps are unable to use cached bundles: every time that a review app spins up, it has to do a full `bundle install` again.

We use `heroku-buildpack-monorepo`, which I do wonder if that's interfering with the correct caching behavior somehow. 

### Comparison of `bundle install` between `master` branch and review apps
**`master` branch build**: 0.74s total
```
-----> Installing dependencies using bundler 2.2.16
       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
       Using rake 13.0.3
       Using concurrent-ruby 1.1.8

       ...
       ... Lots and lots more usings
       ...

       Bundle complete! 68 Gemfile dependencies, 138 gems now installed.
       Gems in the groups 'development' and 'test' were not installed.
       Bundled gems are installed into `./vendor/bundle`
       Removing rack-proxy (0.6.5)
       Removing uglifier (4.2.0)
       Removing execjs (2.7.0)
       Removing semantic_range (3.0.0)
       Removing webpacker (5.4.0)
       Bundle completed (0.74s)
       Cleaning up the bundler cache.
```

**Review app build: 262.80s total**
```
-----> Installing dependencies using bundler 2.2.16
       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
       Fetching gem metadata from https://rubygems.org/...........
       Fetching rake 13.0.3
       Installing rake 13.0.3

       ...
       ... Lots and lots more fetching/install
       ...

       Fetching sass-rails 6.0.0
       Installing sass-rails 6.0.0
       Bundle complete! 68 Gemfile dependencies, 138 gems now installed.
       Gems in the groups 'development' and 'test' were not installed.
       Bundled gems are installed into `./vendor/bundle`
       Post-install message from sentry-raven:
       `sentry-raven` is deprecated! Please migrate to `sentry-ruby`
       
       See https://docs.sentry.io/platforms/ruby/migration for the migration guide.
       
       Bundle completed (262.80s)
       Cleaning up the bundler cache.
```

### Comparison of `yarn install` between `master` branch and review apps
**`master` branch build:**  2.07s total
```
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.22.4
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       Done in 2.07s.
```

**Review app build:**  0.12s total
```
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.22.4
       [1/4] Resolving packages...
       success Already up-to-date.
       Done in 0.12s.
```

### Impact
The impact of this in review app spinup is significant, especially given that review app spinup is often in the critical path of getting a piece of code sent out for review. On `master`, the time from commit to deploy is ~7 minutes. For review apps, the time from commit to spinup is more like ~12 minutes because of this.

### Is this even possible?
It does _seem_ like doing this is possible: somehow, `heroku/nodejs` seems to be able to leverage previously builds to reduce the runtime of `yarn install`, whereas `heroku/ruby` isn't doing the same for cached bundles.

**Comment by zeptonaut** [comment]
Note: it's worth mentioning here that `heroku/nodejs` appears _before_ `heroku-buildpack-monorepo` in our root `app.json`, whereas `heroku/ruby` appears _after_. I'm wondering if that explains why the caching is working better for it.

However, I'm still pretty bamboozled why the cache would work across builds on `master`, but not for new review apps.

**Comment by geoffharcourt** [comment]
We might be doing it wrong, but we didn't see cross-app build caching work until we started using this plugin: https://github.com/commonlit/heroku-buildpack-shared-build-cache (a fork of someone else's work just to prevent it from unexpected modification).

**Comment by schneems** [comment]
Hello. I generally reserve issues for bugs specifically against the buildpack itself. If you're having application-specific issues please open up a support ticket on help.heroku.com so our support staff will have access to your logs, and other debugging tools.

The buildpack doesn't have control or visibility of review apps it puts dependencies in the cache and uses dependencies from the cache regardless of what kind of app is being built. This is likely more of an issue related to review apps.

**Comment by zeptonaut** [comment]
Sounds fair - thanks for taking a look. I suspect that you're right and this is a byproduct of the interplay between `heroku-buildpack-monorepo` and how review apps handle caching, both of which I need to dig into more. I appreciate you taking a look.
