### ISSUE TITLE
OpenSSL 1.1.1k

### ISSUE THREAD

**Issue by vkalach** [heroku/heroku-buildpack-ruby#1166]
Hi guys! I need to use OpenSSL 1.1.1k so I added a buildpack to be able to use it. But after this when ruby buildpack starts I receive an error

      Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/.

       There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.

It doesn't matter which version of OpenSSL I will install and so on. I was trying clear build cache, install newer version of ruby - everytime the same.

The order of buildpacks is:
1. OpenSSL buildpack
2. Freetds buildpack (that's why I need openssl buildpack)
3. Ruby buildpack

Any ideas?

**Comment by schneems** [comment]
We technically don't provide support for any custom buildpacks or their integration. This isn't something that has specifically come up before either. I can ask a few questions and point you in a debugging direction though:

What version of Ruby are you using? How about bundler? Are you able to use OpenSSL 1.1.1k and that version of Ruby/Rubygems https://devcenter.heroku.com/articles/ruby-support#ruby-versions and bundler on docker without the Ruby buildpack?

It seems like the failure is coming from Bundler/Ruby/Rubygems, but it's unclear why. Being able to narrow down the problem and get a smaller reproduction would likely help. Alternatively, there might be an environment variable flag in bundler/ruby/rubygems to get more information when this fails, but I don't know of one off my head.
