### ISSUE TITLE
Bundler < 2.2.18 has "Dependency Confusion in Bundler" vulnerability

### ISSUE THREAD

**Issue by pointcom** [heroku/heroku-buildpack-ruby#1167]
Hi, it looks like the [current bundler version(2.2.16)](https://github.com/heroku/heroku-buildpack-ruby/blob/fe4db44101a9482c09cadd6e5b5ebf112e278f79/lib/language_pack/helpers/bundler_wrapper.rb#L40) used by the Heroku's Ruby Buildpack has ["Dependency Confusion" vulnerability](https://github.com/advisories/GHSA-fp4w-jxhp-m23p).

Here is an extract of the issue from the GitHub advisory database:
>Bundler 1.16.0 through 2.2.9 and 2.2.11 through 2.2.17 sometimes chooses a dependency source based on the highest gem version number, which means that a rogue gem found at a public source may be chosen, even if the intended choice was a private gem that is a dependency of another private gem that is explicitly depended on by the application.

Please let me know if I can help.
Thank you.

**Comment by jchestershopify** [comment]
FWIW, Bundler [2.2.21](https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2221-june-23-2021) includes the ability to upgrade to the new lockfile format without forcing an upgrade of gems.

**Comment by pointcom** [comment]
@jchestershopify Awesome! I just saw your PR which bumps the bundler version to 2.2.21. Thank you.

I guess we now need a review from the Heroku Language team to validate the PR and upload a new "bundler-2.2.21.tgz" file in the heroku ruby buildpack S3 bucket.

**Comment by schneems** [comment]
I've released bundler 2.2.21 on the platform. Sorry this took so long. I was out on vacation and this flew under the radar.
