### ISSUE TITLE
Detect `gems.rb` too.

### ISSUE THREAD

**Issue by ioquatix** [heroku/heroku-buildpack-ruby#1176]
`gems.rb` should be a valid option here.

https://github.com/heroku/heroku-buildpack-ruby/blob/20b1919df498eff6010374b1ca1b91d9f7b56d2a/bin/detect#L14

**Comment by ioquatix** [comment]
It looks like we might also need to update the logic here:

```
grep: /tmp/build_b93d19a1/Gemfile.lock: No such file or directory
-----> Compiling Ruby/NoLockfile
 !
 !     Gemfile.lock required. Please check it in.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by schneems** [comment]
Someone put in a request to support a `BUNDLE_GEMFILE=<path>` env var. I think that would be the more general path forward.

**Comment by ioquatix** [comment]
Maybe you can add that but you should then still auto detect `gems.rb` to match the behaviour of bundler.
