### ISSUE TITLE
Why isn't this buildpack using LTS Node?

### ISSUE THREAD

**Issue by AlecRust** [heroku/heroku-buildpack-ruby#1214]
I see in the Heroku [Node.js buildpack docs](https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version) it says:

> If a Node version isn’t specified in the engine, the `14.x` release will be used.

This is what I would expect, as `14.x` is the LTS at time of writing.

However this Ruby buildpack (which is the only one used in our app) uses Node 12.16.2. **I would have expected both the Ruby and the Node buildpacks to use LTS Node**.

It [looks like](https://devcenter.heroku.com/articles/ruby-support#installed-binaries) I could also load the Node buildpack in order to set a specific Node version, but I don't really want to set a Node version, I'm happy for LTS to be used.

Can this Ruby buildpack be updated to use the current LTS version to match the Node buildpack?

**Comment by AlecRust** [comment]
Just a small bump on this, an ever growing list of npm packages are dropping support for 12.x. A user of this Ruby buildpack would expect to be able to install the latest version of common dependencies like `eslint`, `stylelint` etc.

**Comment by AlecRust** [comment]
Here's a PR: https://github.com/heroku/heroku-buildpack-ruby/pull/1231

**Comment by schneems** [comment]
This is deployed today
