### ISSUE TITLE
Remove sassc after building assets?

### ISSUE THREAD

**Issue by adibsaad** [heroku/heroku-buildpack-ruby#1219]
The sassc gem takes up about 160mb on disk, but it's only needed for the build step (to compile scss-based assets).

It would be great if this buildpack could exclude it from the final slug so we can save space.

Thanks

**Comment by adibsaad** [comment]
@schneems any feedback?
Would be nice if we could specify a list of gems to delete after the build process completes, since some dependencies can't be added to the development/test group because they need to be installed on heroku for the build phase, but aren't needed during runtime.

**Comment by schneems** [comment]
Some people do use on-the-fly asset generation (for better or worse) so I couldn't strip this out for everyone. The path forward would be to find a way to remove it for just you.

There's a `.slugignore` file you can use to remove files that are present on disk at build but not at runtime. That would be my suggested path forward.
