### ISSUE TITLE
Nuke or clean gem `ext` directories

### ISSUE THREAD

**Issue by danp** [heroku/heroku-buildpack-ruby#122]
gems with native extensions in `vendor/bundle` have their `ext` directories left with build artifacts intact. Consider either running `make clean` in each or just removing all `ext` directories.

I am not sure what the contract is for gems around expecting things in their `ext` directories but in limited testing with pg and nokogiri they seem to function fine with `ext` having been completely nuked.

This would potentially save quite a bit of space in the slug.

Example from an app's dyno:

```
$ find . -type d -name ext | xargs du -sh
9.0M    ./ruby/2.0.0/gems/nokogiri-1.5.9/ext
1.2M    ./ruby/2.0.0/gems/yajl-ruby-1.1.0/ext
816K    ./ruby/2.0.0/gems/bcrypt-ruby-3.0.1/ext
1.4M    ./ruby/2.0.0/gems/pg-0.14.1/ext
1.8M    ./ruby/2.0.0/gems/puma-2.0.1/ext
```

**Comment by schneems** [comment]
We should look into this

**Comment by dpiddy** [comment]
Unfortunately some gems rely on things in `ext` at runtime, I think oj is one. :cry:

**Comment by dpiddy** [comment]
oj example [here](https://github.com/ohler55/oj/blob/7cc1f71e38f9bd669cc33faecf97f6f1c4982026/oj.gemspec#L20). I consider this a bug in the way gems work. What is used at runtime should be (forcefully) completely separate from build stuff.
