### ISSUE TITLE
Avoid deployments issues caused by bundler with git sources using globs

### ISSUE THREAD

**Issue by Quiwin** [heroku/heroku-buildpack-ruby#1225]
Hello,

The current bundler version has an [issue](https://github.com/rubygems/rubygems/issues/4943) linked to the generation of Gemfile.lock with multiple git sources on the same repository, differentiated by their glob: their order generated in the Gemfile.lock is non-deterministic and differ between operating systems.

<details>

<summary> This difference causes the deployment on a dyno to fail </summary>

```
Installing dependencies using bundler 2.2.21        
remote:        Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4        
remote:        You are trying to install in deployment mode after changing        
remote:        your Gemfile. Run `bundle install` elsewhere and add the        
remote:        updated Gemfile.lock to version control.        
remote:                
remote:        If this is a development machine, remove the /tmp/build_349b20f0/Gemfile freeze         
remote:        by running ``.        
remote:                
remote:        The list of sources changed        
remote:        Bundler Output: You are trying to install in deployment mode after changing        
remote:        your Gemfile. Run `bundle install` elsewhere and add the        
remote:        updated Gemfile.lock to version control.        
remote:                
remote:        If this is a development machine, remove the /tmp/build_349b20f0/Gemfile freeze         
remote:        by running ``.        
remote:                
remote:        The list of sources changed        
remote:         
remote:  !        
remote:  !     Failed to install gems via Bundler.        
remote:  !        
remote:  !     Push rejected, failed to compile Multipack app.        
remote: 
remote:  !     Push failed  
```

</details>

This is fixed in [v2.2.29](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.2.29) by https://github.com/rubygems/rubygems/pull/4947

As the heroku buildpack still uses a bundler version that precedes the version with this fix, we are having problems deploying properly to our production dynos. Could it be possible to bump the bundler version used to solve this problem?

**Comment by schneems** [comment]
This is now released https://devcenter.heroku.com/changelog-items/2312 sorry for the wait

**Comment by Quiwin** [comment]
Thanks!
