### ISSUE TITLE
Rails 4 Asset Caching Doesn't Clean Old Assets

### ISSUE THREAD

**Issue by hone** [heroku/heroku-buildpack-ruby#123]
Since we started caching assets in Rails 4. There's an issue that old assets aren't getting cleared. We need some way of cleaning up old assets that aren't being used anymore.

Update: To clarify, the issue is that there are old assets that are deleted that still linger.

**Comment by chibicode** [comment]
sprocket-rails has the mentioned fix in 2.1.4:
https://github.com/rails/sprockets-rails/blob/master/CHANGELOG.md#214
https://github.com/rails/sprockets-rails/pull/140

**Comment by paulleader** [comment]
Thanks for the fix. I had a similar issue that was making me tear my hair out, the heroku-repo tool fixed it :)

**Comment by dwbutler** [comment]
Our apps are running sprockets-rails 2.3.1. We are seeing this issue in some environments and not others. Not clear why. Is there some configuration that we're missing?

**Comment by yanhackcode15** [comment]
I was experiencing similar issue where heroku was serving the old js file 10 commits ago. After precompiling the assets locally then push to heroku finally fixed it.
