### ISSUE TITLE
rails: not found, bundle: not found

### ISSUE THREAD

**Issue by collimarco** [heroku/heroku-buildpack-ruby#1233]
I built an image on a simple/new Rails app (v6.1.4) using:

```
pack build example:abc --builder heroku/buildpacks:20
```

If I run the image and I execute `rails` inside it (or rails server, rails console, etc.) I get:

```
$ rails
sh: 2: rails: not found
$ bundle
sh: 3: bundle: not found
```

Same for `bundle` command...

The Rails app files are present in the image and this is the PATH:

```
$ echo $PATH
/cnb/process:/cnb/lifecycle:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

What is going on?

**Comment by schneems** [comment]
Make sure that you're executing with the correct entrypoint when you
`docker run` for example
https://github.com/heroku/cutlass/blob/da085f6c04f7f3d06ac6641e81f919c263ffcdaa/lib/cutlass/app.rb#L80

**Comment by collimarco** [comment]
@schneems Thank you very much! 

It seems that the issue was caused by that... **If I prefix every Kubernetes command with `/cnb/lifecycle/launcher`, everything works as expected!** Is that the correct approach?

Do you know if this behavior is general to all Cloud Native Buildpacks or it is only for Heroku? If it's the first case, probably they should update the docs on buildpacks.io, because I can't find this important piece of infrmation

**Comment by schneems** [comment]
> Is that the correct approach?

I think the right approach is to specify the entrypoint flag instead of prefixing. 

> Do you know if this behavior is general to all Cloud Native Buildpacks or it is only for Heroku? If it's the first case, probably they should update the docs on buildpacks.io, because I can't find this important piece of information

It's all cloud native buildpacks. They would probably love a documentation PR. I agree it's confusing. You can @ me if you want to work on that. I think it would be a win.
