### ISSUE TITLE
Slug size increasing after ruby 3.1.0

### ISSUE THREAD

**Issue by cirdes** [heroku/heroku-buildpack-ruby#1271]
My app with ruby 3.0.3 has a slug of 286.2M. When I tried to update to Ruby 3.1.0 it jumped to 489.2M, very close to Heroku`s hard limit. 

The only diference between deploys are the Ruby versions.

**Comment by schneems** [comment]
I recommend using `du` in a `heroku run bash` session to figure out what changed on disk https://help.heroku.com/KUFMEES1/my-slug-size-is-too-large-how-can-i-make-it-smaller

You can also try re-deploying your app using the old Ruby version to a new heroku app then you can compare the `du` contents.

I've not received any other reports about similar issues so this is likely isolated to behavior in your app and how it interacts with the build system.

**Comment by cirdes** [comment]
@schneems, thanks for pointing out how to dig this problem. There is an issue on Google GRPC https://github.com/grpc/grpc/issues/28627 that is causing slug size to increase.
