### ISSUE TITLE
Cannot deploy anymore after changing ruby default version from 2.7.5 to 3.0.3

### ISSUE THREAD

**Issue by antonioabrf** [heroku/heroku-buildpack-ruby#1282]
_BUILDPACK_URL='https://github.com/heroku/heroku-buildpack-ruby.git'_
When trying deploy an app:
```
       -----> Cleaning up...
       -----> Building telesapp from herokuish...
       -----> Adding BUILD_ENV to build environment...
       -----> Fetching custom buildpack
       -----> Ruby app detected
       Failed to download a Ruby executable for bootstrapping!
       
       This is most likely a temporary internal error. If the problem
       persists, make sure that you are not running a custom or forked
       version of the Heroku Ruby buildpack which may need updating.
       
       url: https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-3.0.3.tgz
       remote: /tmp/buildpacks/custom/bin/compile: line 31: /tmp/tmp.RTxrycjPNh/bin/ruby: No such file or directory
```
I've tried access directly via curl https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-3.0.3.tgz just for checking and the return was:

       <?xml version="1.0" encoding="UTF-8"?>
       <Error><Code>AccessDenied</Code><Message>Access Denied</Message>                                                        
       <RequestId>73BMYQEVPT2T9NHK</RequestId>       
       <HostId>HH+RIcvGKNk9/JmzOXOW8ml2CQk9lBgo5yV4a2TDQCLdhBZMIrFJ+yhhGqizfwxRNPPRtvvY36M=</HostId>       
       </Error>

**Comment by dentarg** [comment]
See https://github.com/heroku/heroku-buildpack-ruby/issues/1279#issuecomment-1057239601

**Comment by schneems** [comment]
Thanks @dentarg. Exact same thing. This is expected. See my response on that link for more info.
