### ISSUE TITLE
Missing documentation on how to use with pack CLI

### ISSUE THREAD

**Issue by hidde-jan** [heroku/heroku-buildpack-ruby#1293]
The last version of this buildpack that was officially published is version 0.1.3, from October 2021. Updates of this buildpack have not been published since then.

Currently, there is no documentation on how up to date versions of this buildpack can be used using the pack CLI.

Specifying the GitHub .git url doesn't work:

```bash
pack build api-heroku-test --builder heroku/buildpacks:20 --buildpack https://github.com/heroku/heroku-buildpack-ruby.git
```

Is the only option to build the buildpack locally?

**Comment by edmorley** [comment]
As of heroku/builder/pull/282 the `heroku/buildpacks:{18,20}` images now contain a shimmed version of the latest stable classic Ruby buildpack release, so can be used with `pack build` without the need to specify custom buildpacks.

There is also a Heroku-22 version of those images (that's been available for a few months), at the new image name of `heroku/builder-classic:22`.

Eventually when Ruby has a native CNB (non-shimmed) it will be available in the `heroku/builder:22` builder image. Development for the native Ruby CNB is occurring here (notably on the separt:
https://github.com/heroku/buildpacks-ruby/tree/schneems/fresh-start-rust

More on the differences between the different builder images can be seen here:
https://github.com/heroku/builder#heroku-builder-images
