### ISSUE TITLE
Issue with Bundler 2.3.10

### ISSUE THREAD

**Issue by kvnlin** [heroku/heroku-buildpack-ruby#1299]
With the recent upgrade to v240 of the buildpack, we're starting to see this issue with using v2.3.10 of bundler. Is this something others are seeing as well?

```
----->` Build succeeded!
-----> Ruby app detected
-----> Installing bundler 2.3.10
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.7.4
-----> Installing dependencies using bundler 2.3.10
```

Then proceeds to fail with the following exception:
```
       NoMethodError: undefined method `satisfied_by?' for nil:NilClass
```

**Comment by kvnlin** [comment]
Bundling with 2.3.10 locally and committing the update Gemfile.lock solved this

**Comment by dentarg** [comment]
Looks like you ran into a bug with Bundler/RubyGems? I found https://github.com/rubygems/rubygems/issues/5446 + https://github.com/rubygems/rubygems/pull/5447
