### ISSUE TITLE
Old version of the buildpack still used if the buildpack is called via the CNB Shim

### ISSUE THREAD

**Issue by aldent95** [heroku/heroku-buildpack-ruby#1302]
The nodejs version update that was applied in #1231 doesn't seem to be applying when the buildpack is used via the Cloud Native Buildpacks shim.

I've got Rails apps deploying via GitLab AutoDevOps and it uses CNB with the Heroku 20 stack (Building Cloud Native Buildpack-based application with builder heroku/buildpacks:20). 
I've tried everything I can think of to get it to pull v231 or higher, but it doesn't seem to want to.

Looking at the change log in here, this buildpack should support heroku-22 now, but the version in the CNB registry doesn't reflect that.
https://registry.buildpacks.io/buildpacks/heroku/ruby

Is there any chance that could be updated, or is there something I can do that I might have missed to force the latest version?

**Comment by edmorley** [comment]
@aldent95 Hi! The Ruby buildpack in `heroku/buildpacks:20` hasn't been updated for some time, as it's not using CNB shim but a different approach. There are plans to resolve that, however in the meantime you can use the up to date CNB shim version of the Ruby buildpack via the new `heroku/builder-classic:22`:
https://github.com/heroku/builder#heroku-builder-images

**Comment by aldent95** [comment]
> @aldent95 Hi! The Ruby buildpack in `heroku/buildpacks:20` hasn't been updated for some time, as it's not using CNB shim but a different approach. There are plans to resolve that, however in the meantime you can use the up to date CNB shim version of the Ruby buildpack via the new `heroku/builder-classic:22`: https://github.com/heroku/builder#heroku-builder-images

Tried ```heroku/builder-classic:22``` and ```heroku/builder:22``` and neither work.

builder-classic fails trying to download bundler 2.3.10 from https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/bundler/bundler-2.3.10.tgz 
builder fails when trying to install yarn 
```
[builder] node[79]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed
```

**Comment by aldent95** [comment]
Ok ```heroku/builder:22``` once I made sure my docker version was set to the latest version Gitlab use for Auto Devops.

And for anyone else who might come acorss this, set the Gitlab CI/CD vairable of ```AUTO_DEVOPS_BUILD_IMAGE_CNB_BUILDER``` to the value of ```heroku/builder:22``` (Or whatever version you want) to get it to work.

**Comment by edmorley** [comment]
Yeah older Docker doesn't work well with Ubuntu 22.04 images (and thus Heroku-22 stack based images).

The reason `heroku/builder:22` didn't work (and the reason why I said to use `heroku/builder-classic:22`), is that that image only contains native CNBs, which only exist for Java and Node.js so far (this list will increase over time). 

In contrast, `heroku/builder-classic:22` contains all the supported Heroku languages, since it uses a shim to wrap the classic Heroku buildpacks to make them compatible with the new Cloud Native Buiildpack spec.

The README of the builder repo explains more:
https://github.com/heroku/builder/blob/main/README.md

**Comment by aldent95** [comment]
Ok, that explains why I'm getting errors on deploy with ```heroku/builder:22``` when I deploy if it doesn't have Ruby at all.

Guess I need to figure out how to upgrade to Ruby 3.1 then with gems that don't currently support it....
