### ISSUE TITLE
RACK_ENV and RAILS_ENV values are frozen at compile time. How?

### ISSUE THREAD

**Issue by Taytay** [heroku/heroku-buildpack-ruby#1305]
We use Heroku presently, and are experimenting with Cloud Native Buildpacks using this buildpack (well actually using this indirectly through `heroku/buildpacks:20`).
It seems to work, but I am particularly confused about one thing:
Whatever values RACK_ENV and RAILS_ENV have at the time of building the container are the values that the container will have when the server is actually launched. It doesn't matter if I give new values for RACK_ENV and RAILS_ENV at the time I launch the container - they are guaranteed to get overwritten with whatever values they had at pack/build time. I've looked in all sorts of places in the container and this codebase to see where these values are getting frozen and overwritten at runtime, but I don't see it. At this point, I am beginning to suspect that it's happening inside of something like `/cnb/process/web`, but that feels overly complicated to me. If you have any advice on where to look to see this, I'd greatly appreciate it, as it would help with our documentation. 

This is admitedly low priority, but to answer the "But why are you doing this?":
For local testing I am trying to see if a packaged container can be tested locally running in development mode, even if it was packaged with RACK_ENV and RAILS_ENV set to "production".

**Comment by schneems** [comment]
We set `RACK_ENV` and `RAILS_ENV` to defaults, you should be able to overwrite them with `heroku config:set RAILS_ENV=<value>` though I caution against changing them away from production
