### ISSUE TITLE
Amazon S3 is extremely slow

### ISSUE THREAD

**Issue by itsNikolay** [heroku/heroku-buildpack-ruby#1306]
Download speed from Amazon S3 is 8KB/s:
(I checked it on 2 different internet providers and both have the same 8Kb/s)
```ruby
$ wget https://s3.amazonaws.com/heroku-nodebin/node/release/linux-x64/node-v16.13.1-linux-x64.tar.gz
--2022-05-25 23:13:04--  https://s3.amazonaws.com/heroku-nodebin/node/release/linux-x64/node-v16.13.1-linux-x64.tar.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.201.200
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.201.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 32395116 (31M) [application/x-tar]
Saving to: ‘node-v16.13.1-linux-x64.tar.gz’

node-v16.13.1-linux-x64.tar.gz               1%[=>    ] 355.64K  7.39KB/s    eta 91m 36s
```
Should we add way to change Node URL  to bypass such case? 
Probably from ENV var? 
It's hardcoded now :(  https://github.com/heroku/heroku-buildpack-ruby/blob/main/lib/language_pack/helpers/nodebin.rb#L8
Or probably you can suggest another way ?

**Comment by schneems** [comment]
It's possible to specify a different bucket for binaries via an env var (when running the buildpack, not at the app level). But it's not really a common use case. Heroku runs on AWS and uses an S3 bucket in the same data center as our builds. We don't really have much support for off-heroku installations right now. 91m is quite a long time though. That seems unusually high.
