### ISSUE TITLE
Correct Ruby version isn't used when Gemfile contains a range

### ISSUE THREAD

**Issue by alexgleason** [heroku/heroku-buildpack-ruby#1320]
I have `.ruby-version` with:

```
3.0.4
```

I have a `Gemfile` which contains a range:

```Gemfile
ruby '>= 2.6.0', '< 3.1.0'
```

(`Gemfile.lock` does not contain a ruby version)

When I try to push my repo, it fails:

```
-----> Compiling Ruby/Rails
       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 90 --max-time 600 https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-20/ruby-2.6.0.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.
       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 90 --max-time 600 https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-20/ruby-2.6.0.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3.
       
       !
       !     The Ruby version you are trying to install does not exist on this stack.
       !
       !     You are trying to install ruby-2.6.0 on heroku-20.
       !
       !     Ruby ruby-2.6.0 is present on the following stacks:
       !
       !     - heroku-18
       !
       !     Heroku recommends you use the latest supported Ruby version listed here:
       !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
       !
       !     For more information on syntax for declaring a Ruby version see:
       !     https://devcenter.heroku.com/articles/ruby-versions
       !
remote:  !     Failure during app build
remote:  !     Removing invalid image tag dokku/hello:latest
remote:  !     App build failed
```

Specifying a range [is supported](https://bundler.io/guides/gemfile_ruby.html).

It should be possible to override the Ruby version used by this buildpack (probably with `.ruby-version`), and even better if it could understand ranges.

**Comment by schneems** [comment]
The message says that 2.6.0 does not exist on heroku-20 but is on heroku-18 and is not related to how we resolve the version.

We get the version from `bundle platform --ruby` when you run that it must output a supported Ruby version in our documentation https://devcenter.heroku.com/articles/ruby-support. If you want to lock to 3.0.4 then I recommend running `bundle update --ruby` and committing the version to git.

If your app is failing, you'll need to open a support ticket so I can help to debug it.
