### ISSUE TITLE
Build failed: rake assets:precompile raises ActiveSupport::EncryptedFile::MissingKeyError

### ISSUE THREAD

**Issue by collimarco** [heroku/heroku-buildpack-ruby#1327]
I am using the following command to build a Rails application (Rails 7.0.4, Ruby 3.1.2):

```
pack build mytag --builder heroku/buildpacks:20 --publish
```

fails with:

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       ActiveSupport::EncryptedFile::MissingKeyError: Missing encryption key to decrypt file with. Ask your team for your master key and write it to /workspace/config/credentials/production.key or put it in the ENV['RAILS_MASTER_KEY'].
       /workspace/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/encrypted_file.rb:122:in `handle_missing_key'
```

Obviously the master key is not available during the build, because it is present only in the production environment. Also it's not necessary to have it for building the assets. 

Any solution?

Note: I am using "heroku/buildpacks:20" because "heroku/buildpacks:22" does not exist [here](https://hub.docker.com/r/heroku/buildpacks)...

**Comment by schneems** [comment]
Sorry I missed this issue when it came in. If you have application-specific issues please open a support ticket with Heroku so I can look at your reproduction.
