### ISSUE TITLE
Build failed:  Sprockets::FileNotFound: couldn't find file

### ISSUE THREAD

**Issue by collimarco** [heroku/heroku-buildpack-ruby#1328]
I get this error while building a Rails 7 application (that was upgraded from previous rails versions):

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       Sprockets::FileNotFound: couldn't find file 'emojionearea/dist/emojionearea' with type 'text/css'
```

The problem is that you should run `rake yarn:install` BEFORE `rake assets:precompile`... otherwise some assets are not present.

Can you fix this?

Note: I am using "heroku/buildpacks:20" because "heroku/buildpacks:22" does not exist [here](https://hub.docker.com/r/heroku/buildpacks)...

**Comment by schneems** [comment]
We only run the `rake assets:precompile` we don't run `rake yarn:install`. If you need that it's up to you to hook into the rake tasks chain. That's how gems like `webpacker` work, they enhance the rake task.
