### ISSUE TITLE
Bug: Ruby EOL warning message is misleading

### ISSUE THREAD

**Issue by latortuga** [heroku/heroku-buildpack-ruby#1346]
The [current Ruby EOL warning message](https://github.com/heroku/heroku-buildpack-ruby/blob/main/lib/language_pack/ruby.rb#L471-L472) suggests that Ruby 2.7 will reach EOL on December 25th. This is not true and has not been true for any previous version of Ruby. New versions of Ruby are released on December 25th but prior "security maintenance only" releases are not EOL'd until [several months later](https://www.ruby-lang.org/en/downloads/branches/). I don't know what to change it to but the current message is misleading.

**Comment by schneems** [comment]
The path forward is to track this state within the buildpack instead of relying on S3 presence check. I would say that functionally it's EOL, if not technically. People shouldn't be using 2.7 past Christmas, other than to be working towards getting off of it...and that's cutting it close.
