### ISSUE TITLE
RuntimeError: failed to get urandom

### ISSUE THREAD

**Issue by dblock** [heroku/heroku-buildpack-ruby#1347]
Ruby 3.1.2p20 introduced `RuntimeError: failed to get urandom` error on heroku-buildpack-ruby. This happens with the latest buildpack (v248), which completely bricks all git push(es), or by pushing a Ruby 3.1.2 app to an older buildpack version.

Interestingly, installing rvm and Ruby 3.1.2 works just fine on the same box. 

These are old versions, but upgrading kernel/docker/etc. isn't currently an option.

```
       Old: ruby 2.7.7p221 (2022-11-24 revision 168ec2b1e5) [x86_64-linux]
       New: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
-----> Installing dependencies using bundler 2.2.33
       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
--- ERROR REPORT TEMPLATE -------------------------------------------------------
       
       ```
       RuntimeError: failed to get urandom
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/securerandom.rb:75:in `urandom'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/securerandom.rb:75:in `singleton class'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/securerandom.rb:42:in `<module:SecureRandom>'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/securerandom.rb:41:in `<top (required)>'
       <internal:/tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
       <internal:/tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/bundler/fetcher.rb:5:in `<top (required)>'
       <internal:/tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
       <internal:/tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli/install.rb:50:in `run'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:255:in `block in install'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:254:in `install'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
       /tmp/build/vendor/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
       /tmp/build/vendor/bundle/ruby/3.1.0/bin/bundle:23:in `load'
       /tmp/build/vendor/bundle/ruby/3.1.0/bin/bundle:23:in `<main>'
       ```
       
       ## Environment
       
       ```
       Bundler       2.3.7
       Platforms   ruby, x86_64-linux
       Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-linux]
       Full Path   /tmp/build/vendor/ruby-3.1.2/bin/ruby
       Config Dir  /app/vendor/ruby-3.1.2/etc
       RubyGems      3.3.7
       Gem Home    /tmp/build/vendor/bundle/ruby/3.1.0
       Gem Path    /tmp/build/vendor/bundle/ruby/3.1.0
       User Home   /app
       User Path   /app/.local/share/gem/ruby/3.1.0
       Bin Dir     /tmp/build/vendor/bundle/ruby/3.1.0/bin
       OpenSSL
       Compiled    OpenSSL 1.1.0g  2 Nov 2017
       Loaded      OpenSSL 1.1.1  11 Sep 2018
       Cert File   /usr/lib/ssl/cert.pem
       Cert Dir    /usr/lib/ssl/certs
       Tools
       Git         2.17.1
       RVM         not installed
       rbenv       not installed
       chruby      not installed
```

```
uname -a
Linux dblock-plum 3.13.0-71-generic #114~precise1-Ubuntu SMP Tue Dec 1 19:37:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by schneems** [comment]
Sorry I didn't see this come in. I hope you found a workaround here. If you're having an application specific issue please open a support ticket so I can take a look at your exact code (and reproduce the issue much easier).
