### ISSUE TITLE
running ruby 3.2 with yjit

### ISSUE THREAD

**Issue by aka47** [heroku/heroku-buildpack-ruby#1362]
As a great major feature ruby has a new jit compiler to speed up ruby apps in production ..  https://github.com/Shopify/yjit

How can we enable yjit within the heroku buildpack? I have not found any information on how to do this within heroku. Something along the lines of ... 

`export RUBY_CONFIGURE_OPTS=--enable-yjit`

Any idea on how to get yjit working within heroku?

**Comment by schneems** [comment]
> Any idea on how to get yjit working within heroku?

It works out of the box, just like any other Ruby environment. Yjit is compiled with Rusty for Ruby 3.2. The Heroku way to se this would be via `heroku config:set` you can use this env var:

```
$ RUBY_YJIT_ENABLE=1 ruby -e "puts RubyVM::YJIT.runtime_stats"
{:inline_code_size=>81983, :outlined_code_size=>63742}
```

```
$ heroku config:set RUBY_YJIT_ENABLE=1
```
