### ISSUE TITLE
Difficulties getting `rake assets:precompile` to work

### ISSUE THREAD

**Issue by JonRowe** [heroku/heroku-buildpack-ruby#1376]
👋  Just setting up a new app (Rails 7 with propshaft and esbuild) and ran into difficulties with the `rake assets:precompile` step of the build...

Presumedly deliberately, there is no npm so you can't install packages to run the command, nor use `npm run <command>`. (This was altered from the boileplate yarn but I assume that would have the same issue...)

Fixing this by adding the nodejs buildpack, then removing and re-adding the ruby buildpack so it ran after nodejs caused `npm run build` to be used which was rather confusing for someone not used to running nodejs apps, further compounded by the fact the generated boilerplate has `--watch` (a.k.a the dev build step) for this command so it gets stuck.

I'm opening this issue because I feel either:

1) npm/yarn should be available at this step for the purpose of precompiling assets without the nodejs buildpack

2) this buildpack documentation / asset pipeline documentation / the failure output should indicate you need to add nodejs in a specific order and highlight the caveats around that more easily

**Comment by schneems** [comment]
Sorry for the delay here. For application support, I recommend opening a support ticket and then it will get routed to me. I don't always see all issues that come in.

We install a version of node and yarn if the app needs it (https://github.com/heroku/heroku-buildpack-ruby/blob/9d5d8c4732b6962e12981f5948ca72d7b40dca0a/lib/language_pack/ruby.rb#L1016-L1024), so I'm not sure why that wasn't working for you. For more specific debugging I would need an application to look at.
