### ISSUE TITLE
JRuby 9.4.2.0 support?

### ISSUE THREAD

**Issue by greghuc** [heroku/heroku-buildpack-ruby#1378]
Hi @schneems 

Any chance of Heroku JRuby 9.4.2.0 support?
It's been out since March 8.

Many thanks!

Greg

**Comment by greghuc** [comment]
I forgot to say - JRuby 9.4.1.0 is definitely buggy, whilst 9.4.2.0 less so.

I've an app whose tests pass on 9.3.10.0, blow up on 9.4.1.0, and pass again on 9.4.2.0

**Comment by greghuc** [comment]
JRuby 9.4.3.0 has been released: https://github.com/jruby/jruby/releases/tag/9.4.3.0. Would be great to have this on Heroku

**Comment by schneems** [comment]
Sorry for the delay. They've been released:

- https://devcenter.heroku.com/changelog-items/2655
- https://devcenter.heroku.com/changelog-items/2656

**Comment by greghuc** [comment]
Many thanks - just deployed 9.4.2.0!
