### ISSUE TITLE
Upgrade to Node 18 LTS

### ISSUE THREAD

**Issue by swrobel** [heroku/heroku-buildpack-ruby#1384]
Node 16 LTS is still the default, and it's [EOL](https://nodejs.dev/en/about/releases/). Is the plan to move to Node 18 LTS?

**Comment by schneems** [comment]
We leapfrogged. We're now at 20. Sorry it took so long. Also FWIW we changed the official guidance to recommend using both the `heroku/nodejs` and `heroku/ruby` buildpacks to have the most stable experience (i.e. no longer relying on the default version vendored with the Ruby buildpack).
