### ISSUE TITLE
Using ruby 3.3.0 for preview release (as suggested in the notes) raises error with bundler

### ISSUE THREAD

**Issue by everton** [heroku/heroku-buildpack-ruby#1387]
In the notes for the support of ruby-3.3.0-preview1 (refs #1380), it says:

> add the following `ruby` directive to your Gemfile:

```ruby
ruby "3.3.0"
```

But if I do this and set my Ruby (locally) to 3.3.0-preview1 (for example, using .ruby-version file), bundler raises the error:

```
Your Ruby version is 3.3.0.preview1, but your Gemfile specified 3.3.0
```

The only proper way (I have found) to indicate to Bundler to use the preview1 release is to say:

```
ruby '3.3.0preview1'
```

(yes, without the "-"), but this is not deployable on Heroku, it raises the error:

```
The Ruby version you are trying to install does not exist: ruby-3.3.0.preview
```

Obs.: this "." is something bundler invented; I never put it there in any way. I tried using the `patchlevel` parameter, but it also didn't work.

**Comment by schneems** [comment]
Sorry about that. I had to do some engineering to get it to work:

- https://github.com/heroku/docker-heroku-ruby-builder/pull/34

It should be fixed now with preview2. Try this out https://devcenter.heroku.com/changelog-items/2695. If you have problems with Ruby 3.3.0-preview2  please open a support ticket

**Comment by everton** [comment]
Thank you, @schneems. I just tested it and can confirm it is working now, using the format `ruby "3.3.0.preview2"`.
