### ISSUE TITLE
Bundler 2.5.6 Causes Builds to Fail 

### ISSUE THREAD

**Issue by OlekKovalevych** [heroku/heroku-buildpack-ruby#1430]
build pack version https://github.com/heroku/heroku-buildpack-ruby/tree/main/changelogs/v267
ruby version: 2.7.2p137

```
 Building on the Heroku-20 stack
remote: -----> Using buildpacks:
remote:        1. heroku/ruby
remote:        2. heroku/nodejs
remote: -----> Ruby app detected
remote: -----> Installing bundler 2.4.22
remote: -----> Removing BUNDLED WITH version in the Gemfile.lock
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.7.2
remote: -----> Installing dependencies using bundler 2.4.22
remote:        Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
```
exception: 
```
remote:        Fetching gem metadata from https://rubygems.org/.........
remote:        bundler-2.5.6 requires ruby version >= 3.0.0, which is incompatible with the
remote:        current version, 2.7.2
remote:        Bundler Output: Fetching gem metadata from https://rubygems.org/.........
remote:        bundler-2.5.6 requires ruby version >= 3.0.0, which is incompatible with the
remote:        current version, 2.7.2
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
```
bundler versions on heroku: 
![image](https://github.com/heroku/heroku-buildpack-ruby/assets/105041262/32549f23-17a3-4ac7-a538-d0edd9e2fdd9)

**Comment by joshreeves** [comment]
Having the same (or similar) issues with v267 build pack. We had to lock our apps to version 266 to be able to deploy.

**Comment by OlekKovalevych** [comment]
After switching the version to 266, the problem still persists
![image](https://github.com/heroku/heroku-buildpack-ruby/assets/105041262/101a2bba-3445-4c19-b799-0ecba601c10d)
exception: 
![image](https://github.com/heroku/heroku-buildpack-ruby/assets/105041262/a81e90d1-45b9-4544-9ab6-b43835efd5a5)

**Comment by edmorley** [comment]
@schneems ^

**Comment by Swastik-T** [comment]
@OlekKovalevych Did you find any solution to this?

**Comment by OlekKovalevych** [comment]
@Swastik-T IMO, at the moment there is only one possible solution - to update version of ruby. But I prefer to stay with my current version of ruby(2.7.2).

**Comment by supra-man** [comment]
@OlekKovalevych @Swastik-T @joshreeves 
I was able to fix this issue by clearing heroku app cache
`heroku plugins:install heroku-repo`
`heroku repo:purge_cache -a your-app-name`

**Comment by Swastik-T** [comment]
@supra-man Thanks, man. It worked for me. They should put this in their [article](https://devcenter.heroku.com/articles/bundler-version#known-upgrade-issuesHeroku).

**Comment by OlekKovalevych** [comment]
@supra-man Thank you a lot! Clearing the cache for me.( also worked for v267 ruby buildpack)

**Comment by latortuga** [comment]
[This fix](https://github.com/heroku/heroku-buildpack-ruby/issues/1430#issuecomment-1972974741) should be included in the changelog because it seems like the changes in #1428 caused this.
