### ISSUE TITLE
Support Ruby 3.1.6 and 3.3.2

### ISSUE THREAD

**Issue by wrburgess** [heroku/heroku-buildpack-ruby#1459]
https://www.ruby-lang.org/en/news/2024/05/30/ruby-3-3-2-released/

**Comment by wrburgess** [comment]
https://www.ruby-lang.org/en/news/2024/05/29/ruby-3-1-6-released/

**Comment by Roguelazer** [comment]
It looks like #1454 might've done this

**Comment by schneems** [comment]
3.3.2, 3.1.6 and 3.3.3 are released.  3.1.6 is the new default

Sorry for the slow response
