### ISSUE TITLE
Add Support for Ruby 3.2.6

### ISSUE THREAD

**Issue by kwent** [heroku/heroku-buildpack-ruby#1502]
## Add Support for Ruby 3.2.6

https://www.ruby-lang.org/en/news/2024/10/30/ruby-3-2-6-released/

**Comment by dgollahon** [comment]
I think you meant 3.2.6 (was going to open a similar issue).

**Comment by schneems** [comment]
Released https://devcenter.heroku.com/changelog-items/3049
