### ISSUE TITLE
"stty: stdin isn't a terminal" warning and broken standard I/O when using JRuby

### ISSUE THREAD

**Issue by simonask** [heroku/heroku-buildpack-ruby#178]
I'm not sure if this is the correct place for this report — if not, I apologise in advance.

I have a JRuby+Puma app running on Heroku, and the app itself seems to run smoothly, but `heroku run bash` and my custom console script seem to break.

During initialization, I get the following warning:

    stty: stdin isn't a terminal

After that, all standard input/output is broken in a weird way that could suggest a blocking/non-blocking pipe mismatch or similar. Output from the server is only printed locally when "Enter" is pressed multiple times, and it is hard to tell when user input to the server reaches it, due to the lack of visual feedback. Eventually it gets there, but in a less than useful state.

I am using JRuby 1.7.6 in Ruby 1.9.3 mode.

My console script sets `STDOUT.sync = true`, but it has no effect (and the problem exists with bash as well). Using either IRB or Pry makes no difference.

My other Ruby apps that aren't using JRuby seem to work fine without any custom configuration.

**Comment by schneems** [comment]
I verified and i'm able to run this fine on my machine. without the warning using MRI. You shouldn't be using the `heroku` gem for heroku commands. Please run `gem uninstall heroku` and then verify you have a heroku binary installed via the toolbelt:

```term
$ which heroku
/usr/local/bin/heroku
```

This wasn't a buildpack problem. If you're having technical issues please open a ticket on help.heroku.com
