### ISSUE TITLE
Update build process now that Vulcan is "Deprecated"

### ISSUE THREAD

**Issue by a-warner** [heroku/heroku-buildpack-ruby#185]
It seems like this is something you probably know about, but I couldn't find an issue for it so I figured I'd create one.  It looks like Vulcan has been deprecated (per https://github.com/heroku/vulcan/commit/0f2b8ee8feffbdaaec2a1685400bb6a91f4dc026) in favor of `heroku run`.

Is there a new recommended way to build dependencies?  It seems like from @schneems's comment on https://github.com/heroku/heroku-buildpack-ruby/pull/73 that [Anvil](https://github.com/heroku/anvil) is now the recommended build too, but the Rake tasks in this buildpack still shell out to vulcan.

**Comment by schneems** [comment]
We use "hatchet" now.
