### ISSUE TITLE
Env vars not available during the bundler cache cleaning step

### ISSUE THREAD

**Issue by 10io** [heroku/heroku-buildpack-ruby#321]
I have a Rails app, which is using a private github repo as a gem dependency. 
I'm using an OAuth token so that bundler can read the repo.
Since I don't want to store the token directly in the `Gemfile`, I'm using a environment variable to store it.

In other words, in my `Gemfile`, I have a private repo:
```ruby
gem 'foobar', :git => "https://#{ENV['GITHUB_TOKEN']}:x-oauth-basic@github.com/foo/foobar.git", :branch => 'master', :tag => '1.0'
```

The `GITHUB_TOKEN` env var is correctly set in the application (I can see it with `heroku config`).

Now, if I deploy this application, I have the following log (let's say that `GITHUB_TOKEN` is set to `OAUTH_TOKEN`):
```shell
-----> Installing dependencies using 1.6.3
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       ...
       Using foobar 1.0 from https://OAUTH_TOKEN:x-oauth-basic@github.com/foo/foobar.git (at master)
       ...
       Your bundle is complete!
       Cleaning up the bundler cache.
       The git source https://:x-oauth-basic@github.com/foo/foobar.git
       is not yet checked out. Please run `bundle install` before trying to start your
       application
-----> Preparing app for Rails asset pipeline
```

As we can see, the dependencies installation goes well. There is no issue with the private repo. The application is correctly deployed and runs as expected.
This issue here is that the bundler cache cleaning step is skipped. It seems that environment variables are not available during this task. Skipping this step doesn't seem to be good: we will accumulate unused gems and gem version over time. I'm not sure if this cache is counting against the slug size limit (300MB).

Note that when we had the `user-env-compile` feature, the bundler cache cleaning step went smoothly.

My questions are:
* Is this expected?
* If it is, is there a workaround?

**Comment by schneems** [comment]
this is fixed in master
