### ISSUE TITLE
Consider and sunspot_solr as trigger for Java?

### ISSUE THREAD

**Issue by johnbeynon** [heroku/heroku-buildpack-ruby#322]
Sunspot_solr has a dependency for a Java runtime - is it worth adding as a trigger along with 'yui-compressor' or leave it down to multipack with Java?

https://github.com/heroku/heroku-buildpack-ruby/blob/fbc7046672abe06bf4774c451f4a029aecf1a12e/lib/language_pack/ruby.rb#L560

**Comment by schneems** [comment]
JVM is now installed by default, we don't have to manually include it.
