### ISSUE TITLE
Full asset compile/cleanup taking more than 15 minutes.

### ISSUE THREAD

**Issue by nathany** [heroku/heroku-buildpack-ruby#329]
This is an issue I mentioned on the Heroku forums but haven't received any response:
https://discussion.heroku.com/t/slug-compilation-time-limit-when-upgrading-sprockets/870

When upgrading the version of **sprocket-rails**, it causes a full asset compile and a full cleanup. The cleanup goes through each and every file rather than just quickly cleaning up everything.

For our particular app, the time to run Bundler, build all the assets and clean all the assets exceeds the [Heroku 15-minute deadline](https://devcenter.heroku.com/articles/slug-compiler#time-limit) for deployment.

Is there anyway this could be sped up? Are newer versions faster? (if I could somehow get us upgraded to a newer version)

``` ruby
gem "rails", "4.0.12"
gem "sprockets-rails", "2.2.0" # lock to avoid asset precompile heroku timeout
gem "sprockets", "2.11.3"
```

This is where the Ruby build pack runs the asset precompile and cleanup:

https://github.com/heroku/heroku-buildpack-ruby/blob/e4bd79031406e1da7487d0269c86c895ed226c84/lib/language_pack/rails4.rb#L69

ref https://github.com/rails/sprockets-rails/issues/209

**Comment by nathany** [comment]
Will do. Thanks.

While [investigating the build pack](https://github.com/rails/sprockets-rails/issues/209#issuecomment-68314888) I noticed the Rails 4.0 and 4.1 have entirely different code paths. We're still on 4.0, so maybe things will go faster in 4.1. 

I also found out that the sprockets 3.0 beta is supposed to be faster, once we are able to upgrade to that.

**Comment by schneems** [comment]
The buildpacks use inheritance so the asset compilation in 4.0 and 4.1 is exactly the same.

**Comment by nathany** [comment]
Oh. I hadn't noticed that. Thanks @schneems. I'm sending in a support ticket right now.
