### ISSUE TITLE
Question: Strange segfaults with native extensions

### ISSUE THREAD

**Issue by dstokes** [heroku/heroku-buildpack-ruby#337]
Hey guys,

I've got a build server that utilizes the buildpack to create tarball slugs of applications. Those tarballs are later deployed to application servers. Everything seems to work fine until I load up a rails console on the app server. Initial runs of the rails console after a deploy cause gems with native extensions to be rebuilt, and throw segfaults. For example, nokogiri *always* rebuilds itself when initiating a console after a deploy, and trying to establish PG connections in the console causes segfaults (when running PGConn.new). After the initial failure, running the same commands succeed without error. My hunch is that the native gem components aren't surviving the slug creation and are being rebuilt on console initialization on the app server. The architecture and OS version is the same on both the build server and application server. I'm all out of ideas :/

**Comment by schneems** [comment]
> I've got a build server that utilizes the buildpack to create tarball slugs of applications. Those tarballs are later deployed to application servers.

This is basically what Heroku does with the build phase.

Almost every app deployed to Heroku uses native extensions i.e. `pg` gem with no problems. Most of them use nokogiri. My best guess would be that the libraries it is trying to link against might not be present in the other system you're putting on other applications?
