### ISSUE TITLE
Update to Bundler 1.8

### ISSUE THREAD

**Issue by titanous** [heroku/heroku-buildpack-ruby#353]
Is it possible to update to the latest Bundler v1.8? We have a user running into bundler/bundler#3063, which was fixed in v1.8.0.

I can PR the version bump, but it looks like the tarball needs to built and saved into the Heroku S3 account in order for it to work without forking competely.

Thanks!

**Comment by schneems** [comment]
There are bugs in 1.8 that prevent us from upgrading. I believe we are targeting an upgrade to 1.9
