### ISSUE TITLE
Run JRUBY_OPTS for assets:precompile

### ISSUE THREAD

**Issue by Ch4s3** [heroku/heroku-buildpack-ruby#356]
I'm trying to figure out how to run something like ```JRUBY_OPTS="--dev" bundle exec rake assets:precompile``` in the buildpack when JRuby is the application's Ruby. For JRuby this would cut the assets:precompile time in half.

It seems like the buildpack could check for JRuby somewhere around [here](https://github.com/heroku/heroku-buildpack-ruby/blob/ebf640b0855ac9f0851dc5ee76297f9f80615edb/lib/language_pack/ruby.rb#L742) and run it with the JRUBY_OPTS if ```jrub? == true```.

I can't seem to figure out how to do that on my fork though. Any help would be appreciated.

**Comment by schneems** [comment]
What does this flag do? What are your thoughts @jkutner ?

**Comment by Ch4s3** [comment]
Great question, it does the following:
+ client mode where applicable (generally older 32-bit JVMs)
+ TieredCompilation and TieredStopAtLevel=1, equivalent to client mode on newer Hotspot-based JVMs
+ compile.mode=OFF to disable JRuby's JVM bytecode compiler
+ jruby.compile.invokedynamic=false to disable the slow-to-warmup invokedynamic features of JRuby

Tiered Compilation/TieredStopAtLevel optimize for startup time but remove optimizations used for long running processes. Client mode on old JVMs does the 32-bit mode equivalent.

The issue here is that when ```rake``` is run under JRuby a new JVM is spun up the rake task runs and that JVM spins down. Setting --dev spins up the JVM more quickly and optimizes for short tasks.

I'd be happy to help implement this, but I can't quite figure out how to structure what I want to do.

**Comment by schneems** [comment]
Seems good, cc @jkutner

**Comment by jkutner** [comment]
Yes, this is a good idea. But we need to make sure JRUBY_OPTS is only set for the asset:precompile and not for runtime. I'll take a look at how we might do this.

**Comment by Ch4s3** [comment]
@jkutner that's why I didn't submit a pull. I couldn't quite figure out the whole flow. That said, its probably appropriate for bundle and assets:precompile.
