### ISSUE TITLE
Binary stub overwrite

### ISSUE THREAD

**Issue by cyx** [heroku/heroku-buildpack-ruby#388]
Some users might already have bin/bundle, bin/rake existing (which also might be the stub created on a windows machine).

For these cases, the application will choke out with the shebang line with an error like:

``` sh
~ $ bundle exec bash                                                                                           
: No such file or directory   
```

We should probably just write out the stubs into the app's bin folder.

**Comment by hone** [comment]
can you elaborate here? We do only write stuff out in the slug? Do you mean the bundler binstubs?

**Comment by cyx** [comment]
So for windows, sometimes they have bin stubs for certain apps.

For the normal case, I know we write out bin/ruby bin/* etc for normal ruby
apps. It seems to be the case that
we don't overwrite these stubs if they exist -- at least that's the bug I
was able to figure out with that windows customer.

**Comment by hone** [comment]
ah right. so you think we should overwrite them for windows?

**Comment by cyx** [comment]
I think we should overwrite ruby, (and the other known bin that we know we
produce) for everything for completeness. Otherwise they
might be linked incorrectly or something.

**Comment by hone** [comment]
Generally, I'm not in favor of overwriting user things when we can avoid
it. This might have unnecessary side effects for people who write their own
things and don't want them overwritten. Ruby might be an exception here.

**Comment by cyx** [comment]
Yep, in this case it was bundle and ruby which seems to have produced the
weird error.

Since we already have the windows branch check, we might as well overwrite
for most of the bins in that scenario since it seems this case
mostly stems for \r windows-y things.

**Comment by hone** [comment]
@cyx if I pull together a PR for this, do you have a repro case I can use to test it?

**Comment by cyx** [comment]
No repro case, but making an app with a broken ruby binary like

    #!/bin/bash
    echo 'broken'

Should suffice.
