### ISSUE TITLE
Use Bower to install assets before precompile

### ISSUE THREAD

**Issue by akshayrawat** [heroku/heroku-buildpack-ruby#392]
Rails 4 Sprockets supports managing assets via bower. The setup I want to get at is:
- Install bower components at `vendor/assets/bower_components` (specified in `.bowerrc`)
- Add that dir to `gitignore`.
- Have the Heroku buildpack run `bower install` before assets precompilation.

The buildpack may detect the need to install bower based on the presence of a `bower.json` or some other strategy. Running `bower install` at an appropriate time can be left to the user.

**Comment by darbyw** [comment]
:+1:

**Comment by akshayrawat** [comment]
Bower's Sprocket integration is [noted here](https://github.com/stve/bower#usage-with-sprockets)

**Comment by orlando** [comment]
@akshayrawat I think a good approach is to use a nodejs buildpack along with the ruby one, adding multiple buildpacks using `heroku buildpack` command or using [https://github.com/ddollar/heroku-buildpack-multi](https://github.com/ddollar/heroku-buildpack-multi).

this is what we do for our app using `browserify-rails`

**Comment by joallard** [comment]
Using the multi+node buildpack adds a good 30s-1min to a typical compile. Not ideal considering it's ran even on failed deploys.

**Comment by orlando** [comment]
@joallard if deploy time is a constraint, then I think you should precompile locally.

**Comment by joallard** [comment]
It's not a constraint, it's an annoyance. I'd have to check my assets into source, and I'm trying to limit the number of stupid things that I do.

**Comment by hunterloftis** [comment]
I generally recommend that ruby folks who're using bower compose the node and ruby buildpacks together as explained by @orlando. There's actually a build-in command for this (`heroku buildpacks`):

- https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app

It may seem to slow things down, but I suspect that's mostly perception: if you're running `bower install`, you have to run it somewhere. If you run it in node then the node bp will take the same amount of time the ruby bp would have taken to execute it.

A quick non-scientific test looks like composition might add about ten seconds to your build time:

```
$ time git push heroku master
Counting objects: 1, done.
Writing objects: 100% (1/1), 185 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching custom git buildpack... done
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  0.10.38
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Downloading and installing node 0.10.38...
remote:        Using default npm version: 1.4.28
remote:
remote: -----> Restoring cache
remote:        Loading 1 from cacheDirectories (default):
remote:        - node_modules
remote:
remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json)
remote:
remote:        > express@0.0.0 postinstall /tmp/build_5635f63f8fc70235cb7813ee44fd883e
remote:        > echo NODE_ENV=$NODE_ENV
remote:
remote:        NODE_ENV=production
remote:
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 1 cacheDirectories (default):
remote:        - node_modules
remote:
remote: -----> Build succeeded!
remote:        ├── body-parser@1.12.4
remote:        ├── cookie-parser@1.3.5
remote:        ├── debug@2.1.3
remote:        ├── express@4.12.4
remote:        ├── jade@1.9.2
remote:        ├── morgan@1.5.3
remote:        └── serve-favicon@2.2.1
remote:
remote: -----> Discovering process types
remote:        Procfile declares types   -> (none)
remote:        Default types for Node.js -> web
remote:
remote: -----> Compressing... done, 6.8MB
remote: -----> Launching... done, v27
remote:        https://morning-ravine-4522.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/morning-ravine-4522.git
   d52f5da..bffb796  master -> master

real	0m9.941s
user	0m0.046s
sys	0m0.041s
```
