### ISSUE TITLE
Proposal for overriding WEB_CONCURRENCY SENSIBLE_DEFAULTS

### ISSUE THREAD

**Issue by nruth** [heroku/heroku-buildpack-ruby#393]
# Problem
WEB_CONCURRENCY is insufficient for users of the process scheduler gem, switching from PX to 1X or even 1X to 2X dyno type depending on load / time of day / etc.

SENSIBLE_DEFAULTS are great, but don't work for apps eating a lot of RAM, e.g. people who couldn't make the asset group work again & are using sass-rails.

# Solution (idea)

New variables:

WEB_CONCURRENCY_1X
WEB_CONCURRENCY_2X
WEB_CONCURRENCY_PX

and changing some lines of def set_default_web_concurrency` to:

` export WEB_CONCURRENCY=${WEB_CONCURRENCY_1X:-${WEB_CONCURRENCY:-2}}`
` export WEB_CONCURRENCY=${WEB_CONCURRENCY_2X:-${WEB_CONCURRENCY:-4}}`
` export WEB_CONCURRENCY=${WEB_CONCURRENCY_PX:-${WEB_CONCURRENCY:-16}}`

Would this be a reasonable PR?

**Comment by schneems** [comment]
I added https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/ruby.rb#L211 so you could write custom functionality. You could write something like this in your app:

```
case ENV['HEROKU_RAM_LIMIT_MB']
when 512
  ENV["WEB_CONCURRENCY"] = ENV["WEB_CONCURRENCY_1X"]
end
```

Or you could do maths

```
ENV["WEB_CONCURRENCY = ENV['HEROKU_RAM_LIMIT_MB'] / 512.0
```

etc.

I think that should be enough for your use case

**Comment by nruth** [comment]
Yes that's the code I was suggesting changing. Do you mean forking the buildpack?

**Comment by schneems** [comment]
>  Do you mean forking the buildpack?

You can put it in your `config/puma.rb` or `config/unicorn.rb` file. No need to get all buildpack-y. If you __really__ wanted to write it as a buildpack, I would make a micro buildpack and use buildpack-multi to call the ruby buildpack then yours. Maintaining a fork of the Ruby buildpack is no small feat.

**Comment by nruth** [comment]
I really *don't* want to stop using the default buildpack for exactly those reasons :)

Thank you for the advice. I'll try the puma option and the code you put above. I hadn't realised that would work.

Might be a useful thing to add to the platform documentation.
