### ISSUE TITLE
libicu-dev

### ISSUE THREAD

**Issue by sobrinho** [heroku/heroku-buildpack-ruby#396]
Hey guys,

We are having a lot of trouble to make charlock holmes run on heroku due to libicu-dev.

You could see the TL;DR of the pain here: http://genius.it/5099323/tooky.co.uk/using-charklock_holmes-on-heroku

We almost have the perfect world using the [webantech build pack](https://github.com/webandtech/heroku-buildpack-ruby/) which is basically the same ruby build pack but with libicu-dev.

Although it's not ideal because we must rely that webantech would have time to keep it in sync with master.

Any thoughts?

**Comment by sobrinho** [comment]
I've published a definitive a guide on charlock holmes wiki, but still no the ideal solution.

See https://github.com/brianmario/charlock_holmes/wiki/Installing-charlock-holmes-and-libicu-dev-on-heroku

**Comment by schneems** [comment]
> We almost have the perfect world using the webantech build pack which is basically the same ruby build pack but with libicu-dev.

Make a micro buildpack that installs libicu-dev then use multi-buildpack to call your micro buildpack then the ruby buildpack

**Comment by sobrinho** [comment]
@schneems that's essentially what I did using apt buildpack, bundler build pack and ruby build pack.

I first assumed it was too complex but looking again it's not that much.

Thanks!
