### ISSUE TITLE
Split buildpack into ruby+bundler and rails?

### ISSUE THREAD

**Issue by nashbridges** [heroku/heroku-buildpack-ruby#399]
Background: [Torba](https://github.com/torba-rb/torba) is a Ruby (+ shell) tool that fetches frontend assets to a local machine and makes them accessible for Sprockets to precompile.

I was [asked](https://github.com/torba-rb/torba/issues/4) whether it is possible to use Torba on Heroku (without precompiling assets locally). My proposal solution (that is, to fork this buildpack and modify it) seems not a good one, because I (or someone else) would have to maintain a fork that doesn't belong to me.

What could be more appropriate is to have a decoupled Torba buildpack which could be used within heroku-buildpack-multi. However, Torba is a gem and needs Bundler for that. This could be solved with heroku-buildpack-multi that contains (not existing yet) ruby-bundler + torba + (not existing yet) rails buildpacks.

Maybe I miss a more easier solution here?

**Comment by schneems** [comment]
There's another buildpack for ruby maintained by @dpiddy https://github.com/dpiddy/heroku-buildpack-ruby-minimal that might be exactly what you're looking for.

**Comment by dpiddy** [comment]
I don't recommend using my buildpack anymore, and in fact it should be deprecated. It probably doesn't work with the cedar-14 stack for example.

**Comment by nashbridges** [comment]
I'm closing this in favour of #442
