### ISSUE TITLE
Buildpack for the library libmagic

### ISSUE THREAD

**Issue by Kameshwaran** [heroku/heroku-buildpack-ruby#409]
Hi 

I'm trying to install <a href="https://github.com/blackwinter/ruby-filemagic">ruby-filemagic</a> gem. It requires `libmagic` library as dependency. Due to lack of this dependency, the gem installation fails in heroku during deployment.

**Comment by schneems** [comment]
Open a support ticket with heroku, this isn't a bug in our buildpack. The TLDR is you need to use multi-buildpack and compile your own binary of libmagic. Use the multi-buildpack to install your binary, then run the ruby-buildpack.
