### ISSUE TITLE
new performance dynos & default web concurrency 

### ISSUE THREAD

**Issue by nruth** [heroku/heroku-buildpack-ruby#410]
http://blog.heroku.com/archives/2015/8/20/introducing-improved-performance-dynos
https://github.com/heroku/heroku-buildpack-ruby/blob/154fab366ff2a611893a825eff33d537d717a350/lib/language_pack/ruby.rb#L218

The switch will need updating with the new RAM values, and the m and l box will probably need a different default WEB_CONCURRENCY?

**Comment by schneems** [comment]
Yes, we need to do this.

**Comment by nruth** [comment]
I just realised I have no idea what `ulimit -u` is actually returning, it's probably not the available RAM in the system? Googling said something about "maximum processes available to a single user".

If those figures haven't changed with the dyno size I think this ticket can just be closed because the current settings already work even if they're not optimised (which needs doing per-app anyway).

The only thing that looks like it'd need changing is `HEROKU_RAM_LIMIT_MB` for the PX dyno, which is set to 6144 but the node has 14GB available.
