### ISSUE TITLE
How do we know when a change is deployed?

### ISSUE THREAD

**Issue by shaqq** [heroku/heroku-buildpack-ruby#411]
@schneems 

We seem to have been affected by this PR:

https://github.com/heroku/heroku-buildpack-ruby/pull/404

But, we saw it last Friday. Are Heroku Ruby deploys always up to date with master?

**Comment by schneems** [comment]
>  Are Heroku Ruby deploys always up to date with master?

No. Generally changes are put on master for a time before being deployed to the entire platform. Anything on master is considered stable and deployable to the platform though. 

What happened? We've had 1 other issue reported but it was later determined that change was unrelated. To date we've seen no negative regressions on anyone's apps with this change. We would like to fix this for everyone before pushing it out. Can you give me some more information or open a support ticket help.heroku.com search for rails 4.1 and link this issue if it would help for me to have access to your app.

**Comment by shaqq** [comment]
@schneems is there a way to know _when_ a change is, or about to be, deployed to the platform?

**Comment by shaqq** [comment]
We were going to follow up with our CSA, but we can open a support ticket as well.

**Comment by schneems** [comment]
All changes are staged on master before they're deployed. Could be days, or hours. The best way to know about when a change is deployed would be to check https://devcenter.heroku.com/changelog

**Comment by shaqq** [comment]
@schneems I can't find the PR I'm referring (https://github.com/heroku/heroku-buildpack-ruby/pull/404) in that Changelog. Could you point me to it?

**Comment by schneems** [comment]
The changelog only has released software. This #404 isn't released yet. We keep a ruby changelog as well https://github.com/heroku/heroku-buildpack-ruby/blob/master/CHANGELOG.md

**Comment by shaqq** [comment]
@schneems so you're saying it would have been impossible for https://github.com/heroku/heroku-buildpack-ruby/pull/404 to have affected us, since it wasn't released?

**Comment by schneems** [comment]
Lots of people use master to deploy to Heroku. I assume you're doing so. If you're not setting `BUILDPACK_URL` then you're not using master, and this wouldn't affect you. Without opening up a ticket and me seeing your app, I don't know what  you're doing.

**Comment by schneems** [comment]
I don't see a ticket from you. If you opened one and it didn't get in my queue send me the ticket number. Probably going to deploy this soon. If it caused an issue with your app I need to know about it. Until then i'm going to close this issue pending an issue reproduction.
