### ISSUE TITLE
Bundle check

### ISSUE THREAD

**Issue by kirs** [heroku/heroku-buildpack-ruby#419]
`bundle check` checks if the dependencies listed in Gemfile are satisfied by currently installed gems.

Instead of running `bundle install` on push, we can first check if we actually need to do bundle install with `bundle check`, and run `bundle install` if it's required

That's what we do that in capistrano: https://github.com/capistrano/bundler/blob/master/lib/capistrano/tasks/bundler.cap#L33-L36

Thanks!
/cc @schneems

**Comment by hone** [comment]
We did this in the old buildpack, but it still needs to do the diff. When I was doing performance testing of bamboo to cedar with the buildpacks, we found it was negligible in a perf difference. Maybe this has changed. But `bundle install` when all the deps are there shouldn't be a long operation. Not having the check removes branching logic and bugs that come out of that when you maintain a cache across multiple platforms.
