### ISSUE TITLE
switch ruby bin download URL easily

### ISSUE THREAD

**Issue by khoan** [heroku/heroku-buildpack-ruby#421]
currently, we need to fork and adjust VENDOR_URL constant to point to jemalloc ruby bin (see https://github.com/heroku/heroku-buildpack-ruby/issues/328)

can we instead have a RUBY_URL env to fulfil similar purpose?

**Comment by schneems** [comment]
Unfortunately we can't support people running arbitrary self compiled versions of Ruby. As in when their app breaks in unexpected ways they expect us to fix it.  If you can do it in the buildpack people will assume it's supported.
