### ISSUE TITLE
Curl does not handle transient network errors

### ISSUE THREAD

**Issue by mikehale** [heroku/heroku-buildpack-ruby#466]
In the [absence](https://curl.haxx.se/mail/lib-2014-08/0133.html) of a `--retry-connrefused` option like wget has, this buildpack should make curl attempts more robust. Otherwise errors like this can arise:

``` console
set -o pipefail; curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.0.tgz -s -o - | tar zxf - 
gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

A pure bash way to do this might look something like this:

``` bash
set -o pipefail
for try in $(seq 10); do
  # retry with exponential backoff for approximately 1m
  rand=$(echo "scale=4; $((RANDOM%10000+1))/10000" | bc)
  power=$(echo $(( $try > 7 ? 7 : $try )))
  exponential_wait=$(echo "(2^$power+$rand) * 0.1" | bc)

  curl -L --fail --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.0.tgz -s -o - && break
  >&2 echo "attempt $try failed, sleeping ${exponential_wait}s"
  sleep $exponential_wait
done | tar zxf -
```

**Comment by schneems** [comment]
Maybe we get wget on the system instead?

**Comment by mikehale** [comment]
Wget is available on cedar-14, but not cedar: https://devcenter.heroku.com/articles/cedar-ubuntu-packages.

An alternative to the bash approach would be to implement some of the retry logic in ruby in the buildpack.

**Comment by mikehale** [comment]
Thinking about this more broadly though, it would be ideal to have "a recommended way" to fetch resources that could be reused by any buildpack.

**Comment by schneems** [comment]
Doing this in ruby would be pretty easy. Check the status code and retry if it's non-zero. When cedar 10 is shut down all buildpacks could switch to wget.

**Comment by mikehale** [comment]
That sound like a good idea. It would also be good to test wget's behavior for various failure modes and make sure that whatever options we pass to it can handle them:

* connect timeout
* read timeout
* connection refused
* connection interrupted (partial data)
* ???

**Comment by schneems** [comment]
Closed via https://github.com/heroku/heroku-buildpack-ruby/pull/585
