### ISSUE TITLE
Can't change BUNDLE_WITHOUT configuration

### ISSUE THREAD

**Issue by adrienkohlbecker** [heroku/heroku-buildpack-ruby#476]
Hello,

I'm trying to remove a group from the list of exclusions.
Due to recent changes in behaviour in bundler (https://github.com/bundler/bundler/pull/4352), if I change the value of my `BUNDLE_WITHOUT` configuration, the install command is changed, but since the `.bundle` is still in the cache, it still picks up the old config.
I noticed there is https://github.com/heroku/heroku-buildpack-ruby/commit/0b7ad94efc871995dc2e4736878f5be19b71ca61 that prevents storing the config in the cache.

Would cutting a new release be enough to solve this issue?
Best,

**Comment by schneems** [comment]
If you're pointing at the buildpack master, then next time you release your app should only be restricted to what you have set in BUNDLE_WITHOUT.

If not you can use

```
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-ruby.git
```

To use what is on master. 

I would only do this temporarily. Once that change is deployed, you'll want to switch away from using master. 

Alternatively you can clear your cache manually using https://github.com/heroku/heroku-repo but that will clear __everything__ including your assets and gem cache, it will be like you're deploying to your app for the first time. That might be overkill.

**Comment by adrienkohlbecker** [comment]
Yes that's why I was asking about a release, we're not using master.
I'll try the heroku-repo approach then!

**Comment by schneems** [comment]
I will probably deploy that change sometime next week.

**Comment by adrienkohlbecker** [comment]
Good to know, thanks!
