### ISSUE TITLE
Feature req: Option to run rake db:migrate upon release (before restarting the dynos)

### ISSUE THREAD

**Issue by oma** [heroku/heroku-buildpack-ruby#48]
Save downtime and errors by providing the _option_ to run migrations on push/deploy. 
git push heroku --with-migrations 
OR 
detect and run new migrations automatically. (perhaps enable/disable using an ENV-var?) 

Minimal downtime is critical and a though nut to solve. It's a bigger problem for the bigger apps (highest paying customers?), I hate the trade-off continuous deployment vs uptime, but it will always be there, I guess.

The total downtime of the app during deployment could be drastically reduced, especially if the environment is already loaded in one of the other rake tasks run. The migration would take a split second. Added benefit is that a failed migration would not only rollback DB but also the deploy.

The two commands are PITA. I could run 'git push heroku && heroku run rake db:migrate', but often the push never return control to my term, so I still have to watch it and most likely wasting valuable seconds of uptime. I know I'm repeating myself now: a failed migration would rollback, but the code depending on the migrations would not be rolled back. I'd have to rollback the release manually. I'd like this automated :)

If I knew how to do this myself, I'd send a pull request... Thanks guys, I appreciate your work! /fan

**Comment by jhubert** [comment]
@schneems Any recommendation as to where I should track this? We're experiencing some similar troubles with migrations and preboot. Thanks!

**Comment by dmathieu** [comment]
You should probably look ingo [release phase](https://devcenter.heroku.com/articles/release-phase) instead.
