### ISSUE TITLE
Allow using vendored gems with `bundle install --local`

### ISSUE THREAD

**Issue by jingweno** [heroku/heroku-buildpack-ruby#481]
We're experimenting with vendoring gems to avoid failed gem installation failing deployments. There was [an attempt](https://github.com/bundler/bundler/pull/4103) to let bundler retry when failed but we still experienced this error sometimes (hitting the retries limit?).

What we did was to check in the result of `bundle package --all` to git and we run `bundle install --local` to install gems. But the Ruby buildpack doesn't seem to pick up the vendored gems for deployment. I wonder whether there's anyway to support it. Another benefit of this approach is we saw faster gem installation speed than downloading everything from rubygems.org

A solution to support this in the buildpack may be to detect if the directory `vendor/cache` exists, if it does, we run `bundle install --local` instead of `bundle install`. A fancier solution may be to extend `Gemfile` to allow a "local" flag, something like:

```rb
ruby "2.3.1"
local true
```

Then the buildpack reads from it (similar to reading Ruby version) and acts accordingly.

Thoughts?

Related to https://github.com/heroku/heroku-buildpack-ruby/issues/106.

/cc @heroku/api

**Comment by schneems** [comment]
This should be how bundler behaves https://github.com/heroku/heroku-buildpack-ruby/pull/439#issuecomment-195507270

**Comment by jingweno** [comment]
@schneems:

> This should be how bundler behaves #439 (comment)

Yes, `bundle install --local` would work. But how do we make it run with `--local

**Comment by rwz** [comment]
@jingweno seems like bundler should automatically invoke `--local` mode when `vendor/cache` is available. We need to verify this though.

**Comment by rwz** [comment]
Ok, can confirm, I've just deployed a heroku app with a bunch of private gems without any credentials for the private gem store. Also, the buildpack completely skipped the step where it talks to rubygems.org. 
:+1:

**Comment by rwz** [comment]
Also, bumped ruby version on one of the apps from 2.3.0 to 2.3.1, so buildpack had to re-install ALL the gems.

Again, completely bypassed talking to rubygems/private-gem-store step. This is amazing!

**Comment by jingweno** [comment]
🎉

**Comment by schneems** [comment]
Ask, and ye shall receive.

By accident.

Because an upstream library already fixed the issue 😉

**Comment by pjaspers** [comment]
I think this changed somewhere between 4 years ago and now? At first glance, seems like bundle no longer picks up on it.

`remote:        Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4`

I realise probably no ones still bundles their gems, but I still kind of like it. So if any interest I might want to bring this back.

**Comment by jeromegn** [comment]
I've noticed the same as @pjaspers. All our gems are packaged in `vendor/cache`, but heroku still just install of them in our CI pipeline.
