### ISSUE TITLE
Exclude sprockets cache from the slug

### ISSUE THREAD

**Issue by werkshy** [heroku/heroku-buildpack-ruby#485]
I have been investigating large slug sizes and it looks like `tmp/cache/assets/sprockets`, the sprockets build cache, is being included in the slug.

It looks like there is no way to hook into `assets:precompile` to handle this since the re-caching of that path happens right after it runs:
https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/rails4.rb#L94

Would it work to clear `tmp/cache` after the build cache has been repopulated but before tarring the slug? Seems like we'd need to modify the build pack to make that work.

**Comment by schneems** [comment]
It's tricky as you mention because we need to perform maintenance operations around cleaning the cache directory before we store it. Did you open up a ticket about high slug size? Maybe there is another way we could reduce it?

**Comment by werkshy** [comment]
Our high slug size is largely due to the fact that assets are included in our slug times: once as source in app/assets, once as compiled assets, and once in the sprockets cache. The sprockets cache is the worst offender because it grows seemingly without limit as we deploy. Now that we know this we can blow away the build cache and regain 100MB in slug size whenever we need to, so we don't need any tech support there, thanks. 

What is the intention of the rails language pack *not* cleaning tmp/cache after the build cache has been updated? To my understanding that is just an oversight.

**Comment by schneems** [comment]
Some people don't precompile all their assets they want to compile some in production if we nuked the tmp/cache directory then any fragments that might be able to speed up their dynamic asset generation get blown away.

Maybe that's not something we want to encourage, but it's something we need to consider. To date the assets tmp dir is usually not the smoking gun on large slug sizes when people open tickets or if it is, then  there's usually another underlying cause. Right now the potential upsides don't merit a total breaking change for some subset of our users. We might re-evaluate in the future.

**Comment by rafbm** [comment]
@werkshy I’m affected by the same issue. You said (emphasis mine):

> Now that we know this _we can blow away the build cache and regain 100MB in slug size whenever we need to_, so we don't need any tech support there, thanks.

How exactly can you do this? Isn’t deploying a new release the only way to alter your slug? How can a deploy explicitly clear files from the slug?

**Comment by rafbm** [comment]
As a side note, mainly intended for @schneems, [this Help Center article](https://devcenter.heroku.com/articles/rails-4-asset-pipeline#caching) says:

> Heroku now caches 50mb worth of `tmp/cache/assets` […]

Not sure what to make of this “50mb”, considering our current `tmp/cache/assets` contains two directory weighing roughly 300MB each:

```
386M	tmp/cache/assets/sprockets
293M	tmp/cache/assets/production
678M	tmp/cache/assets
```

This is the output of `du -hd 1 tmp/cache/assets` in the context of `heroku run bash`.

**Comment by schneems** [comment]
You can clear your cache with this plugin https://github.com/heroku/heroku-repo

For your case please open a ticket https://help.heroku.com search “large slug size” and open a ticket so we can look into that specific case of cache growth.

**Comment by rafbm** [comment]
Thanks Richard. I (re-)opened a ticket I had with this added info. Just wanted to let you know here since I thought maybe that “50mb” was outdated info in the Heroku documentation.

**Comment by schneems** [comment]
It shouldn't be here's the code that should clean your assets https://github.com/heroku/heroku-buildpack-ruby/blob/866e86bd89cbb5d17a85d49d674065e51400b6b6/lib/language_pack/rails4.rb#L106. Though now that i'm looking at it, it only kicks in if you're using Rails 4+ and not with only plain Ruby/Rack. 

Can you give me the ticket number and I can take a look?

**Comment by rafbm** [comment]
Sure! Ticket number is 582208. Rails 5.1.6 app.
