### ISSUE TITLE
Failed to detect set buildpack heroku/ruby

### ISSUE THREAD

**Issue by andymagill** [heroku/heroku-buildpack-ruby#489]
It is my first time with Heroku and Ruby, so this is probably a noob issue but I can't find any solution anywhere.  I am following this guide :

https://devcenter.heroku.com/articles/getting-started-with-rails

I have my app setup, with ruby set as the buildpack, and with this gemfile :
```
    ## rails 
    source 'https://rubygems.org'
    ruby "2.1.5"
    
    ## bundler
    gem 'nokogiri'
    gem 'rack', '~>1.1'
    gem 'rspec', :require => 'spec'
    
    ## heroku
    gem 'rails_12factor', group: :production
    
    ## postgresql 
    gem 'pg'
```

When I try to push to Heroku with git push heroku master, i receive this error :
```
    C:\projects\test\my-app>git push heroku master
    Counting objects: 13, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (13/13), done.
    Writing objects: 100% (13/13), 2.02 KiB | 0 bytes/s, done.
    Total 13 (delta 3), reused 0 (delta 0)
    remote: Compressing source files... done.
    remote: Building source:
    remote:
    remote: -----> Using set buildpack heroku/ruby
    remote:
    remote:  !     Push rejected, failed to detect set buildpack heroku/ruby
    remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
    remote:
    remote: Verifying deploy...
    remote:
    remote: !       Push rejected to heroku-who-are-you.
    remote:
    To https://git.heroku.com/heroku-who-are-you.git
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'https://git.heroku.com/my-app.git'
```
This thing is driving me bananas. Any and all help would be appreciated!

**Comment by andymagill** [comment]
I was able to sort this out.  I was not on the master branch. I was trying to push develop to Heroku master. Really wish the guide would describe that requirement in the develop section.

**Comment by schneems** [comment]
> describe that requirement in the develop section.

I'm not 100% sure I follow what you were trying to do and how things failed. Are you saying that locally you were on a `develop` branch, but you didn't realize that `$ git push heroku master` was the equivalent of `$ git push heroku master:master` instead of `$ git push heroku develop:master`?

**Comment by andymagill** [comment]
@schneems Correct. I believed `git push heroku master` would push from whatever branch I was currently on.

**Comment by schneems** [comment]
I hate when that happens, it's pretty unclear. It's a tough thing to put into documentation since most people never need to push from another branch. It would probably be ignored by the people who need it and at worst confuse people that didn't.

I'm wondering how closely you looked at the deploy output and if there's some kind of message we could 
have exposed that might have tipped you off. Maybe something like this perhaps?

```
    remote: Compressing source files... done.
    remote: Building source from your master branch:
```

Even then it's still pretty subtle, you might think we're talking about `heroku master` instead of your local master. I'm also not sure if that information is exposed when pushing via git (the source branch name).

**Comment by andymagill** [comment]
I agree, not every detail can go into the docs, and this situation is well inside noob territory.  I did look closely at the output and I think your suggestion would be an improvement. It could say "origin/master" instead of just "master" to avoid people dismissing it as the destination branch heruko master.

Also, if the output simply said "Missing Gemfile" I would have started questioning my sanity and expanded my search for the cause elsewhere.
