### ISSUE TITLE
LibYAML is outdated

### ISSUE THREAD

**Issue by jchesterpivotal** [heroku/heroku-buildpack-ruby#495]
Cloud Foundry Buildpacks team received [this issue](https://github.com/cloudfoundry/ruby-buildpack/issues/66), highlighting that the LibYAML shipped with the buildpack is out of date and vulnerable to a CVE.

We settled on an approach of [removing references to LibYAML, instead relying on the `libyaml` library shipped and patched by Ubuntu](https://github.com/cloudfoundry/ruby-buildpack/commit/6a38bf786ac4eca3507970adada0fff58565c88d). 

Both cflinuxfs2 and cedar-14 have this package installed. We believe it would be possible for you to make the same change. The PR is not an exact match for the Heroku codebase, as it also includes CF-specific changes.

**Comment by schneems** [comment]
Thanks for the report, i'm digging into our options right now.

**Comment by hone** [comment]
We've now updated to `0.1.7` of libyaml.
