### ISSUE TITLE
Why is the Gemfile.lock required?

### ISSUE THREAD

**Issue by MattiSG** [heroku/heroku-buildpack-ruby#503]
Hi,

We are using this build pack for review apps on a Jekyll website (https://github.com/sgmap/beta.gouv.fr).
Since we deploy on GitHub Pages, we use dependencies versions from https://github.com/github/pages-gem, which is updated very often (~once a day) lately.

We wrote a dynamic `Gemfile` that fetches these versions and allows us to always reflect production. The only reason for which we have to maintain a `Gemfile.lock` is for Heroku review apps, and it's [getting](https://github.com/sgmap/beta.gouv.fr/pull/388) [quite](https://github.com/sgmap/beta.gouv.fr/pull/378) [annoying](https://github.com/sgmap/beta.gouv.fr/pull/374).

When trying to find an alternate build pack that would support building without `Gemfile.lock`, I've noticed that this one actually deletes the `Gemfile.lock` if it's been built under Windows.

1. Why is it required under other platforms?
2. Would you be open to some flag to support building without it, or should I just fork?
3. If I were to add a flag, which implementation for passing the information would you recommend?

Thanks,
Matti

**Comment by schneems** [comment]
If you don't have a Gemfile.lock there is no guarantee your dependencies resolve and what you're trying to deploy will work. This is so off the best practice path I would recommend forking, we would not support a flag.

**Comment by MattiSG** [comment]
Okay, thanks for the quick reply.

For those who would be interested, we used a workaround here: https://github.com/heroku/heroku-buildpack-ruby/commit/4d98efc884b999ccba7cc37ff214ec3bdb9a4059. Context: https://github.com/sgmap/beta.gouv.fr/pull/392.
