### ISSUE TITLE
Rails 4 Assets Caching doesn't pay attention to the assets prefix

### ISSUE THREAD

**Issue by bronislav** [heroku/heroku-buildpack-ruby#504]
In our application, we are using `assets.prefix` configuration option and because of this we have different paths for [public_assets_folder](https://github.com/heroku/heroku-buildpack-ruby/blob/ce11aca649273103dfeed0ccc5880858be116aa6/lib/language_pack/rails4.rb#L61) and [default_assets_cache](https://github.com/heroku/heroku-buildpack-ruby/blob/ce11aca649273103dfeed0ccc5880858be116aa6/lib/language_pack/rails4.rb#L65).

I understand that the easiest way to get around this is to fork and update those values. But maybe there are another options?

**Comment by schneems** [comment]
Rails doesn't make these values readable or exportable easily. Adding that feature to Rails to export those values would be the only way we could properly detect it here.

**Comment by bronislav** [comment]
@schneems Thank you for you answer. I would like to add this feature to the rails, but in what way do you want to consume this option?

**Comment by schneems** [comment]
We would need some kind of a configuration export. Maybe a json or machine readable version of all config. Realistically this isn't a huge priority. Is there any reason why you can't put your assets in `public/assets`?

**Comment by bronislav** [comment]
We are integrating one of our projects with into 3rd party website at some prefix. And as a result, we   only receive requests with that prefix. And to successfully render our application we should put assets under `/<prefix>/assets`

**Comment by schneems** [comment]
You could use a middleware to serve assets from that prefix, or you could copy over the folder in `public/assets` to that prefix after they're done generating using Rake Task enhance http://www.dan-manges.com/blog/modifying-rake-tasks

**Comment by bronislav** [comment]
@schneems Thank you for excellent suggestions.
