### ISSUE TITLE
Unused securerandom require

### ISSUE THREAD

**Issue by elthariel** [heroku/heroku-buildpack-ruby#506]
I was just randomly reading code and just noticed this require seems useless:
https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/rails5.rb#L1

**Comment by schneems** [comment]
We can probably get rid of that, assuming it is required somewhere else. We definitely use secure random.

**Comment by nsuchy** [comment]
@schneems Has any progress been made on this issue? If not, we're already including it in the Rakefile (See: https://github.com/heroku/heroku-buildpack-ruby/blob/9011faaf211f8eb1c077885422671ae9bc7aa094/Rakefile#L99) so would it be safe to remove from 
https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/rails5.rb#L1 and https://github.com/heroku/heroku-buildpack-ruby/blob/22b24b66c42afdf8c95cc16143221ffd7b2d7f7b/lib/language_pack/rails41.rb#L1 . If so is a pull request welcome on this issue?

**Comment by schneems** [comment]
It's used here https://github.com/heroku/heroku-buildpack-ruby/blob/71c18ff545608fe58f8007bdff76d59ad607e351/lib/language_pack/rails41.rb#L39. The require's not killing anything. Duplicate requires are ignored. 

It was probably added while prototyping something but then never cleaned up. We are generally extremely conservative when it comes to cleanup and refactoring. The test suite is not truly comprehensive and tiny "easy" changes can suck up lots of development time. The Rakefile is almost entirely untested. 

My preference is that this line stays put unless it's actively causing issues. Thanks for the interest though!
