### ISSUE TITLE
v151, bundler version upgrade is crashing app

### ISSUE THREAD

**Issue by hassanrehman** [heroku/heroku-buildpack-ruby#524]
Hi,

I'm using Using cedar-14 on heroku, on an app with ruby 1.9.3p551 and rails 3.2.3.

Since the recent update, it's not loading initializers properly. For instance, we use audited gem. There is an initializer which sets some settings on it like Audited.current_user_method ...  
Here it says Audited is not defined.

Reverting to v150 fixed the issue.

This is not a particular issue, just an example. There is something not right how the files are loaded in the application (gem paths maybe?).

regards,

**Comment by schneems** [comment]
Does your app work with Bundler 1.13.7 locally? 

Can you open up a ticket help.heroku.com search for "buildpack upgrade caused app to fail" link back to this issue.

**Comment by hassanrehman** [comment]
Yes. The initializers all run smoothly. I even tried with production environment on the local system (so as to detect if cached classes had something to do with it), but it all worked fine.

**Comment by schneems** [comment]
did you open a ticket? do you have a ticket id?

**Comment by hassanrehman** [comment]
Ticket #443048

**Comment by schneems** [comment]
We deployed a fix with v152 that should solve this issue.
