### ISSUE TITLE
v151: Adding ENV['RAILS_GROUPS'] = 'assets' Breaks Implementation

### ISSUE THREAD

**Issue by ToniRib** [heroku/heroku-buildpack-ruby#525]
Issue #516 made [a change](https://github.com/heroku/heroku-buildpack-ruby/pull/516/commits/bcc74ad47a502cdad4bcfc434fd0ef435e01164d) to the Rails 3 Language Pack that merges in the environment variable 'RAILS_GROUPS' set to 'assets' by default. Prior versions of the buildpack did not add this environment variable.

We had a section of our code that relied on the response to `Rails.groups.include?('assets')` which resulted in our app breaking after this new buildpack was implemented since all old builds returned `false` and all new builds on Heroku return `true`.

What was the reasoning behind adding this environment variable by default? Is it possible to fix this latest version to remove that default env var?

**Comment by schneems** [comment]
Thanks for the info. We're on it. This behavior change was not intentional, it was during a refactor needed to accommodate our Heroku CI beta. We didn't have any tests around this edge case but we will add them.

In the short term you can lock yourself to an older buildpack

```
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-ruby.git#v150
```

Thanks again for the report, and sorry for the breakage.

**Comment by hone** [comment]
@ToniRib sorry about that. That was unintentional on my part. Can you test this branch and see if this fixes it for you?

```
https://github.com/heroku/heroku-buildpack-ruby#fix_rails3_groups_regression
```

**Comment by ToniRib** [comment]
@hone Is there a way for me to deploy to Heroku with a specific branch of this buildpack? I take it all I need to do is use `heroku buildpacks:set` with the url you gave me?

**Comment by hone** [comment]
@ToniRib yeah, you can just use `heroku buildpacks:set https://github.com/heroku/heroku-buildpack-ruby#fix_rails3_groups_regression`. This will clear out all the existing buildpacks on your app and replace it with this. If you're using more than 1 buildpack, you'll want to use `heroku buildpacks:clear` and `heroku buildpacks:add` instead.

**Comment by ToniRib** [comment]
Alright I'll give it a try tomorrow when I can check with QA to ensure I'm not conflicting with anything they're doing on our test environment.

**Comment by ToniRib** [comment]
@hone Tested it out this morning and everything looks good! Thank you for your prompt help!

**Comment by schneems** [comment]
For cross ticket tracking this is 443054 in our other system.

**Comment by hone** [comment]
@ToniRib we just cut v152 which includes this fix. You can switch back to the official buildpack. Sorry again!
