### ISSUE TITLE
Buildpack is too dependant on one region in AWS S3

### ISSUE THREAD

**Issue by nathansamson** [heroku/heroku-buildpack-ruby#542]
Due to the AWS S3 outage a few days ago I noticed I could not deploy any rails applications anymore.

My proposal
A) Do not link directly to AWS S3, but rather to cloudfront (linked to S3).
I believe this will reduce the chance of a failure in one AWS region to impact everything (this will have a slightly higher cost I believe, but still acceptable I would say)

B) If possible (but this might be limitation in buildpack system) fetch the ruby packages, and store them in the cache as well. So deploying an existing rails app (with cache) is not dependant on AWS anymore at all

**Comment by dmathieu** [comment]
Doing this would not have allowed you to deploy your app during the S3 incident.
The heroku platform itself relies on S3 to store slugs.
Furthermore, during the entire duration of that incident, the Heroku API was disabled. For architectural reasons, running builds depends on that API being available.

So while the buildpack could have run, the platform wouldn't have been able to perform the build in the first place anyway.

**Comment by nathansamson** [comment]
Except that I am using https://github.com/deis/workflow which is using the same buildpacks, but was not affected by the outage as I am running in the eu-west zone :)

**Comment by dmathieu** [comment]
I think you can understand why we would be reticent on setting up a cloudfront bucket so customers can use solutions others than the one we provide :smile:

The buildpack provides configuration to set hostnames and bucket names: https://github.com/heroku/heroku-buildpack-ruby/blob/46e245f60b3fd14754bca5a32c20e88d6a41982b/Rakefile#L5
You can fork it and configure it as you see fit.

**Comment by schneems** [comment]
We used to have cloudfront for our prebuilt binaries but it provided very minimal speed improvements and was extremely expensive. It is not something we would do again. As @dmathieu said, the features already exist for you to program the functionality you want in the buildpack, as you're off the managed path, you'll need to do that yourself.

**Comment by nathansamson** [comment]
Makes sense.

@dmathieu 
For future reference the correct environment variable is BUILDPACK_VENDOR_URL defined in https://github.com/heroku/heroku-buildpack-ruby/blob/ce11aca649273103dfeed0ccc5880858be116aa6/lib/language_pack/base.rb#L18 but thanks for pointing out that it actually exists
