### ISSUE TITLE
NODE_VENDOR_URL is hardcoded

### ISSUE THREAD

**Issue by pynixwang** [heroku/heroku-buildpack-ruby#545]
https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/helpers/node_installer.rb#L8

this url is blocked by gov in some country.

we need a ENV to set mirror

btw. node version stay at 0.10

**Comment by schneems** [comment]
We're updating this soon for the release of rails 5.1 which now requires yarn for support.

We are going to use our own service to download the binaries, so this would involve much more work than changing a URL, you would have to run a service that matches our API. 

Currently the service we use to serve node is private, i don't know if we could change that in the future cc @hunterloftis @jmorrell

**Comment by pynixwang** [comment]
if use #540 , I just need a json file as service that matches your API.

**Comment by hunterloftis** [comment]
@schneems the code isn't open sourced, but the service is public:

- https://nodebin.herokai.com/v1/node/linux-x64/latest?range=6.x
