### ISSUE TITLE
Allow puts statements in Gemfile

### ISSUE THREAD

**Issue by schneems** [heroku/heroku-buildpack-ruby#550]
If we only take the last line from `bundle platform --ruby` we can allow people to add `puts` to their Gemfile.

**Comment by xtagon** [comment]
@schneems This one affected me when I tried to add a `puts` statement to our Gemfile to make it clear that were were doing conditional checks before running the Gemfile (to support installing gems with either Rails 4 or Rails 5). When we pushed to Heroku, it wouldn't deploy, and the error was rather cryptic. It takes your `puts` statement and tries to fetch an S3 asset using the dasherized version of whatever you printed, then fails. It worked when we removed the `puts` statement but that's not an ideal solution.
