### ISSUE TITLE
Support ".ruby-version" as fallback for Ruby version

### ISSUE THREAD

**Issue by franklinyu** [heroku/heroku-buildpack-ruby#568]
Currently if Ruby version is not specified in Gemfile, it fallback to default version ([2.3.4](https://github.com/heroku/heroku-buildpack-ruby/blob/111151fb23dbf9cf725ddcad3489db31ebe7f569/lib/language_pack/ruby_version.rb#L15) currently). See [this Gist](https://gist.github.com/fnichol/1912050) for description of `.ruby-version` file. Currently my `.ruby-version` looks like `ruby-2.4.1`.

I think [this method](https://github.com/heroku/heroku-buildpack-ruby/blob/111151fb23dbf9cf725ddcad3489db31ebe7f569/lib/language_pack/ruby_version.rb#L106-L114) is related.

**Comment by schneems** [comment]
This isn't the place for that functionality. We get our Ruby version from Bundler. The best way to do it would have `bundle update --ruby` also generate a `.ruby-version` that you can use locally.

That being said you can build this yourself with:

```ruby
# Gemfile
ruby File.read(".ruby-version")
```
