### ISSUE TITLE
Heroku CI: Provide a way to skip DB setup

### ISSUE THREAD

**Issue by csuhta** [heroku/heroku-buildpack-ruby#572]
I have an app in Heroku CI and I do not want the Ruby buildpack to run `rake db:schema:load_if_ruby` or friends for me. I want to handle it myself.

I have this (in part) in my app.json:

```
"environments": {
  "test": {
    // …
    "scripts": {
      "test-setup": "",
      "test": "bundle exec rake test"
    }
  }
},
```

The `"test-setup": ""` part is trying to prevent this phase from happening:

```
-----> Clearing db:test:purge db:create db:structure:dump rake tasks
-----> Detecting rake tasks
-----> Preparing test database
       Running: rake db:schema:load_if_ruby
```

Is there a way to skip this step?

**Comment by schneems** [comment]
Can you tell me why you don't want us to run `db:schema:load_if_ruby` ?

**Comment by csuhta** [comment]
I tried to write up a description of why, but it was turning into a big admission of how many smells our testing setup has. Sorry for wasting your time, ignore me!

**Comment by schneems** [comment]
Ha! No worries. Let me know if you want to come back to this. You're not the first to ask for this ability, but so far all the cases were able to be worked around fairly easily.

**Comment by elroadster** [comment]
Does this functionality exist now? We rather not wipe the database clean via db:schema:load task as we have very expensive test data loading which we rather control the intervals for freshness.

**Comment by fbjork** [comment]
@schneems Also looking for a way to skip this in Heroku CI. Any progress?

**Comment by schneems** [comment]
I’m out on paternity leave

**Comment by elroadster** [comment]
Ended up not needing this but you can skip this with something like this on say lib/tasks/test.rake

`Rake::TaskManager.class_eval do
    def delete_task(task_name)
      @tasks.delete(task_name.to_s)
    end
  end

  Rake.application.delete_task('db:schema:load')
  Rake.application.delete_task('db:schema:load_if_ruby')

  namespace :db do
    namespace :schema do
      task :load do
        puts 'db:schema:load rake task did not run as we want to avoid it.'
      end
      task :load_if_ruby do
        puts 'db:schema:load_if_ruby rake task did not run as we want to avoid it.'
      end
    end
  end`

**Comment by csuhta** [comment]
Here's what I ended up doing in an initializer:

```ruby
if Rails.env.test?

  # Unseat several DB tasks to prevent Heroku CI from running them on our suite.
  # There isn't currently a way to prevent Heroku CI from running these commands.

  enemy_tasks = %w[
    db:schema:load
    db:schema:load_if_ruby
    db:structure:load
    db:structure:load_if_sql
    db:migrate
  ]

  enemy_tasks.each do |task_name|
    if Rake::Task.task_defined?(task_name)
      Rake::Task[task_name].clear
    end
    desc "Do nothing"
    task task_name do
      Kernel.puts "#{task_name} has no effect in test mode"
    end
  end

end
```


i.e. Re-define the task to be a no-op.

**Comment by fbjork** [comment]
@schneems Checking back in. Are you back from paternity leave? Would love to see the ability to disable this step on Heroku CI.

**Comment by Charizard** [comment]
@schneems I have a scenario where the schema is different in different branches (because of different features) and when one schema is dumped, during the next run of the other schema a DB level error occurs.

One more thing is, since there is no restricting branch name for CI runs, when one CI run starts when another one is in progress, the new one's dump erases all of the tables and the one running errors out with database not found.

**Comment by tjmcewan** [comment]
I have an app that hits the db when initialised, so the tables need to exist before the app boots.  Rails 4.2's `rake db:schema:load` works just fine with our app, but `rake db:schema:load_if_ruby` appears to boot the app _before_ loading the schema, so it dies.  I'll grab one of the monkey patches above for now, but be great to be able to disable it (or know why it's different to the standard `db:schema:load`, or even know where it's defined - I can't find it?).

Thanks!

**Comment by rubendinho** [comment]
@csuhta's approach worked for me. 

I needed to run a script before the database schema is loaded, so I ended up using the following: 
```
  enemy_tasks = %w[
    db:schema:load_if_ruby
    db:structure:load_if_sql
    db:migrate
  ] 
```

Then in a `test-setup`, script, i can run `rake db:schema:load` which loads the schema.
