### ISSUE TITLE
Double constraints on gems might be broken on Ruby 2.2

### ISSUE THREAD

**Issue by Ferdy89** [heroku/heroku-buildpack-ruby#574]
Hi! I've been recently running into an issue when pushing my app to Heroku, and the awkwardness can be summarized into:
```
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        You are trying to install in deployment mode after changing
remote:        your Gemfile. Run `bundle install` elsewhere and add the
remote:        updated Gemfile.lock to version control.
remote:        You have added to the Gemfile:
remote:        * sidekiq (>= 4.1.5, ~> 4.1)
remote:        You have deleted from the Gemfile:
remote:        * sidekiq (>= 4.1.5, ~> 4.1)
remote:        Bundler Output: You are trying to install in deployment mode after changing
remote:        your Gemfile. Run `bundle install` elsewhere and add the
remote:        updated Gemfile.lock to version control.
remote:
remote:        You have added to the Gemfile:
remote:        * sidekiq (>= 4.1.5, ~> 4.1)
remote:
remote:        You have deleted from the Gemfile:
remote:        * sidekiq (>= 4.1.5, ~> 4.1)
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
```
[Here's the minimalistic "app" I used to trigger this bug](https://gist.github.com/Ferdy89/283e22d429903b2994dab1f70d078235). Just deploying this to a fresh Heroku app seems to trigger it.

We are actually running Ruby 2.2.4 but I made sure it also happens on Ruby 2.2.7. It doesn't seem to happen on Ruby 2.3, though. I was also unable to reproduce it locally anyhow.

Notice how the gem has two version constraints:
```ruby
ruby '2.2.7'

source 'https://rubygems.org'

gem 'sidekiq', '>= 4.1.5', '~> 4.1'
```
Changing it to just `gem 'sidekiq', '~> 4.1'` seems to work just fine. This means it's not very critical but still looks like an unexpected result (again, I couldn't find a way to reproduce locally, so that's I filed the bug here and not in the Bundler project).

**Comment by schneems** [comment]
Not sure where this is coming from, but it may be a bug in Ruby.

I was able to get your gemfile to deploy by changing the ruby version

```
ruby '2.4.1'
```

Thanks for the report.

**Comment by schneems** [comment]
The issue persists in Bundler 1.15.0
