### ISSUE TITLE
Rails 5.1 with webpacker & without sprockets?

### ISSUE THREAD

**Issue by leshik** [heroku/heroku-buildpack-ruby#576]
Hi,
What is the correct way to deploy Rails 5.1 app with webpacker and sprockets disabled? I mean, if the app was created with `rails new myapp --webpack --skip-sprockets`. In this case, the asset pipeline is entirely disabled, and there is no `rake assets:precompile` task. Therefore `yarn:install` and `webpacker:compile` are never called. I also noticed that `node` binary isn't installed with current master of the buildpack in this case.

**Comment by leshik** [comment]
I've made quick & dirty PR #577 to support this functionality in case anyone else needs it. It works ok for me but I'm sure there is a better way to achieve this.

**Comment by schneems** [comment]
The way to do this in your app is to define an `assets:precompile` task.

```ruby
task "assets:precompile" do
  Rake::Task["webpacker:compile"].invoke
end
```

Our standard interface is the `assets:precompile` rake task hook. If you need something custom you can hook into that rake task.

>  I also noticed that node binary isn't installed with current master of the buildpack in this case.

Add the `execjs` to your Gemfile. That's how we know you need node https://github.com/heroku/heroku-buildpack-ruby/blob/2a7c1c9dc6464e0895bcc9a76607939f105d3952/lib/language_pack/ruby.rb#L801-L803

**Comment by jaredbeck** [comment]
> The way to do this in your app is to define an assets:precompile task.

Modern versions of webpacker (I'm using 5.2) now add itself to `assets:precompile` (or defines it, if necessary). See e.g. `webpacker-5.2.1/lib/tasks/webpacker/compile.rake`.

**Comment by Lordnibbler** [comment]
> > The way to do this in your app is to define an assets:precompile task.
> 
> Three years later, modern versions of webpacker now add itself to `assets:precompile` (or define it, if necessary). See e.g. `webpacker-5.2.1/lib/tasks/webpacker/compile.rake`.

As an addition here, if you remove `sprockets-rails` gem (as is now the default in a rails 7 app), you must remove any reference to `Rails.application.config.assets` from `application.rb`, or any of the environment-specific configuration files like `production.rb`.
