### ISSUE TITLE
Bundler 1.15 causes deployment issues

### ISSUE THREAD

**Issue by urkle** [heroku/heroku-buildpack-ruby#578]
One of our applications was configured (badly) to use the GIT path to the ruby buildpack (instead of heroku/ruby for the last released one).  Thus our deploy picked up the bundler 1.15 upgrade that recently happened.  And now all of our deploys fail.

```
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby.git
remote: =====> Detected Framework: Ruby
remote: -----> Compiling Ruby/Rails
remote:        Your app was upgraded to bundler 1.15.0.
remote:        Previously you had a successful deploy with bundler 1.13.7.
remote:        
remote:        If you see problems related to the bundler version please refer to:
remote:        https://devcenter.heroku.com/articles/bundler-version
remote: -----> Using Ruby version: ruby-2.2.5
remote: -----> Installing dependencies using bundler 1.15.0
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        You are trying to install in deployment mode after changing
remote:        your Gemfile. Run `bundle install` elsewhere and add the
remote:        updated Gemfile.lock to version control.
remote:        Bundler is unlocking ruby
remote:        Bundler Output: You are trying to install in deployment mode after changing
remote:        your Gemfile. Run `bundle install` elsewhere and add the
remote:        updated Gemfile.lock to version control.
remote:        
remote:        Bundler is unlocking ruby
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
```

We found a related bundler bug for this. https://github.com/bundler/bundler/issues/5472

What this means is that IF anyone heroku upgrades to bundler 1.15 users *MUST* upgrade their local environment as well and re-run bundler in order to actually deploy. (at least that's what I read from the bug report.. )   for now we have corrected our buildpacks and switched BACK to the released version of the ruby buildpack

**Comment by Tonkpils** [comment]
I am also running into a similar issue, not the same error but started happening with the 1.15 bundler buildpack.

```
remote:        I, [2017-06-02T15:36:52.691982 #1650]  INFO -- : Copying assets to /tmp/build_eebddd974fa8f7dc484069ff25b409d0/public/assets/tinymce
remote:        rake aborted!
remote:        Errno::ENOENT: No such file or directory @ rb_file_s_stat - /tmp/build_eebddd974fa8f7dc484069ff25b409d0/vendor/bundle/ruby/2.4.0/gems/tinymce-rails-4.3.13
remote:        The latest bundler is 1.15.1, but you are currently running 1.15.0.
remote:        To update, run `gem install bundler`
remote:        /tmp/build_eebddd974fa8f7dc484069ff25b409d0/vendor/bundle/ruby/2.4.0/gems/tinymce-rails-4.3.13/lib/tinymce/rails/asset_installer/copy.rb:30:in `copy_assets'
remote:        /tmp/build_eebddd974fa8f7dc484069ff25b409d0/vendor/bundle/ruby/2.4.0/gems/tinymce-rails-4.3.13/lib/tinymce/rails/asset_installer/copy.rb:13:in `call'
remote:        /tmp/build_eebddd974fa8f7dc484069ff25b409d0/vendor/bundle/ruby/2.4.0/gems/tinymce-rails-4.3.13/lib/tinymce/rails/asset_installer.rb:22:in `install'
remote:        /tmp/build_eebddd974fa8f7dc484069ff25b409d0/lib/tasks/tinymce.rake:17:in `block in <top (required)>'
remote:        /tmp/build_eebddd974fa8f7dc484069ff25b409d0/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
```

clearly the file/directory exists if the backtrace contains files in that directory.

**Comment by Tonkpils** [comment]
Reverting back to bundler 1.13.7 on the buildpack fixed the issue

**Comment by schneems** [comment]
Can you open up a ticket support.heroku.com search for "bundler 1.15.0" and link to this issue so that I can take a look at your app code.

These might be bugs in Bundler that need to be reported.

```
remote:        You are trying to install in deployment mode after changing
remote:        your Gemfile. Run `bundle install` elsewhere and add the
remote:        updated Gemfile.lock to version control.
```

Did you try running `bundle install` locally and pushing again with bundler 1.15.0? No luck?

**Comment by urkle** [comment]
@schneems I did not, as we are currently not ready to update to bundler 1.15  I can have one of my devs test it on a review app and see what happens.

**Comment by schneems** [comment]
> I can have one of my devs test it on a review app and see what happens.

That would be great. You don't need to upgrade to 1.15 you can run `bundle install` with 1.13.7

You can have them use the this in the `app.json` to make sure they're using 1.15.0, otherwise i'm going to revert back to 1.13.7 on master soon.

```
  "buildpacks": [
    {
      "url": "https://github.com/heroku/heroku-buildpack-ruby#schneems/bundler-1.15.0"
    }
```

**Comment by urkle** [comment]
Currently we are using 1.11.2 locally and running bundle install locally works fine (and doesn't change anything in the Gemfile)..  

I created a review app using that buildpack branch and logged a support issue referencing this issue.

**Comment by urkle** [comment]
@schneems ok.. so I just tried updating bundler to 1.13.7 locally re-running bundle install (which made 2 changes to the Gemfile.lock, adding the RUBY VERSION and updating BUNDLED WITH).  and then trying a recreation of the review app..  And I receive the same error.. so definitely something is gone wrong w/ the latest bundler.

**Comment by schneems** [comment]
Thanks! Can you open a ticket so I can check out your Gemfile?

**Comment by urkle** [comment]
@schneems I have opened a heroku ticket already.  Ticket 483128, responded to by Caleb already.

**Comment by schneems** [comment]
We determined that the issue here was with a changing source in a Gemfile.

If someone is running into a similar issue, the best advice is to update to Bundler 1.13.7 or greater and run `bundle install` locally.

Thanks again for reporting.

**Comment by pedroFP** [comment]
> We determined that the issue here was with a changing source in a Gemfile.
> 
> If someone is running into a similar issue, the best advice is to update to Bundler 1.13.7 or greater and run `bundle install` locally.
> 
> Thanks again for reporting.

Does'nt work
