### ISSUE TITLE
Set WEB_CONCURRENCY automatically based on WEB_MEMORY

### ISSUE THREAD

**Issue by dleavitt** [heroku/heroku-buildpack-ruby#581]
The nodejs buildpack does this and it's extremely useful:
https://github.com/heroku/heroku-buildpack-nodejs/blob/master/profile/nodejs.sh#L1-L27

Any reason this isn't part of other buildpacks as well?

**Comment by schneems** [comment]
https://devcenter.heroku.com/changelog-items/618

**Comment by dleavitt** [comment]
Thanks! The way the node buildpack does it is much more useful. Guessing this issue is that's it's unstable?
https://github.com/schneems/heroku_ulimit_to_ram

**Comment by schneems** [comment]
Ulimit is stable. Is node getting ram any other way? What makes it "more useful"?

We can't make this the default because people rely on WEB_CONCURRENCY to not be set in some apps and setting it would cause memory swapping for them.

**Comment by dleavitt** [comment]
The node buildpack computes the concurrency from a WEB_MEMORY env var that you provide, whereas the ruby buildpack just assumes it's 256mb.

**Comment by schneems** [comment]
They use ulimit too https://github.com/heroku/heroku-buildpack-nodejs/blob/29db6b78b9e4f240146dee6660b5f230517a2ee6/profile/nodejs.sh#L18

**Comment by dleavitt** [comment]
Right, they use ulimit too. But they let you declare how much memory your application is likely to use (via the WEB_MEMORY var) whereas the ruby version essentially hardcodes it to 256mb.

**Comment by schneems** [comment]
Ahh, I see what you're saying. That's maybe a good idea for a future iteration of this. I really want totally automated auto scaling. But there are issues with reading memory usage inside of a container.


The memory of processes doesn't totally scale liberally. There's a base and then each process adds to that. I'll have to talk with the node maintainer to see how well their approach is working.

**Comment by dleavitt** [comment]
It's working well for me! For Puma (Rails and non-Rails), and Node apps. I've just been duplicating that logic in my puma config.

**Comment by dleavitt** [comment]
Yeah good point on scaling. So far this has sort of worked to my benefit, since I get the number of process I probably want (low enough to avoid GC pressure and accommodate memory spikes) rather than the maximum number I have RAM for.

Node may also scale more linearly than something like Puma with preload_app enabled, as I don't know if its garbage collector has Ruby's fork-friendly features (guessing not.)

In a preload_app situation, processes 2 and beyond scale linearly though. So I guess if this was implemented in a thorough way you'd want like MASTER_MEMORY and WORKER_MEMORY or something.
