### ISSUE TITLE
Rails 5.1 with Yarn + Sprockets, without Webpacker

### ISSUE THREAD

**Issue by odlp** [heroku/heroku-buildpack-ruby#591]
## Background

A Rails 5.1 project I'm working on uses Yarn + Sprockets, but not Webpacker. Before precompiling assets the JavaScript dependencies are installed:

```ruby
# Rakefile

Rake::Task["assets:precompile"].enhance [:js_deps_install]

task :js_deps_install do
  sh "yarn install"
end
```

However this fails because `yarn` isn't available. Adding `webpacker` to the Gemfile works around the issue:

```ruby
# Gemfile

# Required for Heroku to install yarn
gem "webpacker", require: false
```

## Proposal

Would you be open to a pull request which installs Yarn if:
- The `webpacker` gem is present (existing behaviour)
- *OR* the project root has a `yarn.lock` file present (new behaviour)

Relevant code:
https://github.com/heroku/heroku-buildpack-ruby/blob/2a7c1c9dc6464e0895bcc9a76607939f105d3952/lib/language_pack/ruby.rb#L805:L807

**Comment by schneems** [comment]
You can force yarn to be installed by adding

```
gem 'webpacker', require: false
```

Or you can manually add nodejs buildpack via:

```
$ heroku buildpacks:add --index 1 heroku/nodejs
```

**Comment by odlp** [comment]
Thanks, I hadn't realised adding the NodeJS buildpack was an alternative option.

I think there's merit in considering the presence of a `yarn.lock` file as an indicator to install `yarn`. 

I appreciate this could be considered beyond the responsibility of the Ruby buildpack — plus it overlaps with the NodeJS buildpack — but Rails 5.1 has brought Yarn to the Ruby ecosystem.

**Comment by schneems** [comment]
The ruby buildpack does not run "yarn install" it is up to webpacker to do that. If we added yarn without webpacker you won't get yarn install run and you will have to hook into assets:precompile manually. It's actually simpler to only add the buildpack than to have to do those several steps.

**Comment by odlp** [comment]
Got it, thanks for explaining.
