### ISSUE TITLE
libssl missing

### ISSUE THREAD

**Issue by Kostronor** [heroku/heroku-buildpack-ruby#594]
When using the buildpack i get this error:

`Could not open library 'libssl.so'`

Is there a way to add ssl to the buildpack?

**Comment by schneems** [comment]
https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-aptitude can install packages with this buildpack

**Comment by Kostronor** [comment]
@schneems your link 404s:
![image](https://user-images.githubusercontent.com/644950/27646721-a94604de-5c29-11e7-870a-0e54326cd212.png)
I'll see if I can find the buildpack still. Thanks for the hint.

**Comment by schneems** [comment]
Here you go https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt
