### ISSUE TITLE
Let deployment on compilation failure be configurable

### ISSUE THREAD

**Issue by sivakumar-kailasam** [heroku/heroku-buildpack-ruby#596]
In review apps even when assets fail to compile, the deployment went through (see [build.txt](https://github.com/heroku/heroku-buildpack-ruby/files/1120267/build.txt)). According to @hone it was to support some [legacy rails behavior](https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/ruby.rb#L865). 

If this could be made configurable via the app.json file, we can get the deployment behavior we expect it to follow.

**Comment by schneems** [comment]
if you have the rake and the task then it should fail when precompile fails.

Why do you want a review app with no assets?

You can monkeypatch "assets:precompile" task and wrap it in a rescue block to guarantee the exit code is 0 which would give you what you want.
