### ISSUE TITLE
Rails 5.1 Would like yarn support independent of webpacker.

### ISSUE THREAD

**Issue by Yanchek99** [heroku/heroku-buildpack-ruby#601]
Currently in order to use yarn you must define the webpacker gem in your gemfile.  However one could use yarn in a rails 5.1 project with out needing webpacker.   Could the build pack always include yarn?

**Comment by schneems** [comment]
You can get it by specifying the node and then the ruby buildpack a via the "heroku buildpacks" command.

**Comment by kevynlebouille** [comment]
Hi,

I think that specifying node build pack first is a workaround. In Heroku dashboard, the Ruby app become a Node app because of that.

Since Rails 5.1 use yarn as default JS pkg manager, the ruby build-pack should auto-install yarn if yarn.lock is detected (not only webpacker gem).

**Comment by Yanchek99** [comment]
Solution provided by @schneems does resolve the issue if one wants to use yarn without web packer.  But I agree with @kevynlebouille that it does feel like a workaround.  I like the suggested solution of checking for the yarn.lock instead of the webpacker gem.

**Comment by schneems** [comment]
The next step would be for the ruby buildpack to actually vendor the entire node buildpack. Until that happens you'll need to use 2 buildpacks.

**Comment by atwoodjw** [comment]
Using 2 buildpacks is sub-optimal. I run an expensive Gulp build via `postinstall` script. Using 2 the nodejs + ruby buildpacks means it gets run twice.

**Comment by atwoodjw** [comment]
Actually, it looks like I can get around this by using `heroku-prebuild` instead of `postinstall`.

**Comment by jonhue** [comment]
@schneems 

I'm experiencing that the node modules required within the asset pipeline don't compile, thus are missing in the final production assets.

**Comment by dwightwatson** [comment]
I think it would be great to see better Yarn support in the Ruby buildpack. It appears as though Yarn dependencies aren't cached like Bundler dependencies are which means they have to be reinstalled every time Heroku CI runs or an app build occurs. This greatly increases the time it takes to build the app.

**Comment by valterbarros** [comment]
This did help me https://stackoverflow.com/a/43170792/5990824
