### ISSUE TITLE
Deploying Rails and Angular together fails

### ISSUE THREAD

**Issue by bboynton97** [heroku/heroku-buildpack-ruby#615]
I am trying to deploy a Rails 5 app with an Angular 4 project nested inside it. My server runs fine locally, but will not deploy on Heroku. I am following [this](https://blogstephenarifin.wordpress.com/2017/01/09/angular-2-and-ruby-on-rails-on-heroku/) tutorial, except using `$ ln -s client/dist public` to fix an error in the tutorial.

When pushing to Heroku, I'm using the custom buildpack metnioned in the tutorial, then the Ruby buildpack. The Angular project compiles fine, but then fails when building the Ruby project. I've attached the valuable part of the error log below:

```
remote: -----> Preparing app for Rails asset pipeline
remote:  !
remote:  !     File exists @ dir_s_mkdir - public
remote:  !
remote: /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/vendor/ruby/heroku-16/lib/ruby/2.3.0/fileutils.rb:254:in `mkdir': File exists @ dir_s_mkdir - public (Errno::EEXIST)
```

**Comment by bboynton97** [comment]
It's the heroku/ruby buildpack that is causing the error. The angular project builds fine, it doesn't crash until it starts building the Rails app.

**Comment by schneems** [comment]
I think this has something to do with the symlonk you mentioned. Make sure that it's relative and not absolute. 

https://unix.stackexchange.com/questions/84175/create-a-symbolic-link-relative-to-the-current-directory#84178

**Comment by schneems** [comment]
Here is what the code in that section is doing https://github.com/heroku/heroku-buildpack-ruby/blob/857d13c6903f2378b2a41d29cdd8ad0237ceaec9/lib/language_pack/rails4.rb#L69

**Comment by bboynton97** [comment]
@schneems Still getting the same error. I tried `ln -s ./client/dist public` and `ln -s ../client/dist public` to make it relative. Does that sound right?

**Comment by schneems** [comment]
you can see the symlink by running `ls -la` command. Do that from the root directory of the app. Also try moving the whole app to a new directory on disk locally and see if it still works, i.e. if it's still pointing at the correct location.

If that doesn't work you'll need to open up a support ticket so I can see your app. help.heroku.com. Also run 

```
git push heroku master:support
```

So i can get access to the code.

**Comment by bboynton97** [comment]
Done. Thanks!

--

Brandon Boynton
Vemity <http://vemity.com> Founder and CEO
@bboynton97 <http://twitter.com/bboynton97> | @VemityAI
<http://twitter.com/VemityAI>
