### ISSUE TITLE
Update yarn

### ISSUE THREAD

**Issue by vavgustov** [heroku/heroku-buildpack-ruby#616]
Current yarn v0.22.0 doesn't install bins for nested dependencies. It's result to issues with webpacker v3.0.0 which need 0.25.2 or above.

Description: https://github.com/rails/webpacker/issues/739

**Comment by rcarter** [comment]
+1

**Comment by swrobel** [comment]
Really baffled as to why you guys hardcode yarn/bundler versions. It's fine to have defaults, just let us override them.

**Comment by clemens** [comment]
Shouldn't this be solved by providing some kind of fallback chain:

- Look at the `engines.yarn` key in `yarn.lock` and use the version there. If not found ...
- ... look at some kind of environment variable (`YARN_VERSION`) and use it. If not found ...
- ... download https://yarnpkg.com/latest.tar.gz since this always uses the latest version.

I think this would constitute expected behavior, wouldn't it?

**Comment by wirsslinger** [comment]
+1

**Comment by mbrinkme** [comment]
+1

**Comment by tbsvttr** [comment]
+1

**Comment by dreyks** [comment]
Yarn released `v1.0` maybe we can hardcode it now with less fear that we'll need changing it in a week

**Comment by swrobel** [comment]
@dreyks and then they immediately released 1.0.1 ... classic yarn release cycle 😂

**Comment by schneems** [comment]
Working on #620

**Comment by swrobel** [comment]
Still don't understand why it has to be a hardcoded version...

**Comment by BlakeBurnette** [comment]
It seems a workaround is to set up your buildpack to have nodejs first and then ruby. Passing a yarn -v flag would be amazing

**Comment by AndyGauge** [comment]
@BlakeBurnette I tried to do that, but now I have nodejs after ruby.  How do I reorder them?  When I run heroku buildpacks:add --index 1 heroku/nodejs it says heroku/nodejs already exists.

**Comment by dreyks** [comment]
```console
$ heroku buildpacks:remove heroku/nodejs -a <your_app_name>
$ heroku buildpacks:add --index 1 heroku/nodejs -a <your_app_name>
```

**Comment by AndyGauge** [comment]
@dreyks thank you.  I found documentation saying to use heroku config:unset instead of buildpacks:remove.

**Comment by clemens** [comment]
If I remember correctly, having a nodejs buildpack first results in compiling assets twice. It works, but it's hell of slow.

**Comment by schneems** [comment]
Done https://devcenter.heroku.com/changelog-items/1270

**Comment by clemens** [comment]
@schneems What about a dynamic setting via ENV variable? Any plans in this regard?

**Comment by schneems** [comment]
@clemens see this response in the linked thread https://github.com/heroku/heroku-buildpack-ruby/pull/620#issuecomment-332302820
