### ISSUE TITLE
Engines key in package.json is ignored on deployment

### ISSUE THREAD

**Issue by ordinathorreur** [heroku/heroku-buildpack-ruby#618]
I am trying to specify a Webpacker compatible version of Yarn in my package.json file, but it seems to be ignored. Is this expected behaviour or a bug?

E.g:

```
"engines": {
    "yarn": ">=0.25.2"
  }
```

On deployment the wrong version of Yarn is installed and used:

`remote: -----> Installing yarn-0.22.0`

**Comment by ordinathorreur** [comment]
It seems this is not currently supported in the Ruby build pack, so a workaround for this is to also include the Node build pack before the Ruby build pack:

`heroku buildpacks:add --index 1 heroku/nodejs`

**Comment by luccasmaso** [comment]
Problem: https://github.com/rails/webpacker/issues/405
