### ISSUE TITLE
Update Bundler to 1.15.4

### ISSUE THREAD

**Issue by tbsvttr** [heroku/heroku-buildpack-ruby#626]
This buildpack still uses Bundler on version 1.15.2, but version 1.15.4 has been out for a while: https://rubygems.org/gems/bundler/versions/1.15.4

Please update.

**Comment by schneems** [comment]
Bundler is extremely unstable on Heroku and causes downtime on upgrade, we only upgrade it when there is an active reason to do so.

are you having problems that prevent you from using 1.15.2?

**Comment by tbsvttr** [comment]
I get a warning, but not an error.
