### ISSUE TITLE
Webpacker: elm-stuff not cached

### ISSUE THREAD

**Issue by isaacseymour** [heroku/heroku-buildpack-ruby#627]
We're using Rails 5.1 with Webpacker and Elm in a few apps, and it seems like a lot of the build time is spent running `elm package install --yes` and then re-compiling unchanged elm files. This could be hugely reduced by caching the `elm-stuff` directory during the Heroku build.

1. Is it possible to add cached directories to this buildpack without modifying it? If so how?
2. If not, could you point me in the direction of how to add additional cached directories and would you be open to a PR for this?

**Comment by schneems** [comment]
I would recommend explicitly using the nodejs buildpack. I don’t know if they have any other cache directories you can configure or use.

This might be easier if you can open a support ticket and we can look at your app too.

**Comment by isaacseymour** [comment]
Ah okay. I've already got both the nodejs and ruby buildpacks enabled. I assumed this would belong in ruby because it's more related to webpacker than to node (and I think most things would still work even if I removed the nodejs buildpack - I'd just end up using a different node version I believe). I'll open a support ticket on Monday. Thanks for your help.

**Comment by hone** [comment]
The node.js buildpack supports [custom cache
directories](https://devcenter.heroku.com/articles/nodejs-support#custom-caching).
