### ISSUE TITLE
A Common .ruby-version File For Ruby Projects

### ISSUE THREAD

**Issue by fd** [heroku/heroku-buildpack-ruby#63]
It would be nice if ruby versions could also be specified with a `.ruby-version` file.
Most ruby version managers support this convention now.

See: https://gist.github.com/1912050

**Comment by blackjid** [comment]
Hi @hone sorry for bringing this issue up again.. but there have been developments in bundle that might change things.

This PR have been merged to the `2.0-dev` branch, so is not ready for now, but it shows how bundler is going let you handle ruby versions in the future using `.ruby-version` file. https://github.com/bundler/bundler/pull/4036/files

Do you think that this might change the position on how this heroku buildpack choose the ruby version?

**Comment by schneems** [comment]
We use whatever `bundle ruby` gives us. If bundler wants to support `.ruby-version` and give us a valid result we'll use it.

**Comment by blackjid** [comment]
I finally ended up creating a buildpack that can be used before `heroku-buildpack-ruby` that injects the version from the `.ruby-version` into the `Gemfile` It also support versions without patch.
https://github.com/platanus/heroku-buildpack-ruby-version

Will see that the future brings... :)
