### ISSUE TITLE
Bump Yarn to at least 1.1

### ISSUE THREAD

**Issue by swrobel** [heroku/heroku-buildpack-ruby#630]
1.1 includes [this fix](https://github.com/yarnpkg/yarn/issues/4433) which stops a bunch of spurious "incorrect peer dependency" warnings from being output. I, for one, thought it was a production vs dev issue when I saw them on deploy, but instead it's just yet another "heroku's using outdated yarn" issue.

**Comment by pdfrod** [comment]
I have the same problem: I want to get rid of those warnings when deploying, and bumping Yarn to a more up-to-date version seems to be the way to go.

**Comment by josephpage** [comment]
Hey @swrobel, @pdfrod 

This will be fixed when #714 is merged
Please 👍 the PR !

**Comment by swrobel** [comment]
Well, it only took 6 months, but better late than never
