### ISSUE TITLE
Cannot find bundler gem when starting two apps from subdirs

### ISSUE THREAD

**Issue by wmaciejak** [heroku/heroku-buildpack-ruby#633]
Hi!
I have a repository which has inside frontend wroten in node in `client` directory and backend wroten in ruby in `server` directory. For making this project "deployable" to one app on heroku I added `https://github.com/negativetwelve/heroku-buildpack-subdir` buildpack which is responsible for adding specific buildpacks for specific directories.
I also changed $PATH variable to the:
```bash
/app/server/bin:
/app/server/vendor/bundle/bin:
/app/server/vendor/bundle/ruby/2.4.0/bin:
/usr/local/bin:
/usr/bin:
/bin:
```
Application deploys properly (bundler is visible at that stage), but when I try start  puma process, I see error:
```bash
heroku[server.1]: State changed from up to crashed
app[server.1]:      /usr/lib/ruby/2.3.0/rubygems.rb:241:in `bin_path': can't find gem bundler ([">= 0.a"]) (Gem::GemNotFoundException)
app[server.1]:      from /app/server/vendor/bundle/ruby/2.4.0/bin/bundle:22:in `<main>'
```
but when I go to the gems directory `server/vendor/bundle/ruby/2.4.0/gems` I can see that bundler is installed. 

How can I fix this issue?

**Comment by schneems** [comment]
We don't support running apps from sub directories.
