### ISSUE TITLE
Support Rails ActiveStorage Previews

### ISSUE THREAD

**Issue by dwightwatson** [heroku/heroku-buildpack-ruby#635]
Rails 5.2.0.beta1 shipped today and includes the new ActiveStorage feature. ActiveStorage supports the ability to generate previews of attachments including images, PDFs, and videos on the fly. Images are fine, they can be done by adding the `mini_magick` gem. Additional required for PDFs and videos however.

For PDF previews it appears as though the `mupdf` library is required, and for video previews the `ffmpeg` library is required. [More information is available in the `previewer.rb` file](https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/previewer.rb#L33-L34).

Will Heroku consider adding these libraries to the Ruby buildpack so that Rails developers can utilise these new features, or provide an easy way to make these dependencies available on the platform? Thank you.

**Comment by schneems** [comment]
This is something we'll look into.

In the short term you can try the apt buildpack https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt

**Comment by atstockland** [comment]
@schneems how's this coming on heroku?  I easily added https://github.com/heroku/heroku-buildpack-apt.  I have mini_magick gem and "mupdf-tools" & "imagemagick" in Aptfile...but, getting the following errors:

      MiniMagick::Invalid: `identify /tmp/mini_magick20180105-4-pvub9r` failed with error: identify.im6: no decode delegate for this image format `/tmp/mini_magick20180105-4-pvub9r' @ error/constitute.c/ReadImage/544.

      MiniMagick::Error: `identify -format %m %w %h %b /tmp/ActiveStorage20180105-4-1f46tem[0]` failed with error: identify.im6: no decode delegate for this image format `/tmp/ActiveStorage20180105-4-1f46tem' @ error/constitute.c/ReadImage/544.

Can heroku outline the recommended approach for setting up and accommodating ActiveStorage?

**Comment by atstockland** [comment]
@schneems - is this doable on heroku, yet?

**Comment by hone** [comment]
@atstockland it's being actively worked on atm, but not working yet.
