### ISSUE TITLE
Is there any way to not run db:migrate?

### ISSUE THREAD

**Issue by fchatterji** [heroku/heroku-buildpack-ruby#639]
I'm using heroku ci with the buildpack, and everytime a push is made to github the tests are executed.

It's working fine, except that it also runs a db:migrate script. However, i only have unit tests, no database tests. The db:migrate task could potentially endanger my app database. Is there any way to prevent it from running automatically?

**Comment by falkorichter** [comment]
I had to add the `db:migrate` to the Procfile -> if you don´t add it it should not run.

My `Procfile`:
```
web: bundle exec rails server

release: bundle exec rake db:migrate
```
if you do nothing in `release` nothing should run...

**Comment by cesarizu** [comment]
This is happening for me too. I have declared a `test-setup` script on the `app.json` file and I expected this buildpack wouldn't run the default tasks.
