### ISSUE TITLE
bash: bundle: command not found

### ISSUE THREAD

**Issue by calebthompson** [heroku/heroku-buildpack-ruby#641]
bundle may not be in $PATH in some cases.

```
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
```

Herokai: https://help.heroku.com/tickets/538359

**Comment by hone** [comment]
@calebthompson after looking into that ticket, it's a 3rd party buildpack problem and not a problem with the buildpack. huzzah :)
