### ISSUE TITLE
Ruby 1.8.7 support?

### ISSUE THREAD

**Issue by mockdeep** [heroku/heroku-buildpack-ruby#647]
I know this is probably out of left field, but I've got an [ancient old app](https://github.com/mockdeep/better) I try to keep up and running. The [Heroku Ruby docs](https://devcenter.heroku.com/articles/ruby-support#ruby-versions) suggest that version 1.8.7 should still be supported on `cedar-14`, but when I try to deploy I get an error:

```
remote:  !     Debug InformationCommand: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-build-1.8.7.tgz -s -o - | tar zxf - ' failed unexpectedly:
remote:  !     
remote:  !     gzip: stdin: unexpected end of file
remote:  !     tar: Child returned status 1
remote:  !     tar: Error is not recoverable: exiting now
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
```

It looks like maybe the archive is corrupted or missing. Is there any change of getting it fixed?

**Comment by JoseCapela** [comment]
Hello all,
I am having the exact same error when trying to do a deploy with version 1.8.7.
Can you please assist?

**Comment by nsuchy** [comment]
It looks like you are running an older version of the app, by any chance are you able to upgrade to the newer version? What's holding you back on the older version?

**Comment by schneems** [comment]
Here's the relevant section

> When a Ruby version reaches EOL security patches will no longer be available. We highly recommend running on a version of Ruby that is actively supported by Ruby core. Ruby 1.8.7, 1.9.2 and 1.9.3 have reached EOL. While you can still run them on `cedar-14` stack, security patches are not be applied. Ruby 2.0.0 has reached EOL on Feb. 24th, 2016. The only patch version of `1.9.3` on the platform is `p551`, if you get an error about not being able to install 1.9.3 make sure you are using this patch version in your `Gemfile.lock`. The only patch version of `2.0.0` available on the platform is `p648` if you are not able to install 2.0.0 make sure you are using that patch version in your `Gemfile.lock`.

Ruby 1.8.7 is not "supported" in that if there are security patches they will not be applied to them (so it is very likely insecure). Also if you have a bug specific to 1.8.7 while running on Heroku we technically do not support it.

You'll notice that in the docs these versions are explicitly tied to the `cedar-14` stack https://devcenter.heroku.com/articles/cedar-14-stack

This stack is deprecated and you will not be able to deploy to it after April 2019. 

Until then you'll technically be able to deploy. You must set your stack to `cedar-14`:

```
$ heroku stack:set cedar-14
```

However, I checked and we do not have a Ruby 1.8.7 built for cedar-14. We do have a copy of 1.9.3 you can use. Now you can specify this in your Gemfile:

```
ruby '1.9.3'
```

Keep in mind that this is an extremely temporary workaround (to use Ruby 1.9.3). Both versions have been EOL for a long time and are likely very insecure. To continue running on Heroku long term you'll have to upgrade the app to use a more recent Ruby version. The lowest officially supported ruby version is currently 2.3 and that will become unsupported December 25th 2018. My best suggestion would be to try to upgrade to 2.5 and then keep up with updates. It's much easier to do them as they come then to wait and have to jump several versions at once.

If you cannot upgrade your own app, then I would recommend finding a consultancy to do it for you.

**Comment by schneems** [comment]
If anyone is interested, the oldest Ruby version built for `heroku-16` is 2.2.10. For `heroku-18` it is 2.4.5.
