### ISSUE TITLE
[Question] Install bower (hence npm) to manage JS dependencies installation

### ISSUE THREAD

**Issue by franckverrot** [heroku/heroku-buildpack-ruby#67]
In all recent projects, I am using `bower` to organize and install JS dependencies.

The strategy is to put all those dependencies in a git-ignored folders and let Sprockets find those dependencies.

Do you think it would be worth/sensible adding a new step when building Rails 3+ apps that would run `bower install` (right after `bundle install`) automatically so that the deps are part of the compiled container? Is there another way to approach this problem that I'm missing?

Thanks in advance and thanks for your awesome work!

**Comment by akshayrawat** [comment]
Opened #392 to discuss this, since this issue is fairly dated.
