### ISSUE TITLE
Review apps failing due to invalid byte sequence in UTF-8 encoding error

### ISSUE THREAD

**Issue by heridev** [heroku/heroku-buildpack-ruby#722]
At this moment for me, review apps and manual deployments are failing and I'm surprised that nobody has raised this issue so far.

All tickets I have reported to Heroku about the same issue:
![46d12f4f6e2e7b4b615f980b1783cfd3 _image 202018-03-22 20at 201 22 19 20pm](https://user-images.githubusercontent.com/1863670/37805790-fa1ae8b6-2e01-11e8-85c6-dc9db011a06e.png)

And the past days is been failing with the same error:
![04652b19c13a46192e48b92e1b7fca48 _image 202018-03-22 20at 201 25 48 20pm](https://user-images.githubusercontent.com/1863670/37805805-080cb148-2e02-11e8-90d0-1bc3b5bdb29e.png)

```
       │ │ │   └── whet.extend@0.9.9
       │ │ ├─┬ postcss-unique-selectors@2.0.2
 !
 !     invalid byte sequence in UTF-8
 !
/app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/shell_helpers.rb:135:in `split': invalid byte sequence in UTF-8 (ArgumentError)
```
or some months ago with a different dependency while precompiling assets (Friday 22nd September 2017):
```
      ??? ??? ????????? xtend@4.0.1  deduped
 !
 !     invalid byte sequence in UTF-8
 !
/app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/shell_helpers.rb:124:in `split': invalid byte sequence in UTF-8 (ArgumentError)
```

So as you see, this is been happening from time to time, and after looking at the error, we can see that the line with the problem is:
https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/shell_helpers.rb#L135

Because of an invalid encoding.

If we add a `rescue` in that method:
```
    def puts(message)
      begin

      message.to_s.split("\n").each do |line|
        super "       #{line.strip}"
      end

      rescue Exception => e
        Kernel.puts "========= failing something here ================="
        Kernel.puts e.inspect
        Kernel.puts message.to_s
        Kernel.puts "========= failing something here ================="
      end

      $stdout.flush
    end
```
This is what we would see when there is a message with invalid encoding:
<img width="443" alt="screen shot 2018-03-22 at 4 25 55 pm" src="https://user-images.githubusercontent.com/1863670/37805869-5c2c1aca-2e02-11e8-9ecd-327fc7fa6fb2.png">
<img width="1008" alt="screen shot 2018-03-22 at 4 25 40 pm" src="https://user-images.githubusercontent.com/1863670/37805870-5c412ab4-2e02-11e8-833f-eb496779e963.png">

What do you guys think? I'm about to create a new pull request for it, still working on the specs to reflect the issue.

**Comment by schneems** [comment]
I love the idea. I might tweak some of the output formatting but raising a better error is great. Send me a PR if you can.

**Comment by heridev** [comment]
yes, that was just an example for debugging purposes, I'll let you know once I create the PR @schneems thanks

**Comment by heridev** [comment]
hey @schneems this is the PR https://github.com/heroku/heroku-buildpack-ruby/pull/723 seems like Travis is failing 🤔

**Comment by heridev** [comment]
Btw I added `rspec-mocks`, in case you do not want that dependency do you know an expectation for exercising the `Kernel.puts` execution instead of `expect(Kernel).to receive(:puts)`?

**Comment by heridev** [comment]
hey @schneems, do you know why it is failing(utf encoding exception) if I use the `heroku/ruby` buildpack but it works when I specify the github repository? any ideas?
<img width="1659" alt="70b4841f9532aea435ec5cd5d17dccde _image 2018-03-27 at 4 24 11 pm" src="https://user-images.githubusercontent.com/1863670/37998419-c5c2c754-31db-11e8-9490-2c40937d7c07.png">

**Comment by schneems** [comment]
I don’t know I deployed the buildpack so the UTF 8 patch is live. What backtrace are you getting when it fails?

**Comment by schneems** [comment]
if you push the code to a new app do you get the same failure?

**Comment by heridev** [comment]
I just created a new pr to trigger the review app deployment and it seems to be working just fine, thank you @schneems

**Comment by schneems** [comment]
Glad you got it up and running, thanks for your help!
