### ISSUE TITLE
Remove .git directories from "gems" installed from git sources

### ISSUE THREAD

**Issue by danp** [heroku/heroku-buildpack-ruby#76]
ref #16 

If I have:

``` ruby
gem "rails", :git => "git://github.com/rails/rails.git", :ref => "3-0-stable"
```

In my Gemfile I end up with a directory like:

```
vendor/bundle/ruby/1.9.1/bundler/gems/rails-77403a9b0407
```

in my slug. This directory contains a `.git` directory. In a slug created from an app with the above line in its Gemfile that `.git` directory is 64M. I believe this directory can be removed from the slug and things will still work.

**Comment by schneems** [comment]
We should probably do this

**Comment by dpiddy** [comment]
:+1: I still think this should be safe.

**Comment by rodrigoddalmeida** [comment]
Pinging @schneems. Any news on this?

**Comment by jmccartie** [comment]
:+1:

**Comment by cyx** [comment]
:+1:  Willing to take a stab on this if we're all good with the idea.
