### ISSUE TITLE
New buildpack fails to run `webpack` command

### ISSUE THREAD

**Issue by vincentwoo** [heroku/heroku-buildpack-ruby#778]
Post sprockets CVE, I have made only the following diff to my Rails app's `production.rb`:

```
   # Whether to fallback to assets pipeline if a precompiled asset is missed.
-  config.assets.compile = true
+  config.assets.compile = false
```

However, builds now seem to fail with this error:

```
remote:        Compiling…
remote:        Compilation failed:
remote:        error Command "webpack" not found.
remote:
remote:        yarn run v1.8.0
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote:
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
```

Ironically, this is preventing us from deploying the relevant fix to Sprockets. Help would be urgently appreciated.

**Comment by vincentwoo** [comment]
I should add that we have the Node buildpack at #1, with Ruby at #2, and that our binstubs are present and have been working without issue on all previous successful deploys.

**Comment by schneems** [comment]
Thanks for opening the support ticket. It's much easier to diagnose these things with app logs.

If anyone else is seeing this try to replace `heroku/ruby` in your `heroku buildpacks` with `https://github.com/heroku/heroku-buildpack-ruby#v186` which is the commit right before these changes went out. That will help determine if the latest buildpack deploy was the culprit.

Going to close this issue in favor of communicating over the support ticket. Sorry the app's not able to deploy right now, hopefully we'll get this resolved soon.
