### ISSUE TITLE
Update OpenSSL version

### ISSUE THREAD

**Issue by kevinrobinson** [heroku/heroku-buildpack-ruby#782]
The OpenSSL version bundled with this buildpack is quite out of date ([changelog](https://www.openssl.org/news/changelog.html)).  This seems important for improving server-to-server communication from Heroku dynos.

It looks to me like this buildpack creates Ruby  1.0.2g, which is lagging the latest branch (1.1.0h), but even within 1.0.2 it's over two years behind on patches (latest is 1.0.2o).  This is what I see with the Ruby buildpack set to 2.5.1, run on a `heroku-16` dyno this morning:
```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

$ openssl version -a
OpenSSL 1.0.2g  1 Mar 2016
built on: reproducible build, date unspecified
platform: debian-amd64

$ irb
irb(main):002:0> require 'openssl'
=> true
irb(main):003:0> puts OpenSSL::OPENSSL_VERSION
OpenSSL 1.0.2g  1 Mar 2016
```

I don't know much about buildpacks, but here's a shot at a path forward :)  Looking briefly it seems like a path forward would be to update https://github.com/heroku/heroku-buildpack-ruby/blob/2022ef4fdc9c00a9f068cf44007286626ec34ea3/lib/language_pack/ruby.rb#L98 to include a step that installs an updated version of openssl, and then tells the Ruby build process to use it.  With `rbenv` this looks something like: `RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/opt/openssl@1.1 rbenv install 2.5.1` and I'm figuring there's some similar option that would need to be updated here to make sure the Ruby build looks at the proper path.

As a shorter-term solution, perhaps this buildpack could expose that option so if developers used multiple buildpacks, added [heroku-buildpack-apt](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt) and set it to install an updated openssl, that then this Ruby buildpack would support building with that version of openssl.

**Comment by schneems** [comment]
We don’t build OpenSSL that is provided by the stack image.

The stack image doesn’t update its version instead it uses the same version with security patches that are backported by canonical. This way people can be secure and not have to worry about breaking changes. To get a newer OpenSSL you can try the Heroku-18 stack thoughbif you’re just worried about security we’re patched and should be secure.

**Comment by kevinrobinson** [comment]
@schneems Thanks for learning me!  I hear that this is not the right place in Heroku infrastructure to address this.

I can see in the Heroku docs on [stacks](https://devcenter.heroku.com/articles/stack-packages) that heroku-16 includes openssl `1.0.2g-1​ubuntu4.12` but I don't understand why this is considered secure.  If I look at the openssl [changelog](https://www.openssl.org/news/cl102.txt), there have been two years of patches after that release.  Can you help me understand more about the disconnect in what I see in these version numbers, and your perspective that it's patched and should be secure?

Also your suggestion about heroku-18 is great, thanks for that too!  It looks like heroku-18 includes `1.1.0g-2​ubuntu4` so I'll check out the migration path there separately as well.

**Comment by kevinrobinson** [comment]
ah, you're saying heroku-16 is fixed at 1.0.2g, but that security patches have been backported, but I think one of the disconnects is that most of the changes in subsequent releases seem to be security patches.  Maybe if there's a place to see what is in `1.0.2g-1​ubuntu4.12` or understand what exactly that is might help clarify?  Thanks for your help!

**Comment by schneems** [comment]
This is a better question for https://github.com/heroku/stack-images. All of our stack images are publicly open sourced.

**Comment by kevinrobinson** [comment]
@schneems Great!  Thanks for your help in bouncing me to the right spot :)
