### ISSUE TITLE
Detect and warn on `X-Sendfile` header in rails

### ISSUE THREAD

**Issue by schneems** [heroku/heroku-buildpack-ruby#783]
Now that we can detect rails config, one common thing that comes up is that people are setting the `x_sendfile_header` when they're not using apache or nginx:

```
  # config.action_dispatch.x_sendfile_header = 'X-Sendfile' # for Apache
  # config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect' # for NGINX
```

When they do this requests for files will be returned without a body, but no warning or exception. This is difficult to debug.

The one question is: people can put their apps behind apache or nginx via another buildpack. What is a good way to either detect this automatically i.e. is there a "which nginx` command that we can use to determine if that software is installed, or is there some escape valve we can add that says "I don't care about this warning". Or maybe we do both. 

Great idea by @chap and @halogenandtoast!

**Comment by schneems** [comment]
I couldn't reproduce the issue with an example app. I tried with rails 5.2, 4.2, 3.2. With assets set to compile=true and false. With rack cache and without it.

I've got no idea how to trigger this behavior. I'm not doubting that this behavior exists, but there seems to be some other factors involved in getting it to trigger. If anyone has an app that does not render assets when this config is set, but then serves them fine when this config is toggled off then please let me know.

**Comment by philayres** [comment]
I believe I have seen this behaviour when using `send_file` as a response from a controller. Have you tried that in your setup? My current app (rails 4.2 with webrick) doesn't exhibit it, but I think it may have been a Puma server I've seen it with.
