### ISSUE TITLE
Is it possible to remove node_modules directory after compiling to reduce slug size?

### ISSUE THREAD

**Issue by jtokoph** [heroku/heroku-buildpack-ruby#792]
We are currently using webpacker with our rails app and our slug size is over 300MB now. When I shell into a dyno and run `du -sh node_modules` its shows the node_modules directory using 146MB of space: `146M	node_modules`

My first question is: does this effect the slug size?
My second question is: Since these are used to prebuild the webpacker packs, can the node_modules directory be removed before the final slug is built? How would this work with build caches? I'm not sure how cache directories are saved relative to slugs.

**Comment by dwightwatson** [comment]
Have you got any examples of this? I've tried to enhance the Rake task but it doesn't appear to run on Heroku.

```
Rake::Task['assets:precompile'].enhance do
  FileUtils.remove_dir('node_modules', true)
end
```

**Comment by ericboehs** [comment]
That seemed to work for me. Are you adding it to the Rakefile? This reduce the "Compressing..." time of my deploys by about 5 seconds and reduced the size of my slug size by 50MB.

You could try enhancing `assets:clean` instead.

**Comment by ericboehs** [comment]
Ah yeah. I think `.enhance` runs the block before the task so you'd want to enhance `assets:clean` rather than `assets:precompile`.
