### ISSUE TITLE
Set CI=1 to use webpacker cache

### ISSUE THREAD

**Issue by tribela** [heroku/heroku-buildpack-ruby#801]
Since webpacker checks `CI` environment variable and generate digest **without** mtime of file(https://github.com/rails/webpacker/commit/b26e1da4a1755205d715a7e0e3989f58d5c426fe), buildpack should set `CI` env var to prevent huge time consuming webpack build.

**Comment by swrobel** [comment]
Won't actually help unless this is merged: https://github.com/heroku/heroku-buildpack-ruby/pull/803
