### ISSUE TITLE
Don't warn on `.bundle/config` being present due to caching?

### ISSUE THREAD

**Issue by geoffharcourt** [heroku/heroku-buildpack-ruby#804]
We have a Rails app that uses Webpacker. We get this warning when we build our app:

```
You have the `.bundle/config` file checked into your repository
It contains local state like the location of the installed bundle
as well as configured git local gems, and other settings that should
not be shared between multiple checkouts of a single repo. Please
remove the `.bundle/` folder from your repo and add it to your `.gitignore` file.
https://devcenter.heroku.com/articles/bundler-configuration
```

It comes from here:
https://github.com/heroku/heroku-buildpack-ruby/blob/3466da8832679be26a14c64fc0900e7538aee3eb/lib/language_pack/ruby.rb#L602-L611

We don't our check in this Bundler config in our repo. I suspect this is coming from one of two places. First, we have a private gem (Sidekiq Enterprise) with credentials in the environment, so maybe Bundler creates that file after we bundle to store that credential? The second possibility is that this is created during build caching and stored.

Is it possible to scope this check to verify that the file is actually checked into Git vs. present? I couldn't figure out an easy way to do this, but wanted to check if I was missing something.

Possibly related: https://github.com/heroku/heroku-buildpack-ruby/issues/469

**Comment by schneems** [comment]
Pleas open a support ticket and reference this issue. Go to help.heroku.com and search “bundle config warning” then open a ticket.

You shouldn’t be getting this warning under normal circumstances. I need access to your app to understand exactly why you’re getting it.

**Comment by schneems** [comment]
Unfortunately the git did is stripped before the buildpack gets it so we can’t see what’s checked in and what isn’t.

**Comment by schneems** [comment]
Linking internal ticket id 625672

**Comment by jmanian** [comment]
Was there a general resolution to this @schneems? I just noticed the same warning in our build and we also do not check in that file. I can open a support ticket if appropriate.

**Comment by schneems** [comment]
If you're not checking in that file then it's likely coming from another process or buildpack that may unintentionally leak global settings. I recommend spending some time debugging to see if you can determine what's causing that file to show up in the build

**Comment by jmanian** [comment]
It is indeed [this buildpack](https://github.com/NetsoftHoldings/heroku-buildpack-magic#note), thanks for the tip, sorry for the unnecessary ping.
