### ISSUE TITLE
Heroku deployment problems using 4.0.0.pre3 or 4.0.0.pre2

### ISSUE THREAD

**Issue by elalemanyo** [heroku/heroku-buildpack-ruby#824]
Hi,
Using Ruby 2.5.1, I observed some problems when deploying our apps to heroku after upgrading to Rails v5.2.1 when using webpacker 4.0.0.pre2 or 4.0.0.pre3.

https://github.com/rails/webpacker/issues/1739

**Comment by schneems** [comment]
Does it work locally when you run this command?

```
RAILS_ENV=production rake assets:precompile
```

Please open a ticket at help.heroku.com (search for "webpacker") and I can take a look at your specific app issue.

**Comment by elalemanyo** [comment]
Ok, after I run it locally I saw the same error that I was having on heroku 😞. That means that is not an issue with `heroku-buildpack-ruby`, sorry.

Just in case someone have any Idea this is the error that we are getting:

```
ERROR in ./app/javascript/packs/application_admin.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-plugin-es6-promise'
```

Thanks

**Comment by BennyOnGit** [comment]
did you resolve this elalemanyo?  I have similar issues related somehow to heroku deployment...everything in my app was running smooth, then when i tried to push to heroku with newly added buildpacks (added puppeteer / node / & ruby buildpacks manually in heroku dashboard)...I could no longer get my app running locally.  (I assume this could be issues though with either of those buildpacks or conflicting versions, etc... so apologies if I'm posting in the wrong place). 

`ActionView::Template::Error (Webpacker can't find application.css in /Users/BenBarton/Desktop/Projects/app/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
  "application.js": "/packs/application-7f7c5e8f69606dde935b.js",
  "application.js.map": "/packs/application-7f7c5e8f69606dde935b.js.map",
  "entrypoints": {
    "application": {
      "js": [
        "/packs/application-7f7c5e8f69606dde935b.js"
      ],
      "js.map": [
        "/packs/application-7f7c5e8f69606dde935b.js.map"
      ]
    },
    "hello_vue": {
      "js": [
        "/packs/hello_vue-1e0318d7af50674b6862.js"
      ],
      "js.map": [
        "/packs/hello_vue-1e0318d7af50674b6862.js.map"
      ]
    }
  },
  "hello_vue.js": "/packs/hello_vue-1e0318d7af50674b6862.js",
  "hello_vue.js.map": "/packs/hello_vue-1e0318d7af50674b6862.js.map"
}
):
     8:     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     9:     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    10:     <%= javascript_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    11:     <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    12:    
    13:   </head>
    14: 
`

Originally after deploying to heroku, I couldn't run my bin/webpack-dev-server command locally anymore, and I received this error when trying:

ERROR in ./app/javascript/List.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <template>
|   <div id="App_Sources">
|     <div v-for="source in original_sources">

ERROR in ./app/javascript/TestList.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <template>
|   <div id="app">
|     <div v-for="exhibit in original_exhibits">

ERROR in ./app/javascript/app.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <template>
|   <div id="app">
|     <p>{{ message }}</p>

So I had to reinstall Vue for some reason w/ 'bundle exec rails webpacker:install:vue'.  Not sure...but now I get the first error when running rails -s.
