### ISSUE TITLE
150Mb more memory used with node 10.13.0 than 8.10.0

### ISSUE THREAD

**Issue by teeparham** [heroku/heroku-buildpack-ruby#830]
The memory usage for a single Hobby dyno rails web app was 150Mb higher without the `heroku/nodejs` buildpack.

## A) with heroku/nodejs

Memory: 350Mb

Buildpacks:
```
1. https://github.com/gaffneyc/heroku-buildpack-jemalloc.git
2. https://github.com/cyberdelia/heroku-geo-buildpack.git
3. heroku/nodejs # <-----------------------------------------
4. heroku/ruby
```

Deploy log:
```
remote:        Downloading and installing node 10.13.0...
```

## B) without heroku/nodejs

Memory: 500Mb

Buildpacks:
```
1. https://github.com/gaffneyc/heroku-buildpack-jemalloc.git
2. https://github.com/cyberdelia/heroku-geo-buildpack.git
3. heroku/ruby
```

Deploy log:
```
remote: -----> Installing node-v8.10.0-linux-x64
```

![screen shot 2018-11-21 at 10 58 04 am](https://user-images.githubusercontent.com/54017/48860661-c0bbde80-ed7e-11e8-815b-75a6d0190af5.png)

The rails app uses:

```
  * execjs (2.7.0)
  * sprockets (3.7.2)
  * sprockets-rails (3.2.1)
```

**Comment by nsuchy** [comment]
What optimizations / differences are in the nodejs build back that could be added to the Ruby build pack for it's Node.js support?

**Comment by schneems** [comment]
Can you please open a support ticket so we can look at your app? https://help.heroku.com search for "node higher memory use". Are you using node at runtime in your ruby app? 

cc/ @jmorrell

**Comment by schneems** [comment]
This is relevant since we recently bumped the node version to 10.x on the Ruby buildpack on master, but it hasn't been deployed yet https://github.com/heroku/heroku-buildpack-ruby/pull/831

**Comment by teeparham** [comment]
The ruby app is not using node at runtime. That's why I tried to remove the node buildpack. Yes, I'll open a ticket.

**Comment by schneems** [comment]
Wanted to mention the ultimate root cause if anyone stumbles upon this thread.

The `heroku/nodejs` buildpack will set a default value for `WEB_CONCURRENCY` however the Ruby buildpack will not. So if someone has an app with a line like this in their config:

```
workers Integer(ENV.fetch("WEB_CONCURRENCY") { 1 })
```

Then they would expect the default value to be `1` when in reality the value is set by the node buildpack. 

This can be resolved by not using the node buildpack or by explicitly setting the `WEB_CONCURRENCY` value:

```
$ heroku config:set WEB_CONCURRENCY=1
```
