### ISSUE TITLE
Consider stripping ruby binaries and shared libraries

### ISSUE THREAD

**Issue by dpiddy** [heroku/heroku-buildpack-ruby#88]
The binaries and shared libraries at least in the ruby-2.0.0 tarball are not stripped. If having debug symbols for buildpack ruby builds would be useful, consider packaging them into a separate tarball.

This shows possible size reduction, which could translate into quicker build (less to download) and run (smaller slugs to fetch) times:

```bash
~ $ mkdir t
~ $ curl -o - https://s3.amazonaws.com/heroku-buildpack-ruby/ruby-2.0.0.tgz | tar -C t -zxf -
~ $ du -sh t
83M	t
~ $ find t -type f | xargs file | grep 'not stripped' | awk '{ print $1 }' | cut -d: -f1 | xargs strip
~ $ du -sh t
36M	t
~ $ tar -C t -czf ruby-2.0.0-smaller.tgz .
~ $ du -sh ruby-2.0.0-smaller.tgz 
11M	ruby-2.0.0-smaller.tgz
```

**Comment by schneems** [comment]
I think @hone took care of this?
