### ISSUE TITLE
Buildpack always compiles Ruby despite of cache being persistent between builds

### ISSUE THREAD

**Issue by vladfaust** [heroku/heroku-buildpack-ruby#882]
Hello,

I'm trying to build an application with a buildpack from the list of official Heroku buildpacks. I use a homegrown Docker environment. Each consequent build happens in a separate Docker container. But all builds of a single application share the same cache folder.

### Go

When I use the [sample Go application](https://github.com/heroku/go-getting-started), the [Go buildpack](https://github.com/heroku/heroku-buildpack-go) is detected. It puts the Go binary into the cache. And when I rebuild such an app, it reuses this binary:

**> go-getting-started build 1:**

```
# ls -a /.cache (it's empty)
#21 0.648 .
#21 0.648 ..

#21 0.803 -----> Go detected
...
#21 14.64 -----> New Go Version, clearing old cache
#21 14.64 -----> Installing go1.12.5
#21 14.67 -----> Fetching go1.12.5.linux-amd64.tar.gz... done
...
#21 165.3 -----> Determining packages to install
```

As you can see, there was initially no Go binary in the cache, so buildpack had to download it.

**> go-getting-started build 2:** 

```
# ls -a /.cache (yay, it's not empty)
#21 0.543 .
#21 0.543 ..
#21 0.543 .jq
#21 0.543 go-build-cache
#21 0.543 go1.12.5

#21 0.666 -----> Go detected
...
#21 1.864 -----> Using go1.12.5 
#21 1.938 -----> Determining packages to install
```

In the second build, the buildpack reused the cached Go binary, which allowed to improve the building speed significantly.

### Ruby

In contrary, when I'm trying to build the [sample Ruby application](https://github.com/heroku/ruby-getting-started) with the buildpack found in the repository, the Ruby binary gets rebuilt over and over. However, the bundler cache works.

**> ruby-getting-started build 1:**

```
# ls -a /.cache (empty)
#21 0.626 .
#21 0.626 ..

#21 0.682 -----> Ruby detected
...
#21 115.0 -----> Compiling Ruby/Rails
...
#21 252.6 -----> Using Ruby version: ruby-2.4.4
#21 252.8 -----> Installing dependencies using bundler 1.15.2
#21 283.2        Installing rake 12.3.0
...
#21 329.0        Bundle completed (75.80s)
#21 329.8 -----> Installing node-v10.14.1-linux-x64
...
#21 484.3 -----> Detecting rake tasks
#21 485.9 -----> Preparing app for Rails asset pipeline
#21 485.9        Running: rake assets:precompile
#21 491.5        Asset precompilation completed (5.59s)
#21     duration: 8m15.57309045s
```

First time building, Ruby compilation took about 250 seconds, and bundling took 75. There was also Node installed in 150 seconds and assets compiled in 5.

**> ruby-getting-started build 2:**

```
# ls -a /.cache (filled with buildpack cache)
#21 0.610 .
#21 0.610 ..
#21 0.610 heroku-18
#21 0.610 public
#21 0.610 tmp
#21 0.610 vendor

#21 0.680 -----> Ruby detected
...
#21 96.95 -----> Compiling Ruby/Rails
...
#21 148.7 -----> Using Ruby version: ruby-2.4.4
#21 148.8 -----> Installing dependencies using bundler 1.15.2
...
#21 184.6        Using rake 12.3.0
...
#21 184.7        Bundle completed (33.89s)
#21 185.7 -----> Installing node-v10.14.1-linux-x64
...
#21 338.5 -----> Detecting rake tasks
#21 340.2 -----> Preparing app for Rails asset pipeline
#21 340.2        Running: rake assets:precompile
#21 342.2        Asset precompilation completed (2.04s)
#21     duration: 5m46.798156631s
```

On the next build, we can see that bundler used the cache, as well as assets compilation. But Ruby itself and Node binaries were re-compiled again. It slowed down the building process heavily. Why is that? Should I do any more actions to enable effective caching in this case, and if so, what are they then? FYI in all containers I use `heroku/heroku:18-build` as the base image.

Any help would be highly appreciated.

Thanks in advance,
Vlad

**Comment by schneems** [comment]
The ruby binaries are on S3 and our build cache is also on S3 so whether it gets downloaded via a binary or via our cache it takes the same amount of time. We've instrumented it in the past and since our builds happen in the same region where the binary S3 bucket is, the time it takes to download is extremely fast.
