### ISSUE TITLE
gel support?

### ISSUE THREAD

**Issue by adamaiken89** [heroku/heroku-buildpack-ruby#904]
gel is a promising gem manager that is much faster than bundler
Does it possible to include it in future?

https://github.com/gel-rb/gel

**Comment by schneems** [comment]
I like it as a project. What do you envision such support would look like? In the short-term it would need to be opt-in. We would need some way for customers to specify that they want to use it.

There are other longer reaching concerns to making this a fully supported component. A method and policy for updating the version.

**Comment by adamaiken89** [comment]
I am thinking if it can be supported through a dot file like `.gel`.
If a `.gel` exists, the system will use gel rather than bundler. 
If not, just like what we are currently doing.
