### ISSUE TITLE
removing the "Removing of Gemfile.lock when "windows platform" is detected in it" hack

### ISSUE THREAD

**Issue by urkle** [heroku/heroku-buildpack-ruby#91]
According to the bundler issue https://github.com/carlhuda/bundler/issues/635 this _hack_ is no longer needed as current bundler release (1.1.2 at least) handle this correctly and do not try to install windows gems on unix boxes.

**Comment by schneems** [comment]
Would love to get some more windows parity. Is it worth putting this into an upcoming quarter? Maybe we can fund this feature in bundler?
