### ISSUE TITLE
heroku: error Command "webpack" not found.

### ISSUE THREAD

**Issue by jackjwilliams** [heroku/heroku-buildpack-ruby#929]
So this issue started here with this comment:

https://github.com/rails/webpacker/issues/512#issuecomment-540764611

But I don't want to hijack someone else's thread, so I'm moving it into here. It seems to only be with heroku-buildpack-ruby.

What I've also done in addition to the copied comments from the other thread:

Moved webpack from devDependencies to dependencies in package.json

`heroku run bash`
`yarn global add webpack@latest //(I know, I'm grasping at straws here)`

After doing that and adding the nodejs buildpack before ruby, webpack builds!

But then when the ruby buildpack takes over it still fails with "Command 'webpack' not found". I honestly have no idea how to proceed at this point. I must have 3 webpacks installed at this point (global, node_modules, and /bin). 

Copy of comments from old thread:
I'm getting this same error. I was using the ruby and nodejs buildpack, but based on @schneems feedback I removed nodejs. Neither way can seem to find webpack (with nodejs buildpack or without).

**bin folder**

![image](https://user-images.githubusercontent.com/1746015/66602197-384d5480-eb6f-11e9-8f2c-e9025dd7efc9.png)

**Tail of failure log**

I see this warning `Pattern ["webpack@latest"] is trying to unpack in the same destination "/app/.cache/yarn/v4/npm-webpack-4.41.0-db6a254bde671769f7c14e90a1a55e73602fc70b/node_modules/webpack" as pattern ["webpack@^4.32.2"]. This could result in non-deterministic behavior, skipping.`, not sure if it's relevant. 

![image](https://user-images.githubusercontent.com/1746015/66602249-55822300-eb6f-11e9-8dc8-417e70633e96.png)

**package.json**

```json
{
  "name": "name",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "^6.0.0-alpha",
    "@rails/activestorage": "^6.0.0-alpha",
    "@rails/ujs": "^6.0.0-alpha",
    "@rails/webpacker": "^4.0.7",
    "bootstrap": "4.3.1",
    "datatables.net": "^1.10.20",
    "datatables.net-bs4": "^1.10.20",
    "datatables.net-dt": "^1.10.20",
    "datatables.net-responsive": "^2.2.3",
    "datatables.net-responsive-bs4": "^2.2.3",
    "jquery": "^3.4.1",
    "popper.js": "^1.15.0",
    "turbolinks": "^5.2.0"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack": "latest",
    "webpack-dev-server": "^3.8.0"
  }
}
```

I've tried regenerated bins using `bundle exec rake app:update:bin` and `bundle install --binstubs`

![image](https://user-images.githubusercontent.com/1746015/66604171-3a191700-eb73-11e9-8a99-46f324a3c984.png)

Ruby: 2.6.5
Rails: 6.0.0
Sass-rails: 5
Webpacker: 4.0

**Comment by schneems** [comment]
Can you open a support ticket so I can look at your app? help.heroku.com
search for “webpacker” and link back to this issue.
-- 
Richard Schneeman
https://www.schneems.com

**Comment by jackjwilliams** [comment]
I'm not sure what happened, but deleting my node_modules, re-yarn-installing, then pushing to master seemed to have fixed it!

Must have gotten a hosed yarn lock or something.
