### ISSUE TITLE
Can't use jruby-9.2.9.0on heroku-18 buildpack

### ISSUE THREAD

**Issue by greghuc** [heroku/heroku-buildpack-ruby#933]
Hi there

JRuby 9.2.9.0 isn't working on heroku-18 buildpack.

Would be great if this could be fixed. Error message:

`
remote:  !     Debug InformationCommand: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-2.5.7-jruby-9.2.9.0.tgz -s -o - | tar zxf - ' failed unexpectedly:
`

Getting "access denied" if open given url in browser: https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-2.5.7-jruby-9.2.9.0.tgz

Many thanks

**Comment by greghuc** [comment]
cc @jkutner, is this your department? Just tried to deploy JRuby 9.2.9 to Heroku today, and got the same error message as 3 days ago: 

`
remote:  !     Debug InformationCommand: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-2.5.7-jruby-9.2.9.0.tgz -s -o - | tar zxf - ' failed unexpectedly:
`

**Comment by dentarg** [comment]
Also trying to deploy the new JRuby, still fails. We have contacted Heroku support about it, waiting on their answer.

**Comment by schneems** [comment]
I can confirm this binary doesn't exist but we say it should on our support page https://devcenter.heroku.com/articles/ruby-support#ruby-versions. I've messaged our JRuby maintainer (yes it is Joe). It looks like maybe something went wrong with the upload. We will need to investigate. In the mean time you can use ruby `2.5.3` with jruby `9.2.8.0` on Heroku-18, that version should work.

**Comment by dentarg** [comment]
We are still on 9.2.7.0 because of https://github.com/jruby/jruby/issues/5875, but thanks for acknowledging this issue.

**Comment by hone** [comment]
Hi, sorry for the release snafu. I did the JRuby `9.2.9.0` release on Heroku and we were using our new automated pipeline and ran into issue. I've added some more checks and it should now be fixed.

**Comment by roback** [comment]
I can confirm that it's working for us now.

**Comment by greghuc** [comment]
Working here too - thanks
