### ISSUE TITLE
Task `assets:clean` is executed without checking whether it exists

### ISSUE THREAD

**Issue by j15e** [heroku/heroku-buildpack-ruby#934]
## Context

Using Rails 6 without Sprocket, with Webpacker only.

## What happen

This exception happen after assets compilation : 

>        Done in 5.16s.
>        Asset precompilation completed (64.17s)
>        Cleaning assets
>        Running: rake assets:clean
>        I, [2019-11-25T17:07:47.298404 #605]  INFO -- sentry: ** [Raven] Sending event 5db44a5151c44a8a8699a7ccaa2edf71 to Sentry
>        rake aborted!
>        Don't know how to build task 'assets:clean' (See the list of available tasks with `rake --tasks`)
>        /tmp/build_400672b08b175a998e4d7f78b88ee830/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
>        (See full trace by running task with --trace)
> 

## Why

The task `assets:precompile` is defined when using webpacker or sprocket, but the `assets:clean` is not defined when using only webpacker. 

The rails buidpack check the `assets:precompile` exist before calling it : 

https://github.com/heroku/heroku-buildpack-ruby/blob/1a30c5a0a4c189201a979d6d97bfb38a1aca2572/lib/language_pack/rails4.rb#L84-L85

So I think a simple fix could be to check wether the `assets:clean` exist too before calling it : 

https://github.com/heroku/heroku-buildpack-ruby/blob/1a30c5a0a4c189201a979d6d97bfb38a1aca2572/lib/language_pack/rails4.rb#L98-L99

And /or check also for `webpacker:clean` task and invoke that one when required.

What do you think?

Other stuff I found : 

- Webpacker "enhance" the `assets:clean` task, but only if it exist because sprocket is also used (https://github.com/rails/webpacker/pull/1744/files)
- Related PR https://github.com/heroku/heroku-buildpack-ruby/pull/892

**Comment by SampsonCrowley** [comment]
this is a major issue, how is it still uncommented?

**Comment by schneems** [comment]
> this is a major issue, how is there not a single reply yet?

I missed the original issue when it came in. I can queue this up. It's an easy fix
