### ISSUE TITLE
Question: Is there a reason why binary versions can't be specified without forking?

### ISSUE THREAD

**Issue by rflagreca** [heroku/heroku-buildpack-ruby#937]
Self-explanatory.  We use Node v12 in production (specified in our `package.json`) but the Ruby buildpack is pinned to v10, without any way to customize it (e.g using an ENV variable) without forking.  Is there any particular reason for this?  Ideally, we would not like to fork as this would add further maintenance cost for us.

Our builds only succeed because we run the Node buildpack prior to the Ruby one.  Ideally we would like to re-order the buildpacks and run Webpacker from our Node buildpack (using a build script in `package.json`) however, webpacker is dependent on `bundle install` being run before it.

**Comment by schneems** [comment]
The recommended path forward would be to use both buildpacks `heroku/nodejs` and then `heroku/ruby`.

When Ruby detects that node and yarn are already installed we don't re-install them.

> deally we would like to re-order the buildpacks and run Webpacker from our Node buildpack (using a build script in package.json) however, webpacker is dependent on bundle install being run before it.

I'm not totally sure I follow here. You want to bundle install, then run the node buildpack, then run `assets:precompile` ? Is that a correct interpretaion?

**Comment by rflagreca** [comment]
> I'm not totally sure I follow here. You want to bundle install, then run the node buildpack, then run `assets:precompile` ? Is that a correct interpretaion?

Using both Buildpacks would be ideal, however, as I said - if we run the Ruby buildpack `before` we run the Node Buildpack, the Ruby buildpack fails because we specify Node 12 in our `package.json` (and the Ruby buildpack only installs node 10).  We would then like to skip `assets:precompile` and then execute `./bin/webpack` as part of the Node build.

**Comment by rflagreca** [comment]
> I'm not totally sure I follow here. You want to bundle install, then run the node buildpack, then run `assets:precompile` ? Is that a correct interpretaion?

Using both Buildpacks would be ideal, however, as I said - if we run the Ruby buildpack **before** we run the Node Buildpack, the Ruby buildpack fails at `yarn install` because we specify Node 12 in our `package.json` (and the Ruby buildpack only installs node 10).

This could be avoided if we could skip `assets:precompile` (thus skipping `yarn install`) though, and just rely on our node buildpack to run the webpacker binary.  I don't know if this is possible.  I know we can use `WEBPACKER_DISABLE=true` - but this only skips webpacker.

We need the Ruby buildpack to run before the node buildpack so that we have the required gems available to webpacker when we run `./bin/webpack` from the node buildpack.

So ideally we would like to either:
- Specify to the Ruby Buildpack which Node version to install (e.g v12) so that `yarn install` does not fail, continue to use `WEBPACKER_DISABLE=true` and proceed to run the node buildpack and compile our assets there.

OR 

- Skip `assets:precompile` so the Ruby buildpack doesn't fail at `yarn install` and we can then proceed to run the node buildpack and compile assets from there.

**Comment by rflagreca** [comment]
Hi @schneems - have you had any further thoughts on this?  See my reply above.

**Comment by geoffharcourt** [comment]
@rflagreca we got around this problem when we were using both buildpacks by overwriting the yarn Rake task to make it no-op.
