### ISSUE TITLE
Tests aren't using the correct version of Ruby

### ISSUE THREAD

**Issue by simonrussell** [heroku/heroku-buildpack-ruby#960]
This is a weird one.  Getting output like this from Heroku CI:

Test setup:
```
...
-----> Installing bundler 1.17.3
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Setting up Test for Ruby/Rack
-----> Using Ruby version: ruby-2.5.7
-----> Installing dependencies using bundler 1.17.3
...
```
(which succeeds)

Then the actual test phase:
```
-----> Running Ruby buildpack tests...
-----> Installing bundler 1.17.3
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Running test: bundle exec rspec
bundler: failed to load command: rspec (/app/vendor/bundle/bin/rspec)
Bundler::RubyVersionMismatch: Your Ruby version is 2.6.5, but your Gemfile specified 2.5.7
  /app/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:495:in `validate_ruby!'
  /app/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:470:in `validate_runtime!'
  /app/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:101:in `setup'
  /app/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/setup.rb:20:in `<top (required)>'
  /tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-----> Ruby buildpack tests failed with exit status 1
```

You'll note in the stack trace that somehow it's using 2.6.  If I `heroku ci:debug` and manually run `rspec` or `bundle exec rspec` the tests run, and pass.  This only happens when using the `bin/test` script from the buildpack.

**Comment by simonrussell** [comment]
Further investigation: if we set a `test` script manually in `app.json` (to just run `bundle exec rspec`) then it works.  It's the extra setup steps before the tests run that's killing it.

**Comment by schneems** [comment]
Here’s a PR and failing test I’ve been working on
https://github.com/heroku/heroku-buildpack-ruby/pull/961
-- 
Richard Schneeman
https://www.schneems.com

**Comment by simonrussell** [comment]
Thanks for looking into it @schneems -- I figured it was something along those lines, but kind of didn't really know where to start digging.  It's not a blocker since we figured out the workaround, but it's possible it's affecting other people.

**Comment by schneems** [comment]
Should be fixed with v211
