### ISSUE TITLE
v211 breaks PATH

### ISSUE THREAD

**Issue by bstst** [heroku/heroku-buildpack-ruby#966]
v210 works fine.

v211 fails with this:

```
[4/4] Building fresh packages...
error /app/node_modules/node-sass: Command failed.
Exit code: 127
Command: node scripts/install.js
Arguments: 
Directory: /app/node_modules/node-sass
Output:
/bin/sh: 1: node: not found
```

**Comment by dentarg** [comment]
Probably fixed by https://github.com/heroku/heroku-buildpack-ruby/pull/965

**Comment by schneems** [comment]
v211 Does not include #888 so I’m not so sure that #965 would affect it.

Can you open a support ticket https://help.heroku.com search for “v211 ruby
bullildpack broke” and link back to this ticket so I can see your app?
-- 
Richard Schneeman
https://www.schneems.com
he/him

**Comment by schneems** [comment]
Did you ever open up a support ticket or did you get this fixed some other way?

**Comment by bstst** [comment]
> Did you ever open up a support ticket or did you get this fixed some other way?

I forwarded the request to open a ticket to my lead, it might have been missed.

At the moment I'm doing this in `app.json` to fix the issue:

```
"buildpacks": [
        ...snip,
        { "url": "https://github.com/heroku/heroku-buildpack-ruby#v210" },
        ...snip,
      ],
```
