### ISSUE TITLE
Out of date vulcan mention in README?

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-ruby#981]
Hi!

This section of the readme mentions [vulcan](http://github.com/heroku/vulcan):
https://github.com/heroku/heroku-buildpack-ruby#hacking 

...but the repo for that project mentions it's deprecated.

Are the rest of the steps in that section of the readme still correct? :-)

**Comment by schneems** [comment]
Removing in https://github.com/heroku/heroku-buildpack-ruby/pull/991
