### ISSUE TITLE
Use newest possible Ruby version if Gemfile contains version range

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-ruby#983]
Currently if a project's `Gemfile` contains a Ruby version range (rather than a fixed version), such as:
```
ruby '>= 2.3.5', '< 2.7'
```

...and the project's `Gemfile.lock` does not specify a Ruby version (ie no `RUBY VERSION` section), then the Ruby buildpack uses the earliest/oldest Ruby version that meets the `Gemfile` version range, rather than picking the newest Ruby version that still meets the range.

In the example snippet above, this means the Ruby buildpack tries to use Ruby 2.3.5 (which is EOL and insecure) rather than Ruby 2.6.x which would still meet the version upper bound of `< 2.7`.

If using the newest possible version would be too risky (or a pain to compute), then perhaps the buildpack could at least check if the version is EOL, and if so, fall back to the default Ruby version iff it still meets the range.

**Comment by schneems** [comment]
> ...and the project's Gemfile.lock does not specify a Ruby version (ie no RUBY VERSION section), 

When you run `bundle install` it puts your Ruby version in the `Gemfile.lock` and that's what Heroku uses (as you noted). I would be interested in more context where you saw a project that has a range but no Ruby version listed. 

> If using the newest possible version would be too risky (or a pain to compute), then perhaps the buildpack could at least check if the version is EOL, and if so, fall back to the default Ruby version iff it still meets the range.

The ruby buildpack can not resolve "2.7" to a version of Ruby right now. It doesn't know what versions of Ruby exist and it wouldn't know (without additional features) how to find 2.6.6 based off of that designation. I did write code to "walk" versions up or down, so I could possibly write code to accomplish this, however...

Right now the Ruby buildpack doesn't know there's been a version range specified, we get our information from `bundle platform --ruby` output:

```
$ cat Gemfile
source 'https://rubygems.org'

ruby "> 2.3", "< 2.8"
⛄ 2.7.1 🚀  /tmp/67f8fb1624349f809bbab6521d9d3608 (master)
$ bundle platform --ruby
ruby 2.3
```

It was my previous belief that it was very difficult or unlikely to have a project that specified a Ruby version that was not in the Gemfile.lock. If you've got some additional context, I would be happy to re-visit that assumption and try to figure out a good experience for your use case.

**Comment by edmorley** [comment]
Ah so the context here was me first trying to build https://github.com/heroku/ruby-getting-started on Heroku-20 but getting the "Ruby 2.4.x not available" error, then being lazy (plus not knowing what `pNNN` suffix to put at the end of the Ruby version string in `Gemfile.lock`), I just removed the `Gemfile.lock` Ruby version entirely, thinking the buildpack might just pick default Ruby (which I seemed to remember was 2.6.6).

However it sounds like this scenario would be rare (I'm presuming most people don't add Ruby version ranges to their Gemfile, particularly if they are also not using other best practices like a Gemfile.lock), and I can see the difficulty in resolving version ranges - so happy just to close this out for now :-)
